(()=>{
 const header=document.querySelector('.admin-header');if(!header)return;
 const brand=header.firstElementChild;brand.classList.add('admin-brand');const logo=document.createElement('img');logo.src='apanam-header-logo-original.png?v=1';logo.alt='APANAM';logo.className='admin-brand-logo';brand.prepend(logo);
 const form=document.getElementById('studioCloudLogin')||document.getElementById('memberLogin');if(!form)return;
 const wrapper=document.createElement('div');wrapper.className='account-login-layout';form.before(wrapper);const loginDetails=document.createElement('details');loginDetails.className='account-login-details';const loginSummary=document.createElement('summary');loginSummary.textContent='Login / Account बदलें';loginDetails.append(loginSummary,form);wrapper.append(loginDetails);
 const profile=document.createElement('aside');profile.className='account-photo';const photo=document.createElement('img');photo.alt='Profile photo';photo.hidden=true;const fallback=document.createElement('span');fallback.className='account-avatar';fallback.textContent='A';
 const label=document.createElement('label');label.textContent='Photo लगाएँ';const picker=document.createElement('input');picker.type='file';picker.accept='image/png,image/jpeg,image/webp';picker.hidden=true;label.append(picker);
 const remove=document.createElement('button');remove.type='button';remove.textContent='हटाएँ';const note=document.createElement('small');note.textContent='Photo इस browser में सेव होगी।';const status=document.createElement('p');status.setAttribute('role','status');profile.append(fallback,photo,label,remove,note,status);wrapper.append(profile);
 let key='';function refresh(){const user=window.APANAM_CLOUD?.user();loginDetails.open=!user;loginSummary.textContent=user?'Account बदलें / Logout':'Login करें';note.textContent=user?.email||'Photo इस browser में सेव होगी।';key=user?.id?'apanam-profile-photo-'+user.id:'';picker.disabled=!key;remove.disabled=!key;label.classList.toggle('disabled',!key);let saved='';try{saved=key?localStorage.getItem(key)||'':'';}catch{}photo.src=saved;photo.hidden=!saved;fallback.hidden=!!saved;status.textContent=key?'':'Photo लगाने के लिए Login करें।';}
 picker.onchange=async()=>{const file=picker.files[0];if(!file)return;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024)throw Error('PNG/JPG/WebP चुनें, अधिकतम 5 MB।');const currentKey=key;if(!currentKey)throw Error('पहले Login करें।');const image=await createImageBitmap(file);const canvas=document.createElement('canvas');canvas.width=canvas.height=160;const ctx=canvas.getContext('2d');const size=Math.min(image.width,image.height);ctx.drawImage(image,(image.width-size)/2,(image.height-size)/2,size,size,0,0,160,160);image.close();if(key!==currentKey)throw Error('Account बदल गया। फिर चुनें।');localStorage.setItem(currentKey,canvas.toDataURL('image/jpeg',.85));refresh();status.textContent='Photo सेव हुई।';}catch(error){status.textContent=error.message;}finally{picker.value='';}};
 remove.onclick=()=>{try{if(key)localStorage.removeItem(key);refresh();status.textContent='Photo हटाई गई।';}catch{status.textContent='Photo नहीं हट सकी।';}};document.addEventListener('apanam-cloud-session',refresh);refresh();
})();