(()=>{
 const header=document.querySelector('.admin-header')||document.querySelector('body>header');if(!header||document.getElementById('studioHeaderAccount'))return;const editor=!header.classList.contains('admin-header');
 if(!editor){const brand=header.firstElementChild;brand.classList.add('admin-brand');const logo=document.createElement('img');logo.src='apanam-header-logo-original.png?v=1';logo.alt='APANAM AI';logo.className='admin-brand-logo';brand.prepend(logo);}
 const login=document.getElementById('studioCloudLogin')||document.getElementById('memberLogin');if(!login&&!editor)return;
 const wrapper=document.createElement('div');wrapper.className='account-login-layout';if(login)login.before(wrapper);const loginDetails=document.createElement('details');loginDetails.className='account-login-details';const summary=document.createElement('summary');loginDetails.append(summary);if(login)loginDetails.append(login);wrapper.append(loginDetails);
 const card=document.createElement('details');card.id='studioHeaderAccount';card.className='header-account'+(editor?' editor-header-account':'');const trigger=document.createElement('summary');trigger.setAttribute('aria-label','Account विकल्प खोलें');trigger.setAttribute('aria-controls','studioAccountMenu');const avatar=document.createElement('img');avatar.alt='Profile photo';avatar.hidden=true;const initials=document.createElement('span');initials.className='account-avatar';initials.textContent='A';const name=document.createElement('span');name.className='header-account-name';trigger.append(initials,avatar,name);const menu=document.createElement('div');menu.id='studioAccountMenu';menu.className='header-account-menu';const open=document.createElement('button');open.type='button';open.textContent='मेरा Profile';const validity=document.createElement('button');validity.type='button';validity.textContent='Membership / Validity';const logout=document.createElement('button');logout.type='button';logout.textContent='Logout';const signIn=document.createElement('button');signIn.type='button';signIn.textContent='Login करें';menu.append(open,validity,logout,signIn);card.append(trigger,menu);header.append(card);
 document.addEventListener('click',e=>{if(!card.contains(e.target))card.open=false;});card.addEventListener('keydown',e=>{if(e.key==='Escape'){card.open=false;trigger.focus();}});
 card.addEventListener('toggle',()=>{trigger.setAttribute('aria-expanded',String(card.open));if(editor&&card.open){const b=trigger.getBoundingClientRect();menu.style.top=(b.bottom+6)+'px';menu.style.left=Math.max(8,Math.min(b.right-210,innerWidth-218))+'px';}});
 signIn.onclick=()=>{card.open=false;if(!login){window.APANAM_PROJECT?.save();location.href='membership.html';return;}document.querySelector('nav a[href="#cloud"]')?.click();loginDetails.open=true;login.scrollIntoView({block:'center',behavior:'smooth'});login.querySelector('input')?.focus();};
 logout.onclick=async()=>{card.open=false;window.APANAM_PROJECT?.save();if(editor){try{await window.APANAM_CLOUD?.signOut();}catch(e){status.textContent='Logout नहीं हुआ: '+e.message;}}else{document.getElementById('studioCloudLogout')?.click();document.getElementById('memberLogout')?.click();}};

 const dialog=document.createElement('dialog');dialog.id='studioProfileDialog';dialog.className='profile-dialog';dialog.setAttribute('aria-labelledby','profileTitle');const title=document.createElement('h2');title.id='profileTitle';title.textContent='मेरा Profile';const close=document.createElement('button');close.type='button';close.className='profile-close';close.textContent='×';close.setAttribute('aria-label','Profile बंद करें');close.onclick=()=>dialog.close();
 const form=document.createElement('form');form.className='profile-form';const inputs={};for(const [key,label,max] of [['full_name','पूरा नाम',120],['phone','Mobile (स्वयं भरा हुआ)',32],['whatsapp','WhatsApp number (country code सहित)',32],['organization','संस्था / Business नाम',160],['city','शहर',100],['website','Website / Social link',200]]){const l=document.createElement('label'),input=document.createElement('input');l.textContent=label;input.name=key;input.maxLength=max;if(key==='phone'||key==='whatsapp')input.type='tel';inputs[key]=input;l.append(input);form.append(l);}
 const photos=document.createElement('div');photos.className='profile-photo-controls';const preview=document.createElement('img');preview.alt='आपकी Profile photo';preview.hidden=true;const label=document.createElement('label');label.textContent='Photo चुनें';const picker=document.createElement('input');picker.type='file';picker.accept='image/png,image/jpeg,image/webp';label.append(picker);const remove=document.createElement('button');remove.type='button';remove.textContent='Photo हटाएँ';photos.append(preview,label,remove);form.prepend(photos);
 const records=document.createElement('dl');records.className='profile-records';const status=document.createElement('p');status.setAttribute('role','status');const save=document.createElement('button');save.type='submit';save.textContent='Profile सेव करें';const reload=document.createElement('button');reload.type='button';reload.textContent='स्थिति Refresh';form.append(records,save,reload,status);const heading=document.createElement('div');heading.className='profile-heading';heading.style.cssText='position:sticky;top:0;z-index:3;display:flex;align-items:center;justify-content:space-between;gap:12px;background:white;padding:8px 0;border-bottom:1px solid #ede9fe;margin-bottom:12px';title.style.margin='0';close.style.position='static';heading.append(title,close);dialog.append(heading,form);document.body.append(dialog);
 let record=null,pendingPhoto='',sequence=0,saving=false;const cloud=window.APANAM_CLOUD;
 function photo(){preview.src=pendingPhoto;preview.hidden=!pendingPhoto;}
 function row(label,value){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value||'—';records.append(dt,dd);}
 const date=value=>value?new Date(value).toLocaleString('hi-IN',{timeZone:'Asia/Kolkata'}):'—';
 function effective(){if(record?.entitlement?.expires_at)return {...record.entitlement,granted_at:record.entitlement.started_at};return record?.membership||null;}
 const planName=m=>m?.kind==='paid'?'Paid Manual':m?.kind==='trial'?'Trial':'मुफ्त Business Manual';
 function fill(){if(!record)return;const p=record.profile||{};for(const key in inputs)inputs[key].value=p[key]||'';pendingPhoto=p.avatar_data||'';if(!pendingPhoto){try{pendingPhoto=localStorage.getItem('apanam-profile-photo-'+record.user.id)||'';}catch{}}photo();records.replaceChildren();const m=effective();row('Email',record.user.email);row('भूमिका',record.admin?'Admin':'User');row('User ID',record.user.id);row('Account बना',date(record.user.created_at));row('Email verified',record.user.email_confirmed_at?'हाँ':'नहीं');row('पिछला Login',date(record.user.last_sign_in_at));row('Manual योजना',m?planName(m):'अभी खुला manual editor');row('Membership शुरू',date(m?.granted_at));row('Membership समाप्त',date(m?.expires_at));row('Membership स्थिति',m?m.revoked?'Access वापस लिया गया':Date.parse(m.expires_at)>Date.now()?'सक्रिय':'अवधि समाप्त':'कोई membership grant नहीं');if(m&&!m.revoked&&Date.parse(m.expires_at)>Date.now())row('बचे दिन',String(Math.ceil((Date.parse(m.expires_at)-Date.now())/86400000)));row('Payment','वर्तमान स्थिति और अपने receipts Membership पेज पर देखें');row('Paid AI','Provider अभी सक्रिय नहीं');row('Profile अपडेट',date(p.updated_at));}
 
 const notice=document.createElement('div');notice.id='studioValidityNotice';notice.hidden=true;notice.setAttribute('role','status');notice.style.cssText='position:fixed;right:12px;top:66px;z-index:10010;max-width:calc(100vw - 24px);width:320px;padding:12px;background:#fff7ed;border:1px solid #fdba74;border-radius:10px;box-shadow:0 8px 28px #17203322;color:#7c2d12;font:13px Arial,sans-serif;display:flex;gap:10px;align-items:start';const noticeText=document.createElement('span'),noticeClose=document.createElement('button');noticeClose.type='button';noticeClose.textContent='×';noticeClose.setAttribute('aria-label','Validity सूचना बंद करें');noticeClose.style.cssText='border:0;background:transparent;font-size:20px;cursor:pointer';notice.append(noticeText,noticeClose);document.body.append(notice);let noticeTimer;function hideNotice(){notice.hidden=true;notice.style.display='none';clearTimeout(noticeTimer);}noticeClose.onclick=hideNotice;hideNotice();
 function validityNotice(){const m=effective();validity.textContent='Membership / Validity';if(!m||!cloud.user()||record.admin)return;const days=Math.ceil((Date.parse(m.expires_at)-Date.now())/86400000);validity.textContent=m.revoked?'Validity · वापस लिया गया':days<=0?'Validity · समाप्त':'Validity · '+days+' दिन';if(!m.revoked&&days>7)return;const day=new Date().toLocaleDateString('en-CA'),key='apanam-validity-notice-'+record.user.id,stamp=day+':'+m.expires_at+':'+m.revoked;try{if(localStorage.getItem(key)===stamp)return;localStorage.setItem(key,stamp);}catch{}noticeText.textContent=m.revoked?'मुफ्त Business membership वापस ली गई है। Admin से संपर्क करें। अभी manual editor खुला है।':days<=0?'Membership की अवधि समाप्त है। Renewal के लिए Membership पेज देखें। अभी manual editor खुला है।':'आपकी '+planName(m)+' membership '+days+' दिन में समाप्त होगी। Renewal के लिए Membership पेज देखें।';notice.hidden=false;notice.style.display='flex';clearTimeout(noticeTimer);noticeTimer=setTimeout(hideNotice,10000);}

 function render(){const user=cloud?.user();if(login)loginDetails.open=!user;summary.textContent=user?'Account बदलें / Logout':'Login करें';open.disabled=!user;validity.disabled=!user;logout.hidden=!user;signIn.hidden=!!user;const p=record?.profile;name.textContent=user?(p?.full_name||'मेरा Account')+' · '+(record?.admin?'Admin':'User'):'Login';const src=p?.avatar_data||'';avatar.src=src;avatar.hidden=!src;initials.hidden=!!src;initials.textContent=(p?.full_name||user?.email||'A').slice(0,1).toUpperCase();if(record)validityNotice();if(!user)hideNotice();}
 async function refresh(){const n=++sequence,userId=cloud?.user()?.id;record=null;records.replaceChildren();for(const input of Object.values(inputs))input.value='';pendingPhoto='';photo();render();if(!userId){dialog.close();return;}try{const value=await cloud.accountProfile();if(n!==sequence||cloud?.user()?.id!==userId||value.user?.id!==userId)return;record=value;render();if(dialog.open){fill();status.textContent='Profile cloud से खुली।';}}catch(e){if(n===sequence)status.textContent='Profile नहीं खुली: '+e.message;}}
 open.onclick=async()=>{card.open=false;dialog.showModal();status.textContent='जानकारी लोड हो रही है…';save.disabled=true;await refresh();if(record){fill();status.textContent='जानकारी बदलकर Profile सेव करें।';save.disabled=false;}};
 validity.onclick=async()=>{await open.onclick();if(dialog.open)records.scrollIntoView({block:'nearest',behavior:'smooth'});};
 reload.onclick=()=>{if(!saving)refresh();};picker.onchange=async()=>{const file=picker.files[0];if(!file)return;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024)throw Error('PNG/JPG/WebP चुनें, अधिकतम 5 MB।');const image=await createImageBitmap(file);const canvas=document.createElement('canvas');canvas.width=canvas.height=160;const ctx=canvas.getContext('2d'),size=Math.min(image.width,image.height);ctx.drawImage(image,(image.width-size)/2,(image.height-size)/2,size,size,0,0,160,160);image.close();pendingPhoto=canvas.toDataURL('image/jpeg',.85);photo();status.textContent='Photo चुनी। Profile सेव करें।';}catch(e){status.textContent=e.message;}finally{picker.value='';}};
 remove.onclick=()=>{pendingPhoto='';photo();status.textContent='Photo हटाने के लिए Profile सेव करें।';};
 form.onsubmit=async e=>{e.preventDefault();if(saving||!record)return;saving=true;save.disabled=true;picker.disabled=true;remove.disabled=true;const userId=record.user.id;try{const value={avatar_data:pendingPhoto};for(const key in inputs)value[key]=inputs[key].value;const saved=await cloud.saveProfile(value);if(cloud.user()?.id!==userId)return;record.profile=saved;try{localStorage.removeItem('apanam-profile-photo-'+userId);}catch{}render();fill();status.textContent='Profile और photo cloud में सेव हुईं।';}catch(e){status.textContent='Profile सेव नहीं हुई: '+e.message;}finally{saving=false;save.disabled=false;picker.disabled=false;remove.disabled=false;}};
 document.addEventListener('apanam-membership-updated',refresh);document.addEventListener('apanam-cloud-session',refresh);Promise.resolve(cloud?.authReady).then(refresh);
})();
