(()=>{
 const header=document.querySelector('.admin-header');if(!header)return;
 const brand=header.firstElementChild;brand.classList.add('admin-brand');const logo=document.createElement('img');logo.src='apanam-header-logo-original.png?v=1';logo.alt='APANAM AI';logo.className='admin-brand-logo';brand.prepend(logo);
 const login=document.getElementById('studioCloudLogin')||document.getElementById('memberLogin');if(!login)return;
 const wrapper=document.createElement('div');wrapper.className='account-login-layout';login.before(wrapper);const loginDetails=document.createElement('details');loginDetails.className='account-login-details';const summary=document.createElement('summary');loginDetails.append(summary,login);wrapper.append(loginDetails);
 const card=document.createElement('aside');card.className='account-photo';const avatar=document.createElement('img');avatar.alt='Profile photo';avatar.hidden=true;const initials=document.createElement('span');initials.className='account-avatar';initials.textContent='A';const open=document.createElement('button');open.type='button';open.textContent='मेरा Profile';const name=document.createElement('small');card.append(initials,avatar,open,name);wrapper.append(card);
 const dialog=document.createElement('dialog');dialog.className='profile-dialog';dialog.setAttribute('aria-labelledby','profileTitle');const title=document.createElement('h2');title.id='profileTitle';title.textContent='मेरा Profile';const close=document.createElement('button');close.type='button';close.className='profile-close';close.textContent='×';close.setAttribute('aria-label','Profile बंद करें');close.onclick=()=>dialog.close();
 const form=document.createElement('form');form.className='profile-form';const inputs={};for(const [key,label,max] of [['full_name','पूरा नाम',120],['phone','Mobile (स्वयं भरा हुआ)',32],['organization','संस्था / Business नाम',160],['city','शहर',100],['website','Website / Social link',200]]){const l=document.createElement('label'),input=document.createElement('input');l.textContent=label;input.name=key;input.maxLength=max;if(key==='phone')input.type='tel';inputs[key]=input;l.append(input);form.append(l);}
 const photos=document.createElement('div');photos.className='profile-photo-controls';const preview=document.createElement('img');preview.alt='आपकी Profile photo';preview.hidden=true;const label=document.createElement('label');label.textContent='Photo चुनें';const picker=document.createElement('input');picker.type='file';picker.accept='image/png,image/jpeg,image/webp';label.append(picker);const remove=document.createElement('button');remove.type='button';remove.textContent='Photo हटाएँ';photos.append(preview,label,remove);form.prepend(photos);
 const records=document.createElement('dl');records.className='profile-records';const status=document.createElement('p');status.setAttribute('role','status');const save=document.createElement('button');save.type='submit';save.textContent='Profile सेव करें';const reload=document.createElement('button');reload.type='button';reload.textContent='स्थिति Refresh';form.append(records,save,reload,status);dialog.append(title,close,form);document.body.append(dialog);
 let record=null,pendingPhoto='',sequence=0,saving=false;const cloud=window.APANAM_CLOUD;
 function photo(){preview.src=pendingPhoto;preview.hidden=!pendingPhoto;}
 function row(label,value){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value||'—';records.append(dt,dd);}
 const date=value=>value?new Date(value).toLocaleString('hi-IN'):'—';
 function fill(){if(!record)return;const p=record.profile||{};for(const key in inputs)inputs[key].value=p[key]||'';pendingPhoto=p.avatar_data||'';if(!pendingPhoto){try{pendingPhoto=localStorage.getItem('apanam-profile-photo-'+record.user.id)||'';}catch{}}photo();records.replaceChildren();const m=record.membership;row('Email',record.user.email);row('भूमिका',record.admin?'Admin':'User');row('User ID',record.user.id);row('Account बना',date(record.user.created_at));row('Email verified',record.user.email_confirmed_at?'हाँ':'नहीं');row('पिछला Login',date(record.user.last_sign_in_at));row('Manual योजना',m?'मुफ्त Business Manual':'अभी खुला manual editor');row('Membership शुरू',date(m?.granted_at));row('Membership समाप्त',date(m?.expires_at));row('Membership स्थिति',m?m.revoked?'Access वापस लिया गया':Date.parse(m.expires_at)>Date.now()?'सक्रिय':'अवधि समाप्त':'कोई membership grant नहीं');if(m&&!m.revoked&&Date.parse(m.expires_at)>Date.now())row('बचे दिन',String(Math.ceil((Date.parse(m.expires_at)-Date.now())/86400000)));row('AI / Payment','Paid AI और payment अभी सक्रिय नहीं');row('Profile अपडेट',date(p.updated_at));}
 function render(){const user=cloud?.user();loginDetails.open=!user;summary.textContent=user?'Account बदलें / Logout':'Login करें';open.disabled=!user;const p=record?.profile;name.textContent=user?(p?.full_name||user.email)+' · '+(record?.admin?'Admin':'User'):'पहले Login करें';const src=p?.avatar_data||'';avatar.src=src;avatar.hidden=!src;initials.hidden=!!src;initials.textContent=(p?.full_name||user?.email||'A').slice(0,1).toUpperCase();}
 async function refresh(){const n=++sequence;record=null;render();if(!cloud?.user()){dialog.close();return;}try{const value=await cloud.accountProfile();if(n!==sequence)return;record=value;render();if(dialog.open){fill();status.textContent='Profile cloud से खुली।';}}catch(e){if(n===sequence)status.textContent='Profile नहीं खुली: '+e.message;}}
 open.onclick=async()=>{dialog.showModal();status.textContent='जानकारी लोड हो रही है…';save.disabled=true;await refresh();if(record){fill();status.textContent='जानकारी बदलकर Profile सेव करें।';save.disabled=false;}};
 reload.onclick=()=>{if(!saving)refresh();};picker.onchange=async()=>{const file=picker.files[0];if(!file)return;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024)throw Error('PNG/JPG/WebP चुनें, अधिकतम 5 MB।');const image=await createImageBitmap(file);const canvas=document.createElement('canvas');canvas.width=canvas.height=160;const ctx=canvas.getContext('2d'),size=Math.min(image.width,image.height);ctx.drawImage(image,(image.width-size)/2,(image.height-size)/2,size,size,0,0,160,160);image.close();pendingPhoto=canvas.toDataURL('image/jpeg',.85);photo();status.textContent='Photo चुनी। Profile सेव करें।';}catch(e){status.textContent=e.message;}finally{picker.value='';}};
 remove.onclick=()=>{pendingPhoto='';photo();status.textContent='Photo हटाने के लिए Profile सेव करें।';};
 form.onsubmit=async e=>{e.preventDefault();if(saving||!record)return;saving=true;save.disabled=true;picker.disabled=true;remove.disabled=true;const userId=record.user.id;try{const value={avatar_data:pendingPhoto};for(const key in inputs)value[key]=inputs[key].value;const saved=await cloud.saveProfile(value);if(cloud.user()?.id!==userId)return;record.profile=saved;try{localStorage.removeItem('apanam-profile-photo-'+userId);}catch{}render();fill();status.textContent='Profile और photo cloud में सेव हुईं।';}catch(e){status.textContent='Profile सेव नहीं हुई: '+e.message;}finally{saving=false;save.disabled=false;picker.disabled=false;remove.disabled=false;}};
 document.addEventListener('apanam-cloud-session',refresh);refresh();
})();