(()=>{
  const stage=document.getElementById('stage');if(!stage||!window.indexedDB)return;
  let connection;
  const db=()=>connection??=new Promise((resolve,reject)=>{const request=indexedDB.open('apanam-asset-library',1);request.onupgradeneeded=()=>request.result.createObjectStore('assets',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
  async function query(method,value,mode='readonly'){const database=await db();return new Promise((resolve,reject)=>{const tx=database.transaction('assets',mode),request=tx.objectStore('assets')[method](value);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
  const overlay=document.createElement('div');overlay.className='apanam-assets-overlay';overlay.hidden=true;overlay.innerHTML=`<section class="apanam-assets" role="dialog" aria-modal="true" aria-labelledby="apanam-assets-title"><header><div><small>APANAM CREATIVE STUDIO</small><h2 id="apanam-assets-title">मेरी Assets Library</h2><p>Logo और Product photo एक बार सेव करें, फिर किसी भी पोस्टर में लगाएँ।</p></div><button type="button" data-asset-action="close" aria-label="बंद करें">✕</button></header><div class="apanam-assets-body"><div class="apanam-assets-tools"><label>＋ फोटो अपलोड<input type="file" id="apanamAssetUpload" accept="image/png,image/jpeg,image/webp" hidden></label><button type="button" data-asset-action="selected">चुनी हुई फोटो सेव करें</button><button type="button" data-asset-action="logo">Brand Logo सेव करें</button></div><p class="apanam-assets-note">हर फोटो अधिकतम 5 MB रखें। Assets इसी browser में रहेंगी; मूल फाइल अलग सुरक्षित रखें।</p><p class="apanam-assets-status" role="status"></p><div class="apanam-assets-list"></div></div></section>`;document.body.append(overlay);
  const list=overlay.querySelector('.apanam-assets-list'),status=overlay.querySelector('[role="status"]'),picker=overlay.querySelector('#apanamAssetUpload');
  function close(){overlay.hidden=true}
  function dataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})}
  async function saveAsset(src,name){if(typeof src!=='string'||!src.startsWith('data:image/')){status.textContent='केवल upload की हुई PNG, JPG या WebP फोटो सेव करें।';return}if(src.length>7000000){status.textContent='फोटो बहुत बड़ी है। 5 MB से छोटी फोटो चुनें।';return}const all=await query('getAll');if(all.some(item=>item.src===src)){status.textContent='यह फोटो Library में पहले से है।';return}await query('put',{id:Date.now(),name:String(name||'मेरी फोटो').slice(0,60),src},'readwrite');status.textContent='Asset Library में सेव हो गई।';await render()}
  function addToPoster(asset){const element=document.createElement('div');element.className='element';element.dataset.kind='image';element.style.cssText=`left:80px;top:80px;width:220px;height:180px;z-index:${Math.max(2,...[...stage.querySelectorAll('.element')].map(item=>Number(item.style.zIndex)||1))+1}`;element.innerHTML=`<img alt="" style="width:100%;height:100%;object-fit:contain">`;element.querySelector('img').src=asset.src;stage.append(element);window.APANAM_EDITOR_WIRE?.(element);element.click();window.APANAM_PROJECT?.save?.();close()}
  async function render(){const assets=(await query('getAll')).sort((a,b)=>b.id-a.id);list.replaceChildren();if(!assets.length){list.innerHTML='<div class="apanam-assets-empty">अभी कोई asset सेव नहीं है। ऊपर से Logo या Product photo जोड़ें।</div>';return}for(const asset of assets){const card=document.createElement('article');const image=document.createElement('img');image.src=asset.src;image.alt=asset.name;const name=document.createElement('strong');name.textContent=asset.name;const use=document.createElement('button');use.type='button';use.textContent='पोस्टर में लगाएँ';use.onclick=()=>addToPoster(asset);const rename=document.createElement('button');rename.type='button';rename.textContent='नाम';rename.onclick=async()=>{const value=prompt('Asset का नाम',asset.name);if(value===null||!value.trim())return;await query('put',{...asset,name:value.trim().slice(0,60)},'readwrite');render()};const remove=document.createElement('button');remove.type='button';remove.textContent='हटाएँ';remove.className='danger';remove.onclick=async()=>{if(!confirm('यह asset Library से हटाएँ?'))return;await query('delete',asset.id,'readwrite');render()};const actions=document.createElement('div');actions.append(use,rename,remove);card.append(image,name,actions);list.append(card)}}
  picker.onchange=async()=>{const file=picker.files?.[0];picker.value='';if(!file)return;if(file.size>5000000||!/^image\/(png|jpeg|webp)$/i.test(file.type)){status.textContent='5 MB से छोटी PNG, JPG या WebP फोटो चुनें।';return}try{await saveAsset(await dataUrl(file),file.name.replace(/\.[^.]+$/,''))}catch(_){status.textContent='फोटो पढ़ी नहीं जा सकी।'}};
  overlay.addEventListener('click',async event=>{if(event.target===overlay){close();return}const action=event.target.closest('[data-asset-action]')?.dataset.assetAction;if(action==='close')close();if(action==='selected'){const image=stage.querySelector('.element.selected img');if(!image){status.textContent='पहले पोस्टर में किसी फोटो को select करें।';return}await saveAsset(image.src,'चुनी हुई फोटो')}if(action==='logo'){const logo=localStorage.getItem('apanam_brand_logo_v1');if(!logo){status.textContent='पहले Brand Kit में Logo upload और save करें।';return}await saveAsset(logo,'Brand Logo')}});
  async function open(){overlay.hidden=false;status.textContent='';try{await render()}catch(_){status.textContent='इस browser में Assets Library उपलब्ध नहीं है।'}}
  document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!overlay.hidden)close()});window.APANAM_ASSET_LIBRARY={open};
})();
