(()=>{
  const $=id=>document.getElementById(id),canvas=$('screen'),outputCtx=canvas.getContext('2d'),drawingCanvas=document.createElement('canvas');drawingCanvas.width=1280;drawingCanvas.height=720;const ctx=drawingCanvas.getContext('2d');
  const fields=['title','caption','duration','background','photoFit','character','characterType','motion','transition','titleColor','captionColor','titleSize','captionSize','captionPosition'];
  const defaults={title:'पहला Scene',caption:'APANAM में आपका स्वागत है',duration:4,background:'#312e81',photoFit:'cover',character:'#facc15',characterType:'smile',motion:'bounce',transition:'fade',titleColor:'#ffffff',captionColor:'#ffffff',titleSize:56,captionSize:32,captionPosition:'lower'};
  let scenes=[],current=-1,playing=false,recorder=null,raf=0,audioFile=null,sceneAudioFiles=[],audioContext=null,audioSource=null,sceneAudioSources=[],voiceRecorder=null,voiceStream=null,previewAudio=null,previewAudioUrl=null,videoPreviewAudio=null,videoPreviewUrl=null,videoPreviewSceneAudio=null,videoPreviewSceneUrl=null;
  const images=new Map();
  function backgroundImage(src){if(!src)return null;if(images.has(src))return images.get(src);const image=new Image();image.onload=()=>{if(!playing&&(scene()?.backgroundImage===src||scene()?.logoImage===src||scene()?.layers?.some(layer=>layer.src===src)))draw(scene(),0)};image.src=src;images.set(src,image);return image}
  try{const saved=JSON.parse(localStorage.getItem('apanam-cartoon-scenes')||'[]');if(Array.isArray(saved))scenes=saved.slice(0,100).map(s=>({...defaults,...s}))}catch{}
  if(!scenes.length)scenes=[{...defaults}];
  sceneAudioFiles=scenes.map(()=>null);
  let notificationPending=false;
  function notifySceneChange(){if(notificationPending)return;notificationPending=true;queueMicrotask(()=>{notificationPending=false;document.dispatchEvent(new CustomEvent('apanam-scene-change'))})}
  function save(){notifySceneChange();try{localStorage.setItem('apanam-cartoon-scenes',JSON.stringify(scenes));updateTimeline();return true}catch{$('status').textContent='ब्राउज़र की जगह भर गई है। वीडियो का JSON बैकअप डाउनलोड करें।';return false}}
  function scene(){return scenes[current]}
  function select(i){current=i;notifySceneChange();fields.forEach(k=>$(k).value=scene()[k]);list();draw(scene(),0);$('sceneAudioStatus').textContent=sceneAudioFiles[i]?`इस सीन की आवाज़: ${sceneAudioFiles[i].name}`:'इस सीन की अलग आवाज़ नहीं है।'}
  function list(){const root=$('scenes');root.replaceChildren();scenes.forEach((s,i)=>{const row=document.createElement('div');row.className='scene-row';row.setAttribute('role','listitem');const b=document.createElement('button');b.type='button';b.className=i===current?'selected':'';b.textContent=`${i+1}. ${s.title||'Scene'} · ${s.duration}s${sceneAudioFiles[i]?' 🔊':''}`;b.onclick=()=>select(i);row.append(b);for(const [step,label] of [[-1,'↑'],[1,'↓']]){const move=document.createElement('button');move.type='button';move.textContent=label;move.title=step<0?'Scene ऊपर ले जाएँ':'Scene नीचे ले जाएँ';move.setAttribute('aria-label',`${s.title||'Scene'} ${move.title}`);move.disabled=i+step<0||i+step>=scenes.length;move.onclick=()=>{[scenes[i],scenes[i+step]]=[scenes[i+step],scenes[i]];[sceneAudioFiles[i],sceneAudioFiles[i+step]]=[sceneAudioFiles[i+step],sceneAudioFiles[i]];save();select(i+step)};row.append(move)}root.append(row)})}
  function wrapText(value,x,y,width,limit=3){ctx.textAlign='center';const words=String(value||'').trim().split(/\s+/).filter(Boolean),lines=[];let line='';const fit=text=>{if(ctx.measureText(text).width<=width)return text;const chars=Intl.Segmenter?Array.from(new Intl.Segmenter(undefined,{granularity:'grapheme'}).segment(text),part=>part.segment):Array.from(text);let low=0,high=chars.length;while(low<high){const mid=Math.ceil((low+high)/2);if(ctx.measureText(chars.slice(0,mid).join('')+'…').width<=width)low=mid;else high=mid-1}return chars.slice(0,low).join('')+'…'};for(let i=0;i<words.length;i++){const next=line?`${line} ${words[i]}`:words[i];if(ctx.measureText(next).width<=width){line=next;continue}if(line&&lines.length<limit-1){lines.push(line);line=words[i];continue}line=fit([line,...words.slice(i)].filter(Boolean).join(' '));break}if(line)lines.push(fit(line));lines.forEach((text,i)=>ctx.fillText(text,x,y+i*52))}
  function drawLayers(s){for(const layer of Array.isArray(s.layers)?s.layers.slice(0,12):[]){ctx.save();ctx.globalAlpha=Math.min(1,Math.max(.1,Number(layer.opacity)||1));const x=Math.min(1180,Math.max(100,Number(layer.x)||640)),y=Math.min(650,Math.max(70,Number(layer.y)||360));if(layer.kind==='image'&&typeof layer.src==='string'){const image=backgroundImage(layer.src);if(image?.complete&&image.naturalWidth){const maxW=Math.min(600,Math.max(60,Number(layer.width)||240)),maxH=Math.min(420,Math.max(60,Number(layer.height)||180)),scale=Math.min(maxW/image.naturalWidth,maxH/image.naturalHeight);ctx.drawImage(image,x-image.naturalWidth*scale/2,y-image.naturalHeight*scale/2,image.naturalWidth*scale,image.naturalHeight*scale)}}else if(layer.kind==='text'){ctx.fillStyle=/^#[0-9a-f]{6}$/i.test(layer.color)?layer.color:'#ffffff';ctx.font=`bold ${Math.min(96,Math.max(18,Number(layer.size)||40))}px Arial,sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.strokeStyle='#0009';ctx.lineWidth=6;ctx.lineJoin='round';ctx.strokeText(String(layer.text||'').slice(0,100),x,y,700);ctx.fillText(String(layer.text||'').slice(0,100),x,y,700)}ctx.restore()}}
  const formats={landscape:[1280,720],square:[1080,1080],portrait:[720,1280]};
  function present(s){const W=canvas.width,H=canvas.height,scale=Math.min(W/1280,H/720),w=1280*scale,h=720*scale;outputCtx.clearRect(0,0,W,H);outputCtx.fillStyle=s.background||'#18213a';outputCtx.fillRect(0,0,W,H);if(w<W||h<H){outputCtx.save();outputCtx.globalAlpha=.25;outputCtx.filter='blur(24px)';const fill=Math.max(W/1280,H/720);outputCtx.drawImage(drawingCanvas,(W-1280*fill)/2,(H-720*fill)/2,1280*fill,720*fill);outputCtx.restore()}outputCtx.drawImage(drawingCanvas,(W-w)/2,(H-h)/2,w,h)}
  function setFormat(value){const format=formats[value]?value:'landscape';$('videoFormat').value=format;const [w,h]=formats[format];canvas.width=w;canvas.height=h;canvas.style.aspectRatio=`${w} / ${h}`;canvas.style.width=format==='portrait'?'min(100%,420px)':format==='square'?'min(100%,760px)':'min(100%,1100px)';$('videoFormatLabel').textContent=`${w} × ${h}`;if(scene())draw(scene(),0)}
  function draw(s,t){ctx.fillStyle=s.background;ctx.fillRect(0,0,1280,720);const photo=backgroundImage(s.backgroundImage);if(s.posterOnly){if(photo?.complete&&photo.naturalWidth){const scale=Math.min(drawingCanvas.width/photo.naturalWidth,drawingCanvas.height/photo.naturalHeight),w=photo.naturalWidth*scale,h=photo.naturalHeight*scale;ctx.drawImage(photo,(drawingCanvas.width-w)/2,(drawingCanvas.height-h)/2,w,h)}present(s);return}if(photo?.complete&&photo.naturalWidth){const scale=(s.photoFit==='contain'?Math.min:Math.max)(drawingCanvas.width/photo.naturalWidth,drawingCanvas.height/photo.naturalHeight),w=photo.naturalWidth*scale,h=photo.naturalHeight*scale;ctx.drawImage(photo,(drawingCanvas.width-w)/2,(drawingCanvas.height-h)/2,w,h);ctx.fillStyle='#0005';ctx.fillRect(0,0,drawingCanvas.width,drawingCanvas.height)}ctx.fillStyle='#ffffff22';ctx.fillRect(0,590,1280,130);
    const x=s.motion==='slide'?190+Math.min(1,t/Math.max(1,s.duration))*850:640;
    const y=s.motion==='bounce'?370-Math.abs(Math.sin(t*4))*85:370;
    ctx.fillStyle=s.character;
    if(s.characterType==='person'){ctx.beginPath();ctx.arc(x,y-45,72,0,Math.PI*2);ctx.fill();ctx.fillRect(x-78,y+42,156,115);ctx.lineWidth=24;ctx.lineCap='round';ctx.strokeStyle=s.character;ctx.beginPath();ctx.moveTo(x-68,y+65);ctx.lineTo(x-135,y+130);ctx.moveTo(x+68,y+65);ctx.lineTo(x+135,y+130);ctx.stroke()}
    else{if(s.characterType==='cat'){ctx.beginPath();ctx.moveTo(x-90,y-45);ctx.lineTo(x-102,y-145);ctx.lineTo(x-30,y-98);ctx.moveTo(x+90,y-45);ctx.lineTo(x+102,y-145);ctx.lineTo(x+30,y-98);ctx.fill()}ctx.beginPath();ctx.arc(x,y,110,0,Math.PI*2);ctx.fill()}
    ctx.fillStyle='#172033';ctx.beginPath();ctx.arc(x-36,y-25,10,0,7);ctx.arc(x+36,y-25,10,0,7);ctx.fill();ctx.beginPath();ctx.arc(x,y+12,42,.1,Math.PI-.1);ctx.lineWidth=7;ctx.strokeStyle='#172033';ctx.stroke();
    ctx.fillStyle=s.titleColor||'#fff';ctx.font=`bold ${Math.min(88,Math.max(24,Number(s.titleSize)||56))}px Arial,sans-serif`;wrapText(s.title,640,100,1120,2);
    ctx.fillStyle=s.captionColor||'#fff';ctx.font=`${Math.min(64,Math.max(18,Number(s.captionSize)||32))}px Arial,sans-serif`;wrapText(s.caption,640,s.captionPosition==='top'?240:s.captionPosition==='bottom'?630:550,1080,2);
    drawLayers(s);const logo=backgroundImage(s.logoImage);if(logo?.complete&&logo.naturalWidth){const scale=Math.min(140/logo.naturalWidth,100/logo.naturalHeight,1),width=logo.naturalWidth*scale,height=logo.naturalHeight*scale;ctx.drawImage(logo,drawingCanvas.width-width-34,28,width,height)}
    present(s)
  }
  function total(){return scenes.reduce((n,s)=>n+Number(s.duration||1),0)}
  function updateTimeline(position=0){const slider=$('videoTimeline');if(!slider)return;slider.max=String(total());slider.value=String(Math.min(total(),Math.max(0,position)));$('videoTime').textContent=`${Number(slider.value).toFixed(1)} / ${total().toFixed(1)} सेकंड`}
  function frameAt(elapsed){let t=elapsed;for(const [index,s] of scenes.entries()){let d=Number(s.duration)||1;if(t<d)return {s,t,index};t-=d}return {s:scenes.at(-1),t:Number(scenes.at(-1).duration)||1,index:scenes.length-1}}
  function stopVideoPreviewAudio(){videoPreviewAudio?.pause();videoPreviewAudio=null;if(videoPreviewUrl)URL.revokeObjectURL(videoPreviewUrl);videoPreviewUrl=null}
  function stopScenePreviewAudio(){videoPreviewSceneAudio?.pause();videoPreviewSceneAudio=null;if(videoPreviewSceneUrl)URL.revokeObjectURL(videoPreviewSceneUrl);videoPreviewSceneUrl=null}
  function startScenePreviewAudio(index){stopScenePreviewAudio();const file=sceneAudioFiles[index];if(!file)return;videoPreviewSceneUrl=URL.createObjectURL(file);videoPreviewSceneAudio=new Audio(videoPreviewSceneUrl);videoPreviewSceneAudio.volume=Number($('audioVolume').value)/100;videoPreviewSceneAudio.play().catch(()=>{$('sceneAudioStatus').textContent='इस सीन की आवाज़ नहीं चली। फ़ाइल जाँचें।'})}
  function stop(){playing=false;cancelAnimationFrame(raf);stopVideoPreviewAudio();stopScenePreviewAudio();if(recorder?.state==='recording')recorder.stop();recorder=null;$('status').textContent='रुका हुआ'}
  function play(exporting=false){if(playing)stop();stopAudioPreview();stopVideoPreviewAudio();stopScenePreviewAudio();const length=total();if(!length)return;playing=true;const start=performance.now();let lastScene=-1;$('status').textContent=exporting?'Video बन रहा है…':'Preview चल रहा है…';if(!exporting&&audioFile){videoPreviewUrl=URL.createObjectURL(audioFile);videoPreviewAudio=new Audio(videoPreviewUrl);videoPreviewAudio.volume=Number($('audioVolume').value)/100;videoPreviewAudio.loop=$('loopAudio').checked;videoPreviewAudio.play().catch(()=>{$('audioStatus').textContent='प्रीव्यू की आवाज़ नहीं चली। ऑडियो फ़ाइल जाँचें।'})}
    function tick(now){if(!playing)return;const elapsed=(now-start)/1000;const {s,t,index}=frameAt(Math.min(elapsed,length-.001));if(index!==lastScene){lastScene=index;if(!exporting)startScenePreviewAudio(index)}draw(s,t);updateTimeline(elapsed);if(index>0&&t<.55&&s.transition!=='cut'){const progress=Math.min(1,t/.55);if(s.transition==='wipe'){ctx.fillStyle='#111827';ctx.fillRect(1280*progress,0,1280*(1-progress),720)}else{const color=s.transition==='flash'?'255,255,255':'13,14,31',alpha=(1-progress)*(s.transition==='dark'?1:.82);ctx.fillStyle=`rgba(${color},${alpha.toFixed(3)})`;ctx.fillRect(0,0,1280,720)}present(s)}if(elapsed<length)raf=requestAnimationFrame(tick);else{playing=false;stopVideoPreviewAudio();stopScenePreviewAudio();if(recorder?.state==='recording')recorder.stop();else if(exporting){if(!$('videoDownloadLink'))$('status').textContent='वीडियो सहेज रहे हैं…'}else $('status').textContent='Preview पूरा हुआ'}}raf=requestAnimationFrame(tick)
  }
  fields.forEach(k=>$(k).addEventListener('input',()=>{if(!scene())return;scene()[k]=k==='duration'?Math.min(15,Math.max(1,Number($(k).value)||1)):['titleSize','captionSize'].includes(k)?Math.min(88,Math.max(18,Number($(k).value)||32)):$(k).value;save();list();if(!playing)draw(scene(),0)}));
  $('add').onclick=()=>{if(scenes.length>=100){$('status').textContent='एक प्रोजेक्ट में अधिकतम 100 सीन रखें।';return}scenes.push({...defaults,title:`Scene ${scenes.length+1}`,...(scenes[0]?.logoImage?{logoImage:scenes[0].logoImage}:{})});sceneAudioFiles.push(null);save();select(scenes.length-1)};
  $('duplicateScene').onclick=()=>{if(scenes.length>=100){$('status').textContent='एक प्रोजेक्ट में अधिकतम 100 सीन रखें।';return}const copy={...scene(),layers:Array.isArray(scene().layers)?scene().layers.map(layer=>({...layer})):[],title:`${scene().title||'Scene'} कॉपी`};scenes.splice(current+1,0,copy);sceneAudioFiles.splice(current+1,0,sceneAudioFiles[current]||null);if(!save()){scenes.splice(current+1,1);sceneAudioFiles.splice(current+1,1);return}select(current+1);$('status').textContent='सीन और उसकी आवाज़ कॉपी हो गए।'};
  $('remove').onclick=()=>{if(scenes.length===1){$('status').textContent='कम से कम एक scene रखें';return}scenes.splice(current,1);sceneAudioFiles.splice(current,1);save();select(Math.min(current,scenes.length-1))};
  $('scenePng').onclick=()=>{if(playing){$('status').textContent='पहले वीडियो प्रीव्यू रोकें।';return}draw(scene(),0);const link=document.createElement('a');link.download=`${window.APANAM_VIDEO_EXPORT_BASENAME?.()||'APANAM-cartoon-video'}-scene-${current+1}.png`;link.href=canvas.toDataURL('image/png');link.click();$('status').textContent='इस सीन की PNG डाउनलोड हुई।'};
  $('preview').onclick=()=>play();$('stop').onclick=()=>{stop();window.speechSynthesis?.cancel()};
  $('videoTimeline').oninput=event=>{if(playing)stop();const time=Math.min(total()-.001,Number(event.target.value)||0),{s,t,index}=frameAt(Math.max(0,time));draw(s,t);updateTimeline(time);$('status').textContent=`सीन ${index+1} की झलक`};
  $('speak').onclick=()=>{if(!window.speechSynthesis){$('status').textContent='इस browser में voice preview उपलब्ध नहीं है';return}speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(scene().caption||scene().title);utterance.lang=/[\u0900-\u097f]/.test(utterance.text)?'hi-IN':/[\u0980-\u09ff]/.test(utterance.text)?'bn-IN':'en-IN';speechSynthesis.speak(utterance);$('status').textContent='Dialogue सुनाया जा रहा है'};
  function stopAudioPreview(){previewAudio?.pause();previewAudio=null;if(previewAudioUrl)URL.revokeObjectURL(previewAudioUrl);previewAudioUrl=null;$('listenAudio').textContent='▶ ऑडियो सुनें'}
  $('audioFile').onchange=event=>{stopAudioPreview();stopVideoPreviewAudio();audioFile=event.target.files?.[0]||null;$('audioStatus').textContent=audioFile?`चुना गया ऑडियो: ${audioFile.name}`:'ऑडियो फ़ाइल चुनने पर वह डाउनलोड किए गए WebM में जुड़ेगी।'};
  $('listenAudio').onclick=async()=>{if(previewAudio){stopAudioPreview();return}if(!audioFile){$('audioStatus').textContent='पहले ऑडियो फ़ाइल चुनें या आवाज़ रिकॉर्ड करें।';return}previewAudioUrl=URL.createObjectURL(audioFile);previewAudio=new Audio(previewAudioUrl);previewAudio.volume=Number($('audioVolume').value)/100;previewAudio.onended=stopAudioPreview;try{await previewAudio.play();$('listenAudio').textContent='■ ऑडियो रोकें'}catch(_){stopAudioPreview();$('audioStatus').textContent='ऑडियो नहीं चला। दूसरी फ़ाइल चुनें।'}};
  $('videoFormat').onchange=()=>{if(playing)stop();setFormat($('videoFormat').value)};
  $('audioVolume').oninput=()=>{const volume=Number($('audioVolume').value);$('audioVolumeValue').textContent=`${volume}%`;if(previewAudio)previewAudio.volume=volume/100;if(videoPreviewAudio)videoPreviewAudio.volume=volume/100;if(videoPreviewSceneAudio)videoPreviewSceneAudio.volume=volume/100};
  $('sceneAudioFile').onchange=event=>{const file=event.target.files?.[0];if(!file)return;if(file.size>10000000){$('sceneAudioStatus').textContent='सीन की ऑडियो 10 MB से छोटी रखें।';event.target.value='';return}sceneAudioFiles[current]=file;select(current);$('status').textContent='इस सीन की आवाज़ जुड़ गई।';event.target.value=''};
  $('removeSceneAudio').onclick=()=>{sceneAudioFiles[current]=null;stopScenePreviewAudio();select(current);$('status').textContent='इस सीन की आवाज़ हट गई।'};
  $('scenePhoto').onchange=async event=>{const file=event.target.files?.[0];if(!file)return;try{if(file.size>12000000)throw Error('large');const url=URL.createObjectURL(file),image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=url});URL.revokeObjectURL(url);const scale=Math.min(1,960/Math.max(image.width,image.height)),small=document.createEle…5375 tokens truncated…093eइल नहीं खुली या ब्राउज़र इसे रिकॉर्ड नहीं कर सका। दूसरी MP3/WAV फ़ाइल चुनें।'}
  };
  window.APANAM_CARTOON_PROJECT={snapshot:()=>scenes.map(s=>({...s})),currentScene:()=>scene(),refreshScene(){save();list();draw(scene(),0);document.dispatchEvent(new CustomEvent("apanam-scene-change"))},applySubtitles(entries){if(!Array.isArray(entries))return 0;const count=Math.min(entries.length,scenes.length);for(let i=0;i<count;i++){scenes[i].caption=String(entries[i].caption||"").slice(0,220);scenes[i].duration=Math.min(15,Math.max(1,Number(entries[i].duration)||scenes[i].duration||4))}save();select(Math.min(current,count-1));return count},snapshotAudio:()=>audioFile,snapshotSceneAudio:()=>sceneAudioFiles.slice(),restoreSceneAudio(files){sceneAudioFiles=scenes.map((_,i)=>files?.[i] instanceof Blob?files[i]:null);select(current)},snapshotSettings:()=>({volume:Number($('audioVolume').value),loop:$('loopAudio').checked,format:$('videoFormat').value,audioStart:Number($('audioStart')?.value)||0,fadeAudio:$('fadeAudio')?.checked!==false,fadeTime:Number($('audioFadeTime')?.value)||.8}),restoreSettings(settings){const value=Number(settings?.volume);$('audioVolume').value=Number.isFinite(value)?Math.min(100,Math.max(0,value)):100;$('audioVolumeValue').textContent=`${$('audioVolume').value}%`;$('loopAudio').checked=Boolean(settings?.loop);setFormat(settings?.format);if($('audioStart'))$('audioStart').value=Math.max(0,Number(settings?.audioStart)||0);if($('fadeAudio'))$('fadeAudio').checked=settings?.fadeAudio!==false;if($('audioFadeTime'))$('audioFadeTime').value=Math.min(3,Math.max(.2,Number(settings?.fadeTime)||.8))},restoreAudio(file){stopAudioPreview();stopVideoPreviewAudio();audioFile=file instanceof Blob?file:null;$('audioFile').value='';$('audioStatus').textContent=audioFile?`प्रोजेक्ट की सेव की हुई आवाज़: ${audioFile.name||'ऑडियो'}`:'इस प्रोजेक्ट में ऑडियो नहीं है। फ़ाइल चुनें या आवाज़ रिकॉर्ड करें।'},restore(incoming){if(!Array.isArray(incoming)||!incoming.length||incoming.length>100||incoming.some(s=>!s||typeof s.title!=='string'||typeof s.caption!=='string'||!Number.isFinite(Number(s.duration))))return false;if(playing)stop();const previous=scenes,previousClips=sceneAudioFiles;scenes=incoming.map(s=>({...defaults,...s,duration:Math.min(15,Math.max(1,Number(s.duration)||1))}));sceneAudioFiles=scenes.map(()=>null);if(!save()){scenes=previous;sceneAudioFiles=previousClips;return false}select(0);return true},append(incoming,clips){if(!Array.isArray(incoming)||!incoming.length||scenes.length+incoming.length>100||incoming.some(s=>!s||typeof s.title!=='string'||typeof s.caption!=='string'||!Number.isFinite(Number(s.duration))))return false;if(playing)stop();const from=scenes.length;sceneAudioFiles.push(...incoming.map((_,i)=>clips?.[i] instanceof Blob?clips[i]:null));scenes.push(...incoming.map(s=>({...defaults,...s,duration:Math.min(15,Math.max(1,Number(s.duration)||1))})));if(!save()){scenes.length=from;sceneAudioFiles.length=from;return false}select(from);return true}};
  setFormat('landscape');select(0);updateTimeline();$('status').textContent='सीन तैयार हैं। Preview देखें या नया सीन जोड़ें।';
  try{const incoming=sessionStorage.getItem('apanam-poster-to-video');if(incoming?.startsWith('data:image/jpeg;base64,')&&incoming.length<3000000&&scenes.length<100){const poster={...defaults,title:'पोस्टर सीन',caption:'',motion:'still',background:'#18213a',backgroundImage:incoming,posterOnly:true};scenes.push(poster);sceneAudioFiles.push(null);if(save()){sessionStorage.removeItem('apanam-poster-to-video');select(scenes.length-1);$('status').textContent='पोस्टर नया वीडियो सीन बन गया। अवधि बदलें और Preview देखें।'}else{scenes.pop();sceneAudioFiles.pop()}}}catch(_){$('status').textContent='पोस्टर सीन नहीं खुला। फिर से पोस्टर एडिटर से भेजें।'}
})();