(()=>{
  const $=id=>document.getElementById(id),canvas=$('screen'),ctx=canvas.getContext('2d');
  const fields=['title','caption','duration','background','character','characterType','motion','transition','titleColor','captionColor','titleSize','captionSize'];
  const defaults={title:'पहला Scene',caption:'APANAM में आपका स्वागत है',duration:4,background:'#312e81',character:'#facc15',characterType:'smile',motion:'bounce',transition:'fade',titleColor:'#ffffff',captionColor:'#ffffff',titleSize:56,captionSize:32};
  let scenes=[],current=-1,playing=false,recorder=null,raf=0,audioFile=null,audioContext=null,audioSource=null,voiceRecorder=null,voiceStream=null;
  const images=new Map();
  function backgroundImage(src){if(!src)return null;if(images.has(src))return images.get(src);const image=new Image();image.onload=()=>{if(!playing&&scene()?.backgroundImage===src)draw(scene(),0)};image.src=src;images.set(src,image);return image}
  try{const saved=JSON.parse(localStorage.getItem('apanam-cartoon-scenes')||'[]');if(Array.isArray(saved))scenes=saved.slice(0,100).map(s=>({...defaults,...s}))}catch{}
  if(!scenes.length)scenes=[{...defaults}];
  function save(){try{localStorage.setItem('apanam-cartoon-scenes',JSON.stringify(scenes));updateTimeline();return true}catch{$('status').textContent='ब्राउज़र की जगह भर गई है। वीडियो का JSON बैकअप डाउनलोड करें।';return false}}
  function scene(){return scenes[current]}
  function select(i){current=i;fields.forEach(k=>$(k).value=scene()[k]);list();draw(scene(),0)}
  function list(){const root=$('scenes');root.replaceChildren();scenes.forEach((s,i)=>{const row=document.createElement('div');row.className='scene-row';row.setAttribute('role','listitem');const b=document.createElement('button');b.type='button';b.className=i===current?'selected':'';b.textContent=`${i+1}. ${s.title||'Scene'} · ${s.duration}s`;b.onclick=()=>select(i);row.append(b);for(const [step,label] of [[-1,'↑'],[1,'↓']]){const move=document.createElement('button');move.type='button';move.textContent=label;move.title=step<0?'Scene ऊपर ले जाएँ':'Scene नीचे ले जाएँ';move.setAttribute('aria-label',`${s.title||'Scene'} ${move.title}`);move.disabled=i+step<0||i+step>=scenes.length;move.onclick=()=>{[scenes[i],scenes[i+step]]=[scenes[i+step],scenes[i]];save();select(i+step)};row.append(move)}root.append(row)})}
  function wrapText(value,x,y,width,limit=3){ctx.textAlign='center';const words=String(value||'').split(/\s+/),lines=[''];for(const word of words){let n=lines.at(-1)+(lines.at(-1)?' ':'')+word;if(ctx.measureText(n).width>width&&lines.at(-1)&&lines.length<limit)lines.push(word);else lines[lines.length-1]=n}lines.forEach((line,i)=>ctx.fillText(line,x,y+i*52))}
  function draw(s,t){ctx.fillStyle=s.background;ctx.fillRect(0,0,1280,720);const photo=backgroundImage(s.backgroundImage);if(photo?.complete&&photo.naturalWidth){const scale=Math.max(canvas.width/photo.naturalWidth,canvas.height/photo.naturalHeight),w=photo.naturalWidth*scale,h=photo.naturalHeight*scale;ctx.drawImage(photo,(canvas.width-w)/2,(canvas.height-h)/2,w,h);ctx.fillStyle='#0005';ctx.fillRect(0,0,canvas.width,canvas.height)}ctx.fillStyle='#ffffff22';ctx.fillRect(0,590,1280,130);
    const x=s.motion==='slide'?190+Math.min(1,t/Math.max(1,s.duration))*850:640;
    const y=s.motion==='bounce'?370-Math.abs(Math.sin(t*4))*85:370;
    ctx.fillStyle=s.character;
    if(s.characterType==='person'){ctx.beginPath();ctx.arc(x,y-45,72,0,Math.PI*2);ctx.fill();ctx.fillRect(x-78,y+42,156,115);ctx.lineWidth=24;ctx.lineCap='round';ctx.strokeStyle=s.character;ctx.beginPath();ctx.moveTo(x-68,y+65);ctx.lineTo(x-135,y+130);ctx.moveTo(x+68,y+65);ctx.lineTo(x+135,y+130);ctx.stroke()}
    else{if(s.characterType==='cat'){ctx.beginPath();ctx.moveTo(x-90,y-45);ctx.lineTo(x-102,y-145);ctx.lineTo(x-30,y-98);ctx.moveTo(x+90,y-45);ctx.lineTo(x+102,y-145);ctx.lineTo(x+30,y-98);ctx.fill()}ctx.beginPath();ctx.arc(x,y,110,0,Math.PI*2);ctx.fill()}
    ctx.fillStyle='#172033';ctx.beginPath();ctx.arc(x-36,y-25,10,0,7);ctx.arc(x+36,y-25,10,0,7);ctx.fill();ctx.beginPath();ctx.arc(x,y+12,42,.1,Math.PI-.1);ctx.lineWidth=7;ctx.strokeStyle='#172033';ctx.stroke();
    ctx.fillStyle=s.titleColor||'#fff';ctx.font=`bold ${Math.min(88,Math.max(24,Number(s.titleSize)||56))}px Arial,sans-serif`;wrapText(s.title,640,100,1120,2);
    ctx.fillStyle=s.captionColor||'#fff';ctx.font=`${Math.min(64,Math.max(18,Number(s.captionSize)||32))}px Arial,sans-serif`;wrapText(s.caption,640,550,1080,2)
  }
  function total(){return scenes.reduce((n,s)=>n+Number(s.duration||1),0)}
  function updateTimeline(position=0){const slider=$('videoTimeline');if(!slider)return;slider.max=String(total());slider.value=String(Math.min(total(),Math.max(0,position)));$('videoTime').textContent=`${Number(slider.value).toFixed(1)} / ${total().toFixed(1)} सेकंड`}
  function frameAt(elapsed){let t=elapsed;for(const [index,s] of scenes.entries()){let d=Number(s.duration)||1;if(t<d)return {s,t,index};t-=d}return {s:scenes.at(-1),t:Number(scenes.at(-1).duration)||1,index:scenes.length-1}}
  function stop(){playing=false;cancelAnimationFrame(raf);if(recorder?.state==='recording')recorder.stop();recorder=null;$('status').textContent='रुका हुआ'}
  function play(exporting=false){if(playing)stop();const length=total();if(!length)return;playing=true;const start=performance.now();$('status').textContent=exporting?'Video बन रहा है…':'Preview चल रहा है…';
    function tick(now){if(!playing)return;const elapsed=(now-start)/1000;const {s,t,index}=frameAt(Math.min(elapsed,length-.001));draw(s,t);updateTimeline(elapsed);if(index>0&&s.transition==='fade'&&t<.45){ctx.fillStyle=`rgba(13,14,31,${(1-t/.45).toFixed(3)})`;ctx.fillRect(0,0,canvas.width,canvas.height)}if(elapsed<length)raf=requestAnimationFrame(tick);else{playing=false;if(recorder?.state==='recording')recorder.stop();else $('status').textContent='Preview पूरा हुआ'}}raf=requestAnimationFrame(tick)
  }
  fields.forEach(k=>$(k).addEventListener('input',()=>{if(!scene())return;scene()[k]=k==='duration'?Math.min(15,Math.max(1,Number($(k).value)||1)):['titleSize','captionSize'].includes(k)?Math.min(88,Math.max(18,Number($(k).value)||32)):$(k).value;save();list();if(!playing)draw(scene(),0)}));
  $('add').onclick=()=>{scenes.push({...defaults,title:`Scene ${scenes.length+1}`});save();select(scenes.length-1)};
  $('duplicateScene').onclick=()=>{if(scenes.length>=100){$('status').textContent='एक प्रोजेक्ट में अधिकतम 100 सीन रखें।';return}const copy={...scene(),title:`${scene().title||'Scene'} कॉपी`};scenes.splice(current+1,0,copy);if(!save()){scenes.splice(current+1,1);return}select(current+1);$('status').textContent='सीन कॉपी हो गया।'};
  $('remove').onclick=()=>{if(scenes.length===1){$('status').textContent='कम से कम एक scene रखें';return}scenes.splice(current,1);save();select(Math.min(current,scenes.length-1))};
  $('scenePng').onclick=()=>{if(playing){$('status').textContent='पहले वीडियो प्रीव्यू रोकें।';return}draw(scene(),0);const link=document.createElement('a');link.download='APANAM-cartoon-scene.png';link.href=canvas.toDataURL('image/png');link.click();$('status').textContent='इस सीन की PNG डाउनलोड हुई।'};
  $('preview').onclick=()=>play();$('stop').onclick=()=>{stop();window.speechSynthesis?.cancel()};
  $('videoTimeline').oninput=event=>{if(playing)stop();const time=Math.min(total()-.001,Number(event.target.value)||0),{s,t,index}=frameAt(Math.max(0,time));draw(s,t);updateTimeline(time);$('status').textContent=`सीन ${index+1} की झलक`};
  $('speak').onclick=()=>{if(!window.speechSynthesis){$('status').textContent='इस browser में voice preview उपलब्ध नहीं है';return}speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(scene().caption||scene().title);utterance.lang=/[\u0900-\u097f]/.test(utterance.text)?'hi-IN':/[\u0980-\u09ff]/.test(utterance.text)?'bn-IN':'en-IN';speechSynthesis.speak(utterance);$('status').textContent='Dialogue सुनाया जा रहा है'};
  $('audioFile').onchange=event=>{audioFile=event.target.files?.[0]||null;$('audioStatus').textContent=audioFile?`चुना गया ऑडियो: ${audioFile.name}`:'ऑडियो फ़ाइल चुनने पर वह डाउनलोड किए गए WebM में जुड़ेगी।'};
  $('scenePhoto').onchange=async event=>{const file=event.target.files?.[0];if(!file)return;try{if(file.size>12000000)throw Error('large');const url=URL.createObjectURL(file),image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=url});URL.revokeObjectURL(url);const scale=Math.min(1,960/Math.max(image.width,image.height)),small=document.createElement('canvas');small.width=Math.max(1,Math.round(image.width*scale));small.height=Math.max(1,Math.round(image.height*scale));small.getContext('2d').drawImage(image,0,0,small.width,small.height);const previous=scene().backgroundImage;scene().backgroundImage=small.toDataURL('image/jpeg',.68);backgroundImage(scene().backgroundImage);if(!save()){scene().backgroundImage=previous;return}draw(scene(),0);$('status').textContent='इस सीन का फ़ोटो बैकग्राउंड लग गया।'}catch(_){$('status').textContent='फ़ोटो नहीं खुली। 12 MB से छोटी JPG/PNG चुनें।'}finally{event.target.value=''}};
  $('removeScenePhoto').onclick=()=>{delete scene().backgroundImage;save();draw(scene(),0);$('status').textContent='सीन का फ़ोटो बैकग्राउंड हट गया।'};
  $('recordVoice').onclick=async()=>{if(voiceRecorder?.state==='recording')return;if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){$('audioStatus').textContent='इस browser में माइक्रोफ़ोन रिकॉर्डिंग उपलब्ध नहीं है।';return}try{voiceStream=await navigator.mediaDevices.getUserMedia({audio:true});const chunks=[];voiceRecorder=new MediaRecorder(voiceStream);voiceRecorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};voiceRecorder.onstop=()=>{voiceStream?.getTracks().forEach(track=>track.stop());voiceStream=null;$('recordVoice').disabled=false;$('stopVoice').disabled=true;if(!chunks.length){$('audioStatus').textContent='आवाज़ रिकॉर्ड नहीं हुई। दोबारा कोशिश करें।';return}audioFile=new File([new Blob(chunks,{type:voiceRecorder.mimeType||'audio/webm'})],'APANAM-recorded-voice.webm',{type:voiceRecorder.mimeType||'audio/webm'});$('audioFile').value='';$('audioStatus').textContent=`रिकॉर्ड की हुई आवाज़ तैयार है (${Math.round(audioFile.size/1024)} KB)। WebM डाउनलोड में जुड़ेगी।`};voiceRecorder.start();$('recordVoice').disabled=true;$('stopVoice').disabled=false;$('audioStatus').textContent='रिकॉर्डिंग चालू है। बोलें, फिर रोकें दबाएँ।'}catch(_){voiceStream?.getTracks().forEach(track=>track.stop());voiceStream=null;$('audioStatus').textContent='माइक्रोफ़ोन नहीं खुला। ब्राउज़र में अनुमति दें या ऑडियो फ़ाइल चुनें।'}};
  $('stopVoice').onclick=()=>{if(voiceRecorder?.state==='recording')voiceRecorder.stop()};
  $('backupVideo').onclick=()=>{const blob=new Blob([JSON.stringify({format:'apanam-cartoon-project',version:1,scenes},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='APANAM-cartoon-project.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),60000);$('status').textContent='सीन का प्रोजेक्ट बैकअप डाउनलोड हुआ। ऑडियो फ़ाइल अलग रखें।'};
  $('downloadSubtitles').onclick=()=>{const stamp=seconds=>{const ms=Math.round(seconds*1000),h=Math.floor(ms/3600000),m=Math.floor(ms/60000)%60,s=Math.floor(ms/1000)%60;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')},${String(ms%1000).padStart(3,'0')}`};let time=0,index=0;const lines=[];for(const s of scenes){const end=time+Number(s.duration||1),caption=String(s.caption||'').trim();if(caption)lines.push(`${++index}\n${stamp(time)} --> ${stamp(end)}\n${caption}\n`);time=end}if(!lines.length){$('status').textContent='पहले किसी सीन में Dialogue / Caption लिखें।';return}const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'application/x-subrip;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='APANAM-cartoon-subtitles.srt';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);$('status').textContent=`${index} सबटाइटल वाली SRT फ़ाइल डाउनलोड हुई।`};
  $('restoreVideo').onchange=async event=>{const file=event.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data.format!=='apanam-cartoon-project'||!Array.isArray(data.scenes)||!data.scenes.length||data.scenes.length>100||data.scenes.some(s=>!s||typeof s.title!=='string'||typeof s.caption!=='string'||!Number.isFinite(Number(s.duration))))throw Error('invalid');if(!confirm('मौजूदा वीडियो के सीन बदल जाएँगे। बैकअप खोलें?'))return;scenes=data.scenes.map(s=>({...defaults,...s,duration:Math.min(15,Math.max(1,Number(s.duration)||1))}));save();select(0);$('status').textContent=`${scenes.length} सीन वापस आ गए।`}catch(_){$('status').textContent='सही APANAM वीडियो प्रोजेक्ट JSON चुनें।'}finally{event.target.value=''}};
  $('export').onclick=async()=>{if(playing)stop();if(!window.MediaRecorder||!canvas.captureStream){$('status').textContent='इस browser में WebM export उपलब्ध नहीं है';return}
    const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(x=>MediaRecorder.isTypeSupported(x));if(!mime){$('status').textContent='इस browser में WebM export उपलब्ध नहीं है';return}
    $('export').disabled=true;$('status').textContent='वीडियो तैयार हो रहा है…';let stream=canvas.captureStream(30);
    try{
      if(audioFile){const Context=window.AudioContext||window.webkitAudioContext;if(!Context)throw new Error('इस browser में audio export उपलब्ध नहीं है');audioContext=new Context();await audioContext.resume();const buffer=await audioContext.decodeAudioData(await audioFile.arrayBuffer());const destination=audioContext.createMediaStreamDestination();audioSource=audioContext.createBufferSource();audioSource.buffer=buffer;audioSource.connect(destination);stream.addTrack(destination.stream.getAudioTracks()[0]);}
      draw(scenes[0],0);const chunks=[];recorder=new MediaRecorder(stream,{mimeType:mime});recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};
      recorder.onstop=()=>{try{audioSource?.stop()}catch(_){}audioSource=null;audioContext?.close();audioContext=null;stream.getTracks().forEach(track=>track.stop());$('export').disabled=false;if(!chunks.length){$('status').textContent='Export नहीं बन पाया';return}const url=URL.createObjectURL(new Blob(chunks,{type:mime})),a=document.createElement('a');a.href=url;a.download='APANAM-cartoon-video.webm';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);$('status').textContent=audioFile?'आवाज़ के साथ WebM video तैयार है':'WebM video तैयार है';recorder=null};
      recorder.onerror=()=>{$('status').textContent='वीडियो रिकॉर्ड नहीं हो सका';stop()};recorder.onstart=()=>{audioSource?.start();play(true)};recorder.start();
    }catch(error){stream.getTracks().forEach(track=>track.stop());audioContext?.close();audioContext=null;audioSource=null;$('export').disabled=false;$('status').textContent='ऑडियो फ़ाइल नहीं खुली या ब्राउज़र इसे रिकॉर्ड नहीं कर सका। दूसरी MP3/WAV फ़ाइल चुनें।'}
  };
  window.APANAM_CARTOON_PROJECT={snapshot:()=>scenes.map(s=>({...s})),restore(incoming){if(!Array.isArray(incoming)||!incoming.length||incoming.length>100||incoming.some(s=>!s||typeof s.title!=='string'||typeof s.caption!=='string'||!Number.isFinite(Number(s.duration))))return false;scenes=incoming.map(s=>({...defaults,...s,duration:Math.min(15,Math.max(1,Number(s.duration)||1))}));save();select(0);return true}};
  select(0);updateTimeline()
})();
