(()=>{
  const api=window.APANAM_CARTOON_PROJECT,series=document.querySelector('.series-manager'),scenesRoot=document.getElementById('scenes');if(!api||!series||!scenesRoot)return;
  const box=document.createElement('section');box.className='chapter-manager';box.innerHTML=`<h2>Long Film · Chapter Manager</h2><p>लंबी कहानी को छोटे chapters में बाँटें। हर chapter को अलग project की तरह export करना सुरक्षित रहता है।</p><label>इस Scene का Chapter<input id="chapterName" maxlength="60" placeholder="जैसे: अध्याय 1 · शुरुआत"></label><div class="pair"><button type="button" id="applyChapter">इस Scene में लगाएँ</button><button type="button" id="newChapter">＋ नया Chapter</button></div><div class="chapter-summary"></div><div class="chapter-list"></div><button type="button" id="downloadChapter">⬇ चुना Chapter JSON</button>`;series.after(box);
  const input=box.querySelector('#chapterName'),summary=box.querySelector('.chapter-summary'),list=box.querySelector('.chapter-list');let chosen='';
  const scenes=()=>api.snapshot(),current=()=>api.currentScene();
  function chapters(){const map=new Map();scenes().forEach((scene,index)=>{const name=String(scene.chapter||'बिना Chapter').trim()||'बिना Chapter';if(!map.has(name))map.set(name,[]);map.get(name).push(index)});return map}
  function render(){input.value=String(current()?.chapter||'');const map=chapters(),all=scenes(),seconds=all.reduce((sum,scene)=>sum+Number(scene.duration||1),0);summary.textContent=`${all.length} Scenes · ${map.size} Chapters · ${Math.floor(seconds/60)}m ${Math.round(seconds%60)}s`;list.replaceChildren();for(const [name,indexes] of map){const button=document.createElement('button');button.type='button';button.className=name===chosen?'active':'';button.textContent=`${name} · ${indexes.length} scene`;button.onclick=()=>{chosen=name;render();scenesRoot.querySelectorAll('.scene-row')[indexes[0]]?.querySelector('button')?.click()};list.append(button)}}
  function apply(name){const value=String(name||'').trim().slice(0,60);if(!value){document.getElementById('status').textContent='Chapter का नाम लिखें।';return}current().chapter=value;chosen=value;api.refreshScene();document.getElementById('status').textContent=`यह scene “${value}” में जुड़ गया।`;render()}
  box.querySelector('#applyChapter').onclick=()=>apply(input.value);box.querySelector('#newChapter').onclick=()=>{const names=[...chapters().keys()].filter(name=>name!=='बिना Chapter'),next=`अध्याय ${names.length+1}`;input.value=next;apply(next)};
  box.querySelector('#downloadChapter').onclick=()=>{const name=chosen||String(current()?.chapter||'').trim();if(!name||name==='बिना Chapter'){document.getElementById('status').textContent='पहले किसी Chapter को चुनें या scene में chapter लगाएँ।';return}const selected=scenes().filter(scene=>String(scene.chapter||'').trim()===name);if(!selected.length)return;const data={format:'apanam-cartoon-project',version:1,name,scenes:selected,settings:api.snapshotSettings()},url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=`APANAM-${name.replace(/[^\p{L}\p{N}]+/gu,'-').slice(0,45)||'chapter'}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),60000);document.getElementById('status').textContent=`${name} का JSON backup डाउनलोड हुआ। Audio files अलग सुरक्षित रखें।`};
  scenesRoot.addEventListener('click',()=>setTimeout(render,0));document.addEventListener('apanam-scene-change',render);render();
})();
