(()=>{
  if(document.getElementById('apanamCreatorHubButton'))return;
  const header=document.querySelector('body>header');if(!header)return;
  const button=document.createElement('button');button.id='apanamCreatorHubButton';button.type='button';button.textContent='✦ Home';button.title='APANAM Creator Dashboard';
  const actions=header.querySelector('.actions');(actions||header).prepend(button);
  const overlay=document.createElement('div');overlay.className='apanam-hub-overlay';overlay.hidden=true;
  overlay.innerHTML=`<section class="apanam-hub" role="dialog" aria-modal="true" aria-labelledby="apanam-hub-title"><div class="apanam-hub-head"><div><small>APANAM AI CREATIVE STUDIO</small><h2 id="apanam-hub-title">Creator Dashboard</h2><p>डिज़ाइन, वीडियो और अपने प्रोजेक्ट एक जगह से खोलें।</p></div><button type="button" data-hub="close" aria-label="बंद करें">✕</button></div><div class="apanam-hub-tabs" role="tablist"><button type="button" class="active" data-hub-view="create">＋ नया बनाएँ</button><button type="button" data-hub-view="projects">▣ मेरे प्रोजेक्ट</button></div><div class="apanam-hub-view active" data-view="create"><div class="apanam-hub-grid"><button type="button" data-hub="poster"><span>🎨</span><strong>पोस्टर बनाएँ</strong><small>टेम्पलेट, टेक्स्ट, फ़ोटो और PDF</small></button><button type="button" data-hub="product"><span>🛍️</span><strong>प्रोडक्ट डिज़ाइन</strong><small>कीमत, ऑफ़र और लिस्टिंग फ़ोटो</small></button><a href="cartoon-video.html"><span>🎬</span><strong>कार्टून वीडियो</strong><small>सीन, आवाज़ और WebM डाउनलोड</small></a><button type="button" data-hub="posterVideo"><span>🎞️</span><strong>पोस्टर से वीडियो</strong><small>खुले पोस्टर को नए वीडियो सीन में भेजें</small></button></div></div><div class="apanam-hub-view" data-view="projects"><div class="apanam-project-summary"><article><span>🎨</span><div><strong data-poster-count>—</strong><small>सेव पोस्टर</small></div><button type="button" data-hub="gallery">पोस्टर खोलें</button></article><article><span>🎬</span><div><strong data-video-count>—</strong><small>सेव वीडियो</small></div><a href="cartoon-video.html?gallery=1">वीडियो खोलें</a></article></div><p class="apanam-project-help">प्रोजेक्ट इसी browser में सुरक्षित रहते हैं। दूसरे फ़ोन या कंप्यूटर के लिए Gallery से JSON backup डाउनलोड करें।</p></div><p data-hub-status role="status">नया काम शुरू करें या पहले से सेव प्रोजेक्ट खोलें।</p></section>`;
  document.body.append(overlay);const status=overlay.querySelector('[data-hub-status]');
  const dbCount=(name,store)=>new Promise(resolve=>{if(!window.indexedDB){resolve(0);return}const request=indexedDB.open(name);request.onerror=()=>resolve(0);request.onsuccess=()=>{try{const database=request.result;if(!database.objectStoreNames.contains(store)){database.close();resolve(0);return}const count=database.transaction(store).objectStore(store).count();count.onsuccess=()=>{database.close();resolve(count.result||0)};count.onerror=()=>{database.close();resolve(0)}}catch(_){resolve(0)}}});
  async function updateCounts(){const [posters,videos]=await Promise.all([dbCount('apanam-manual-gallery','posters'),dbCount('apanam-cartoon-gallery','projects')]);overlay.querySelector('[data-poster-count]').textContent=posters;overlay.querySelector('[data-video-count]').textContent=videos}
  function showView(name){overlay.querySelectorAll('[data-hub-view]').forEach(tab=>tab.classList.toggle('active',tab.dataset.hubView===name));overlay.querySelectorAll('[data-view]').forEach(view=>view.classList.toggle('active',view.dataset.view===name));if(name==='projects')updateCounts()}
  const close=()=>{overlay.hidden=true;button.focus()};button.onclick=()=>{overlay.hidden=false;showView('create');overlay.querySelector('[data-hub="close"]').focus()};
  overlay.addEventListener('click',async event=>{if(event.target===overlay){close();return}const viewButton=event.target.closest('[data-hub-view]');if(viewButton){showView(viewButton.dataset.hubView);return}const target=event.target.closest('[data-hub]');if(!target)return;if(target.dataset.hub==='close')close();if(target.dataset.hub==='gallery'){close();document.getElementById('loadProject')?.click()}if(target.dataset.hub==='posterVideo'){if(!document.querySelector('#stage .element')){status.textContent='पहले कैनवास पर पोस्टर बनाएँ या खोलें।';return}if(!window.APANAM_RENDER_CANVAS){status.textContent='पोस्टर तैयार नहीं है। पेज दोबारा खोलें।';return}target.disabled=true;status.textContent='पोस्टर वीडियो के लिए तैयार हो रहा है…';try{const source=await window.APANAM_RENDER_CANVAS(),scale=Math.min(1,960/Math.max(source.width,source.height)),output=document.createElement('canvas');output.width=Math.max(1,Math.round(source.width*scale));output.height=Math.max(1,Math.round(source.height*scale));output.getContext('2d').drawImage(source,0,0,output.width,output.height);sessionStorage.setItem('apanam-poster-to-video',output.toDataURL('image/jpeg',.75));window.location.href='cartoon-video.html'}catch(_){status.textContent='पोस्टर नहीं भेजा जा सका। चित्र छोटा करें और फिर कोशिश करें।';target.disabled=false}}if(target.dataset.hub==='poster'||target.dataset.hub==='product'){const tab=[...document.querySelectorAll('button')].find(el=>el.textContent.trim()===(target.dataset.hub==='product'?'Product':'Templates'));close();tab?.click();document.querySelector('#stageWrap')?.scrollIntoView({block:'nearest',behavior:'smooth'})}});
  document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!overlay.hidden)close()});
})();
