(()=>{
  const poster=document.getElementById('stage'),video=document.getElementById('screen');if(!poster&&!video)return;
  const header=document.querySelector('body>header'),button=document.createElement('button');button.type='button';button.id='apanamHelpButton';button.textContent='? Help';button.title='काम करने का आसान तरीका';(header.querySelector('.actions')||header).append(button);
  const overlay=document.createElement('div');overlay.className='apanam-help-overlay';overlay.hidden=true;
  const posterSteps=[['1','Template चुनें','Templates में अपनी category का डिज़ाइन चुनें।'],['2','Text और Photo बदलें','किसी element पर click करके edit करें।'],['3','Brand लगाएँ','Logo, रंग, फोन और social handle सेव करें।'],['4','Project सुरक्षित रखें','Save से gallery में रखें और JSON backup लें।'],['5','Download करें','PNG, JPG, WebP या PDF चुनें।']];
  const videoSteps=[['1','Scene बनाएँ','हर भाग का title, caption और समय लिखें।'],['2','Photo और Layers जोड़ें','Background, अतिरिक्त Text/Photo और Logo लगाएँ।'],['3','आवाज़ जोड़ें','मुख्य music, recording या scene की अलग audio चुनें।'],['4','Series व Subtitle','Series/Episode भरें और जरूरत पर SRT खोलें।'],['5','Export व Backup','WebM बनाएँ और audio सहित पूरा JSON backup लें।']];
  const steps=poster?posterSteps:videoSteps;
  overlay.innerHTML=`<section class="apanam-help" role="dialog" aria-modal="true" aria-labelledby="apanam-help-title"><header><div><small>APANAM CREATIVE STUDIO</small><h2 id="apanam-help-title">${poster?'Poster':'Video'} बनाने का आसान तरीका</h2></div><button type="button" data-help-close aria-label="बंद करें">✕</button></header><div class="apanam-help-body"><div class="apanam-help-steps">${steps.map(step=>`<article><b>${step[0]}</b><div><strong>${step[1]}</strong><p>${step[2]}</p></div></article>`).join('')}</div><aside><h3>तुरंत शुरू करें</h3><button type="button" data-help-sample>✨ Sample ${poster?'Poster':'Video'} खोलें</button><button type="button" data-help-projects>▣ मेरे Projects</button><p><strong>जरूरी:</strong> Projects इसी browser में रहते हैं। दूसरे device के लिए JSON backup सुरक्षित रखें।</p><p>AI के बिना Manual Poster और Video tools मुफ्त चलते हैं।</p></aside></div></section>`;document.body.append(overlay);
  const close=()=>{overlay.hidden=true;button.focus()};button.onclick=()=>overlay.hidden=false;overlay.onclick=event=>{if(event.target===overlay||event.target.closest('[data-help-close]'))close()};
  overlay.querySelector('[data-help-projects]').onclick=()=>{close();(poster?document.getElementById('loadProject'):document.getElementById('openVideoGallery'))?.click()};
  overlay.querySelector('[data-help-sample]').onclick=()=>{if(poster){const template=document.querySelector('[data-pro-template="listing"]');if(!template){document.getElementById('apanamCreatorHubButton')?.click();return}if(document.querySelector('#stage .element')&&!confirm('अभी खुला Poster बदल जाएगा। Sample Poster खोलें?'))return;close();template.click();document.getElementById('stageWrap')?.scrollIntoView({behavior:'smooth',block:'center'})}else{if(!confirm('अभी खुले Video scenes बदल जाएँगे। 3-scene Sample खोलें?'))return;const sample=[{title:'आपका परिचय',caption:'अपने Brand या कहानी की शुरुआत यहाँ करें।',duration:4,background:'#4c1d95',character:'#facc15',characterType:'person',motion:'bounce',transition:'fade',titleColor:'#ffffff',captionColor:'#ffffff',titleSize:56,captionSize:32,captionPosition:'lower',photoFit:'cover'},{title:'मुख्य जानकारी',caption:'Product, सेवा या कहानी का सबसे जरूरी लाभ बताएँ।',duration:5,background:'#075985',character:'#fb7185',characterType:'smile',motion:'slide',transition:'wipe',titleColor:'#ffffff',captionColor:'#ffffff',titleSize:56,captionSize:32,captionPosition:'lower',photoFit:'cover'},{title:'अंतिम संदेश',caption:'आज ही संपर्क करें · धन्यवाद',duration:4,background:'#14532d',character:'#fde047',characterType:'cat',motion:'bounce',transition:'flash',titleColor:'#ffffff',captionColor:'#ffffff',titleSize:56,captionSize:32,captionPosition:'bottom',photoFit:'cover'}];if(window.APANAM_CARTOON_PROJECT?.restore(sample)){close();document.getElementById('status').textContent='3-scene Sample Video खुल गया। अब text, photo और audio बदलें।'}}};
  document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!overlay.hidden)close()});
})();
