(()=>{'use strict';
const api=window.APANAM_CLOUD,form=document.getElementById('memberLogin'),status=document.getElementById('memberStatus'),id=document.getElementById('memberId'),logout=document.getElementById('memberLogout'),refresh=document.getElementById('memberRefresh'),copy=document.getElementById('memberCopyId'),details=document.getElementById('memberValidity');let busy=false,sequence=0;
const date=v=>v?new Date(v).toLocaleString('hi-IN',{timeZone:'Asia/Kolkata'}):'—';
const state=r=>!r?'कोई membership नहीं':r.revoked?'Access वापस लिया गया':Date.parse(r.expires_at)>Date.now()?'सक्रिय':'अवधि समाप्त';
async function render(){const n=++sequence,user=api.user();id.textContent='';details.replaceChildren();copy.hidden=true;logout.hidden=refresh.hidden=!user;if(!user){status.textContent='Membership देखने के लिए Login करें।';return;}status.textContent='Membership लोड हो रही है…';try{const access=await api.memberAccess();const record=access?.expires_at?{...access,granted_at:access.started_at}:null;if(n!==sequence||api.user()?.id!==user.id)return;id.textContent='आपकी User ID: '+user.id;copy.hidden=false;const active=record&&!record.revoked&&Date.parse(record.expires_at)>Date.now();const plan=record?.kind==='paid'?'Paid Manual Membership':record?.kind==='trial'?'Trial':'मुफ्त Business Membership';status.textContent=active?plan+' · सक्रिय':record?.revoked?'Admin ने मुफ्त Manual Access वापस लिया है। Admin से संपर्क करें।':record?'Membership की अवधि समाप्त हो गई है। नीचे renewal विकल्प देखें।':'इस account में active paid, trial या Business membership नहीं है। उपलब्ध योजनाएँ नीचे देखें।';for(const [label,value] of [['योजना',record?plan:'—'],['स्थिति',state(record)],['शुरू',date(record?.granted_at)],['समाप्त',date(record?.expires_at)],['बचे दिन',active?String(Math.ceil((Date.parse(record.expires_at)-Date.now())/86400000)):'—']]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;details.append(dt,dd);}}catch(error){if(n===sequence)status.textContent='स्थिति नहीं मिली: '+error.message;}}
form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const button=form.querySelector('[type=submit]');button.disabled=true;try{await api.signIn(form.elements.email.value.trim(),form.elements.password.value);form.elements.password.value='';await render();}catch(error){status.textContent=error.message;}finally{busy=false;button.disabled=false;}};
logout.onclick=async()=>{try{await api.signOut();}catch(error){status.textContent='Logout नहीं हुआ: '+error.message;return;}await render();};refresh.onclick=render;
copy.onclick=async()=>{const user=api.user();if(!user)return;try{await navigator.clipboard.writeText(user.id);copy.textContent='User ID copy हुई';}catch{const selection=window.getSelection(),range=document.createRange();range.selectNodeContents(id);selection.removeAllRanges();selection.addRange(range);copy.textContent='User ID चुनी है · Copy करें';}};
document.addEventListener('apanam-membership-updated',render);document.addEventListener('apanam-cloud-session',()=>{copy.textContent='User ID copy करें';render();});render();
})();
