(()=>{'use strict';function init(){const stage=document.getElementById('stage'),video=document.getElementById('screen');if(!stage&&!video)return;const open=document.createElement('button');open.id='apanamSocialShare';open.type='button';open.textContent='Share ↗';open.title='बना हुआ poster या video भेजें';const actions=document.querySelector('header .actions')||document.querySelector('header'),downloadButton=document.getElementById('download');if(downloadButton?.parentElement===actions)downloadButton.after(open);else actions.append(open);
const modal=document.createElement('dialog');modal.id='apanamShareDialog';modal.innerHTML='<div class="social-share-heading"><strong>Poster / Video भेजें</strong><button type="button" data-share-close>✕ बंद</button></div><p id="socialShareStatus" role="status"></p><div class="social-share-platforms"></div><button type="button" id="socialShareNative">↗ फोन / कंप्यूटर के apps में भेजें</button><button type="button" id="socialShareDownload">↓ फ़ाइल Download करें</button><button type="button" id="socialShareVideo">पहले वीडियो तैयार करें</button><p class="social-share-note">Share खुलने पर अपना app और व्यक्ति चुनें। अगर फ़ाइल sharing उपलब्ध नहीं है, Download करके उस app में attach करें।</p>';document.body.append(modal);let file=null,version=0;const status=modal.querySelector('#socialShareStatus'),native=modal.querySelector('#socialShareNative'),download=modal.querySelector('#socialShareDownload'),prepareVideo=modal.querySelector('#socialShareVideo');modal.querySelector('[data-share-close]').onclick=()=>{version++;modal.close()};
function supported(){try{return !!(file&&navigator.share&&navigator.canShare?.({files:[file]}))}catch(_){return false}}
function sync(){native.disabled=!file||!supported();download.disabled=!file;modal.querySelectorAll('[data-platform]').forEach(b=>b.disabled=!file);prepareVideo.hidden=!video||!!file;}
function save(){if(!file)return;const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);status.textContent='फ़ाइल Download हुई। चुने हुए app में इसे attach करें।';}
async function share(platform){if(!file)return;if(!supported()){save();return;}try{await navigator.share({files:[file],title:'APANAM Creative',text:''});status.textContent='Share window खुली।'+(platform?' वहाँ '+platform+' चुनें।':'');}catch(e){status.textContent=e.name==='AbortError'?'Sharing रद्द हुई। फ़ाइल तैयार है।':'सीधे sharing नहीं खुली। Download करके फ़ाइल भेजें।';}}
for(const name of ['WhatsApp','Facebook','Instagram','Telegram','अन्य apps']){const b=document.createElement('button');b.type='button';b.dataset.platform=name;b.textContent=name;b.onclick=()=>share(name);modal.querySelector('.social-share-platforms').append(b);}native.onclick=()=>share();download.onclick=save;prepareVideo.onclick=()=>{version++;modal.close();document.getElementById('export')?.click();};
open.onclick=async()=>{const current=++version;file=null;status.textContent=video?'तैयार वीडियो जाँच रहे हैं…':'Poster फ़ाइल तैयार हो रही है…';sync();modal.showModal();try{if(video){const link=document.getElementById('videoDownloadLink');if(!link){status.textContent='पहले WebM वीडियो तैयार करें, फिर Share दबाएँ।';sync();return;}const blob=await (await fetch(link.href)).blob();if(current!==version)return;file=new File([blob],link.download||'APANAM-video.webm',{type:blob.type||'video/webm'});}else{if(!stage.querySelector('.element'))throw Error('पहले अपना poster बनाएँ।');const canvas=await window.APANAM_RENDER_CANVAS(),blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Poster फ़ाइल नहीं बन सकी।')),'image/png'));if(current!==version)return;file=new File([blob],'APANAM-poster.png',{type:'image/png'});}status.textContent=file.name+' · '+Math.max(1,Math.round(file.size/1024))+' KB · '+(supported()?'App चुनकर फ़ाइल भेजें।':'इस browser में सीधे फ़ाइल sharing उपलब्ध नहीं है। Download करके attach करें।');sync();}catch(e){if(current!==version)return;status.textContent=e.message||'फ़ाइल तैयार नहीं हुई। दोबारा कोशिश करें।';sync();}};
}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();})();
