(()=>{'use strict';
const config=window.APANAM_CLOUD_CONFIG;if(!config?.url||!config?.key)return;
const KEY='apanam-studio-cloud-session-v1';let session=null,refreshing=null;const versions={};
try{session=JSON.parse(sessionStorage.getItem(KEY)||'null')}catch{}
function remember(value){session=value;try{if(value)sessionStorage.setItem(KEY,JSON.stringify(value));else sessionStorage.removeItem(KEY)}catch{}document.dispatchEvent(new Event('apanam-cloud-session'));}
async function request(path,options={},token){const headers={apikey:config.key,...options.headers};if(token)headers.Authorization='Bearer '+token;const response=await fetch(config.url+path,{...options,headers,signal:options.signal||AbortSignal.timeout(12000)});let data;try{data=await response.json()}catch{data=null}if(!response.ok)throw Error(data?.msg||data?.message||data?.error_description||data?.error||'Cloud request असफल ('+response.status+')');return data;}
async function access(){if(!session)throw Error('पहले login करें।');if(session.expires_at*1000>Date.now()+60000)return session.access_token;if(!refreshing)refreshing=request('/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})}).then(value=>{remember({...value,recovery:session?.recovery===true});return value.access_token}).catch(error=>{remember(null);throw error}).finally(()=>refreshing=null);return refreshing;}
async function signIn(email,password){const value=await request('/auth/v1/token?grant_type=password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});remember(value);return value.user;}
async function signUp(email,password){return request('/auth/v1/signup?redirect_to='+encodeURIComponent(authRedirect()),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});}
async function signOut(){try{if(session)await request('/auth/v1/logout',{method:'POST'},await access())}finally{remember(null)}}

let authLinkError='';
function authRedirect(){return new URL('membership.html',location.href).href.split('#')[0].split('?')[0];}
async function resetPasswordEmail(email){return request('/auth/v1/recover?redirect_to='+encodeURIComponent(authRedirect()),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});}
async function resendVerification(email){return request('/auth/v1/resend?redirect_to='+encodeURIComponent(authRedirect()),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,type:'signup'})});}
async function changeRecoveredPassword(password){if(!session?.recovery)throw Error('पहले email का नया password reset link खोलें।');if(password.length<8)throw Error('कम से कम 8 अक्षर रखें।');const user=await request('/auth/v1/user',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})},await access());remember({...session,user,recovery:false});return user;}
const authReady=(async()=>{const hash=new URLSearchParams(location.hash.slice(1));if(!hash.has('access_token')&&!hash.has('error'))return;if(hash.has('error')){authLinkError='Email link अमान्य या समाप्त है। नया link माँगें।';history.replaceState(null,'',location.pathname+location.search);return;}const token=hash.get('access_token'),refreshToken=hash.get('refresh_token'),recovery=hash.get('type')==='recovery';history.replaceState(null,'',location.pathname+location.search);if(!token||!refreshToken){authLinkError='Email link अधूरा है। नया link माँगें।';return;}try{const user=await request('/auth/v1/user',{},token);remember({access_token:token,refresh_token:refreshToken,expires_at:Math.floor(Date.now()/1000)+Math.max(60,Math.min(86400,Number(hash.get('expires_in'))||3600)),user,recovery});}catch{authLinkError='Email link नहीं खुला। नया link माँगें।';}})();

async function isAdmin(){if(!session)return false;const token=await access(),user=await request('/auth/v1/user',{},token);const rows=await request('/rest/v1/studio_admins?select=user_id&user_id=eq.'+encodeURIComponent(user.id),{},token);return rows?.length===1;}
async function load(id='published'){const rows=await request('/rest/v1/studio_catalogs?select=payload,version&id=eq.'+id,{signal:AbortSignal.timeout(id==='published'?3500:12000)},id==='draft'?await access():undefined);if(!rows?.[0])throw Error('Cloud catalog उपलब्ध नहीं है।');versions[id]=rows[0].version;return window.APANAM_CATALOG.catalog(rows[0].payload);}
async function save(id,catalog){if(!await isAdmin())throw Error('इस account को admin अधिकार नहीं मिला है।');if(!versions[id])await load(id);const payload=window.APANAM_CATALOG.catalog(catalog);if(id==='published')payload.templates=payload.templates.filter(t=>t.published);if(new Blob([JSON.stringify(payload)]).size>10*1024*1024)throw Error('Catalog 10 MB से बड़ा है। बड़े image को छोटा करें।');const token=await access();const rows=await request('/rest/v1/studio_catalogs?id=eq.'+id+'&version=eq.'+versions[id],{method:'PATCH',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({payload,version:versions[id]+1,updated_at:new Date().toISOString()})},token);if(!rows?.[0])throw Error('दूसरे admin ने catalog बदला है। Cloud से नया draft लें; आपका local backup सुरक्षित है।');versions[id]=rows[0].version;return payload;}
async function prepareAssets(catalog){
 const clean=window.APANAM_CATALOG.catalog(catalog),sources=new Map(),boxes=[];
 for(const item of clean.templates){const box=document.createElement('div');box.innerHTML=item.project.html;boxes.push([item,box]);for(const img of box.querySelectorAll('img'))if(img.src.startsWith('data:image/'))sources.set(img.src,null);if(item.project.bgImage.startsWith('data:image/'))sources.set(item.project.bgImage,null);}
 // Validate the complete batch before any upload consumes storage.
 for(const src of sources.keys()){const blob=await (await fetch(src)).blob();if(!['image/png','image/jpeg','image/webp','image/gif'].includes(blob.type))throw Error('PNG/JPG/WebP/GIF image चुनें।');if(blob.size>2*1024*1024)throw Error('हर poster/photo 2 MB से छोटा रखें।');sources.set(src,blob);}
 const urls=new Map();for(const [src,blob] of sources){const extension=blob.type==='image/jpeg'?'jpg':blob.type.split('/')[1],name=crypto.randomUUID()+'.'+extension;await request('/storage/v1/object/studio-posters/'+name,{method:'POST',headers:{'Content-Type':blob.type},body:blob},await access());urls.set(src,config.url+'/storage/v1/object/public/studio-posters/'+name);}
 for(const [item,box] of boxes){for(const img of box.querySelectorAll('img'))if(urls.has(img.src))img.src=urls.get(img.src);item.project.html=box.innerHTML;if(urls.has(item.project.bgImage))item.project.bgImage=urls.get(item.project.bgImage);}return clean;
}
async function membership(){const user=await request('/auth/v1/user',{},await access());const rows=await request('/rest/v1/studio_memberships?select=plan,granted_at,expires_at,revoked&user_id=eq.'+encodeURIComponent(user.id),{},await access());return rows?.[0]||null;}
async function grantManual(userId,days){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(userId))throw Error('सही user ID चुनें।');days=Number(days);if(!Number.isInteger(days)||days<1||days>365)throw Error('1–365 दिन चुनें।');if(!await isAdmin())throw Error('Admin login जरूरी है।');return request('/rest/v1/studio_memberships?on_conflict=user_id',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({user_id:userId,plan:'manual_complimentary',expires_at:new Date(Date.now()+days*86400000).toISOString(),granted_by:session.user.id,revoked:false,granted_at:new Date().toISOString()})},await access());}
async function listMemberships(){if(!await isAdmin())throw Error('Admin login जरूरी है।');return request('/rest/v1/studio_memberships?select=user_id,plan,expires_at,revoked&order=expires_at.desc&limit=100',{},await access());}
async function revokeManual(userId){if(!await isAdmin())throw Error('Admin login जरूरी है।');const rows=await request('/rest/v1/studio_memberships?user_id=eq.'+encodeURIComponent(userId),{method:'PATCH',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({revoked:true,granted_by:session.user.id})},await access());if(!rows?.length)throw Error('Membership नहीं मिली।');return rows[0];}
const projectVersions=new Map();
async function listProjects(){const token=await access(),user=await request('/auth/v1/user',{},token);const rows=await request('/rest/v1/studio_projects?select=slot,title,version,updated_at&user_id=eq.'+encodeURIComponent(user.id)+'&order=slot',{},token);for(const row of rows)if(!projectVersions.has(user.id+':'+row.slot))projectVersions.set(user.id+':'+row.slot,row.version);return rows;}
async function loadProject(slot){const token=await access(),user=await request('/auth/v1/user',{},token);const rows=await request('/rest/v1/studio_projects?select=payload,title,version&user_id=eq.'+encodeURIComponent(user.id)+'&slot=eq.'+Number(slot),{},token);if(!rows?.[0])throw Error('इस slot में poster नहीं है।');projectVersions.set(user.id+':'+slot,rows[0].version);return {...rows[0],payload:window.APANAM_CATALOG.project(rows[0].payload)};}
async function saveProject(slot,title,project){slot=Number(slot);if(!Number.isInteger(slot)||slot<1||slot>5)throw Error('1–5 slot चुनें।');title=String(title||'').trim().slice(0,80);if(!title)throw Error('Poster का नाम लिखें।');const payload=window.APANAM_CATALOG.project(project);if(new Blob([JSON.stringify(payload)]).size>1900000)throw Error('Cloud poster 2 MB सीमा से बड़ा है। छोटा image चुनें; local JSON backup रखें।');const token=await access(),user=await request('/auth/v1/user',{},token),key=user.id+':'+slot,version=projectVersions.get(key),body={user_id:user.id,slot,title,payload,version:version?version+1:1,updated_at:new Date().toISOString()};const rows=await request('/rest/v1/studio_projects'+(version?'?user_id=eq.'+encodeURIComponent(user.id)+'&slot=eq.'+slot+'&version=eq.'+version:'?on_conflict=user_id,slot'),{method:version?'PATCH':'POST',headers:{'Content-Type':'application/json',Prefer:version?'return=representation':'resolution=ignore-duplicates,return=representation'},body:JSON.stringify(body)},token);if(!rows?.length)throw Error('दूसरे device से poster बदला है। Local backup रखें; cloud poster खोलकर बदलाव मिलाएँ।');projectVersions.set(key,rows[0].version);return rows[0];}

async function deleteProject(slot,expectedUserId){slot=Number(slot);if(!Number.isInteger(slot)||slot<1||slot>5)throw Error('1–5 slot चुनें।');const token=await access(),user=await request('/auth/v1/user',{},token),key=user.id+':'+slot,version=projectVersions.get(key);if(expectedUserId&&user.id!==expectedUserId)throw Error('Account बदल गया। दोबारा खोलें।');if(!version)throw Error('पहले cloud सूची या poster खोलें।');const rows=await request('/rest/v1/studio_projects?user_id=eq.'+encodeURIComponent(user.id)+'&slot=eq.'+slot+'&version=eq.'+version,{method:'DELETE',headers:{Prefer:'return=representation'}},token);if(!rows?.length)throw Error('Poster बदल गया या हट चुका है। सूची Refresh करें।');projectVersions.delete(key);return true;}
async function accountProfile(){const token=await access(),user=await request('/auth/v1/user',{},token);const [rows,member,admin,entitlement]=await Promise.all([request('/rest/v1/studio_profiles?select=*&user_id=eq.'+encodeURIComponent(user.id),{},token),membership(),isAdmin(),memberAccess()]);return {user,profile:rows?.[0]||null,membership:member,admin,entitlement};}
async function saveProfile(value){const token=await access(),user=await request('/auth/v1/user',{},token);const payload={user_id:user.id,full_name:String(value.full_name||'').trim().slice(0,120),phone:String(value.phone||'').trim().slice(0,32),whatsapp:String(value.whatsapp||'').trim().slice(0,32),organization:String(value.organization||'').trim().slice(0,160),city:String(value.city||'').trim().slice(0,100),website:String(value.website||'').trim().slice(0,200),avatar_data:String(value.avatar_data||''),updated_at:new Date().toISOString()};if(payload.avatar_data.length>100000||payload.avatar_data&&!/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(payload.avatar_data))throw Error('Photo का आकार/format सही नहीं है। फिर चुनें।');const rows=await request('/rest/v1/studio_profiles?on_conflict=user_id',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(payload)},token);return rows[0];}

async function adminUsers(search='',offset=0,filter='all'){return request('/rest/v1/rpc/studio_admin_user_directory_v2',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({search_term:String(search).slice(0,120),page_offset:Math.max(0,Number(offset)||0),status_filter:filter})},await access());}
async function adminUserCount(search='',filter='all'){return request('/rest/v1/rpc/studio_admin_user_count_v2',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({search_term:String(search).slice(0,120),status_filter:filter})},await access());}

const videoVersions=new Map();
async function videoIdentity(expected){const token=await access(),user=await request('/auth/v1/user',{},token);if(expected&&user.id!==expected)throw Error('Account बदल गया। Cloud सूची फिर खोलें।');return {token,user};}
async function listVideoProjects(){const {token,user}=await videoIdentity();const rows=await request('/rest/v1/studio_video_projects?select=slot,title,version,updated_at&user_id=eq.'+encodeURIComponent(user.id)+'&order=slot',{},token);for(const row of rows)videoVersions.set(user.id+':'+row.slot,row.version);return rows;}
async function loadVideoProject(slot,expected){const {token,user}=await videoIdentity(expected);const rows=await request('/rest/v1/studio_video_projects?select=*&user_id=eq.'+encodeURIComponent(user.id)+'&slot=eq.'+Number(slot),{},token);if(!rows.length)throw Error('यह video slot खाली है।');videoVersions.set(user.id+':'+slot,rows[0].version);return rows[0];}
async function saveVideoProject(slot,title,payload,expected){slot=Number(slot);if(![1,2].includes(slot))throw Error('Video slot सही नहीं है।');if(payload?.format!=='apanam-cartoon-project-full'||!Array.isArray(payload.scenes)||!payload.scenes.length||payload.scenes.length>100||new TextEncoder().encode(JSON.stringify(payload)).length>2000000)throw Error('Video/audio backup अधिकतम 2 MB रखें। बड़ा पूरा JSON backup अपने पास रखें।');const {token,user}=await videoIdentity(expected),key=user.id+':'+slot;let version=videoVersions.get(key);if(version===undefined){const rows=await request('/rest/v1/studio_video_projects?select=version&user_id=eq.'+encodeURIComponent(user.id)+'&slot=eq.'+slot,{},token);version=rows[0]?.version;}const body={title:String(title||'मेरा Video').trim().slice(0,80)||'मेरा Video',payload};let rows;if(version!==undefined){rows=await request('/rest/v1/studio_video_projects?user_id=eq.'+encodeURIComponent(user.id)+'&slot=eq.'+slot+'&version=eq.'+version,{method:'PATCH',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(body)},token);}else{rows=await request('/rest/v1/studio_video_projects',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({...body,user_id:user.id,slot})},token);}if(!rows.length)throw Error('Cloud video दूसरे device पर बदल गया। Refresh करके फिर देखें।');videoVersions.set(key,rows[0].version);return rows[0];}
async function deleteVideoProject(slot,expected){const {token,user}=await videoIdentity(expected),key=user.id+':'+slot,version=videoVersions.get(key);if(version===undefined)throw Error('पहले चुना video backup खोलें।');const rows=await request('/rest/v1/studio_video_projects?user_id=eq.'+encodeURIComponent(user.id)+'&slot=eq.'+Number(slot)+'&version=eq.'+version,{method:'DELETE',headers:{Prefer:'return=representation'}},token);if(!rows.length)throw Error('Cloud video बदल गया। Refresh करके फिर देखें।');videoVersions.delete(key);return true;}


async function businessOverview(){return request('/rest/v1/rpc/studio_business_overview',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'},await access());}
async function startTrial(){return request('/rest/v1/rpc/studio_start_trial',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'},await access());}
async function saveReminderPreferences(email){const token=await access(),user=await request('/auth/v1/user',{},token);return request('/rest/v1/studio_notification_preferences?on_conflict=user_id',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({user_id:user.id,email_reminders:!!email,sms_reminders:false,updated_at:new Date().toISOString()})},token);}
async function aiQuote(kind,units){return request('/rest/v1/rpc/studio_ai_quote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request_kind:kind,units})},await access());}
async function adminBusiness(action,value={}){return request('/rest/v1/rpc/studio_admin_business',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,value})},await access());}
async function businessRequest(action,options={},binary=false){const uid=session?.user?.id,token=await access();if(!uid)throw Error('Login करें।');const r=await fetch(config.url+'/functions/v1/studio-business?action='+encodeURIComponent(action),{...options,method:'POST',headers:{apikey:config.key,Authorization:'Bearer '+token,...options.headers},signal:AbortSignal.timeout(60000)});let data;if(binary&&r.ok)data=await r.blob();else data=await r.json().catch(()=>null);if(session?.user?.id!==uid)throw Error('Account बदल गया। फिर खोलें।');if(!r.ok)throw Error(data?.error||'Cloud operation failed ('+r.status+')');return data;}
const businessStatus=()=>businessRequest('status');
async function listMedia(){const token=await access(),user=await request('/auth/v1/user',{},token);return request('/rest/v1/studio_media_files?select=id,title,bytes,mime,status,created_at&user_id=eq.'+encodeURIComponent(user.id)+'&status=neq.deleted&order=created_at.desc&limit=30',{},token);}
const uploadMedia=file=>businessRequest('upload',{headers:{'Content-Type':file.type||(/\.json$/i.test(file.name)?'application/json':'application/octet-stream'),'x-file-name':encodeURIComponent(file.name)},body:file});
const downloadMedia=id=>businessRequest('download',{headers:{'Content-Type':'application/json'},body:JSON.stringify({id})},true);
const deleteMedia=id=>businessRequest('delete',{headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});

async function paymentRequest(action,value={}){const uid=session?.user?.id,token=await access();const data=await request('/functions/v1/studio-payments?action='+encodeURIComponent(action),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value),signal:AbortSignal.timeout(45000)},token);if(session?.user?.id!==uid)throw Error('Account बदल गया। फिर जाँचें।');return data;}
async function paidMemberships(){return request('/rest/v1/studio_paid_memberships?select=environment,expires_at,updated_at&user_id=eq.'+encodeURIComponent(session?.user?.id||''),{},await access());}
async function adminPayments(environment,state,offset){return request('/rest/v1/rpc/studio_admin_payments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({payment_environment:environment,payment_state:state,page_offset:offset})},await access());}
async function memberAccess(){return request('/rest/v1/rpc/studio_member_access',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'},await access());}
async function ownPayments(offset=0){return request('/rest/v1/rpc/studio_own_payments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({page_offset:offset})},await access());}
async function alertHealth(){return request('/rest/v1/rpc/studio_alert_health',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'},await access());}
async function aiAccount(){return request('/rest/v1/rpc/studio_ai_account',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'},await access());}
async function aiBusinessSummary(){return request('/rest/v1/rpc/studio_ai_business_summary',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'},await access());}
async function aiPaymentRequest(action,value={}){const uid=session?.user?.id,token=await access();if(!uid)throw Error('Login करें।');const data=await request('/functions/v1/studio-ai-payments?action='+encodeURIComponent(action),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value),signal:AbortSignal.timeout(45000)},token);if(session?.user?.id!==uid)throw Error('Account बदल गया। फिर जाँचें।');return data;}
async function sarvamVoice(action,value={}){const uid=session?.user?.id,token=await access();if(!uid)throw Error('Login करें।');const r=await fetch(config.url+'/functions/v1/studio-sarvam-voice?action='+encodeURIComponent(action),{method:'POST',headers:{apikey:config.key,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(value),signal:AbortSignal.timeout(75000)});const data=r.ok&&action==='generate'?await r.blob():await r.json().catch(()=>null);if(session?.user?.id!==uid)throw Error('Account बदल गया।');if(!r.ok)throw Error(data?.error||'Voice request असफल');return data;}
async function paidVoice(action,value={}){const uid=session?.user?.id,token=await access();if(!uid)throw Error('Login करें।');const r=await fetch(config.url+'/functions/v1/studio-paid-voice?action='+encodeURIComponent(action),{method:'POST',headers:{apikey:config.key,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(value),signal:AbortSignal.timeout(75000)});const data=r.ok&&action==='generate'?await r.blob():await r.json().catch(()=>null);if(session?.user?.id!==uid)throw Error('Account बदल गया।');if(!r.ok)throw Error(data?.error||'Voice request असफल');return data;}
async function subscriptionRequest(action,value={}){const uid=session?.user?.id,token=await access();if(!uid)throw Error('Login करें।');const data=await request('/functions/v1/studio-subscriptions?action='+encodeURIComponent(action),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value),signal:AbortSignal.timeout(75000)},token);if(session?.user?.id!==uid)throw Error('Account बदल गया।');return data;}
window.APANAM_CLOUD={paidVoice,subscriptionRequest,sarvamVoice,aiAccount,aiBusinessSummary,aiPaymentRequest,memberAccess,ownPayments,alertHealth,adminPayments,paymentRequest,paidMemberships,businessOverview,startTrial,saveReminderPreferences,aiQuote,adminBusiness,businessStatus,listMedia,uploadMedia,downloadMedia,deleteMedia,listVideoProjects,loadVideoProject,saveVideoProject,deleteVideoProject,authReady,resetPasswordEmail,resendVerification,changeRecoveredPassword,isRecovery:()=>session?.recovery===true,authLinkError:()=>authLinkError,adminUserCount,adminUsers,accountProfile,saveProfile,listMemberships,revokeManual,deleteProject,listProjects,loadProject,saveProject,membership,grantManual,signIn,signUp,signOut,isAdmin,load,save,prepareAssets,user:()=>session?.user||null};
})();

