create or replace function public.studio_admin_user_directory_v2(search_term text default '',page_offset integer default 0,status_filter text default 'all')
returns table(user_id uuid,email text,account_created_at timestamptz,email_verified boolean,full_name text,phone text,whatsapp text,organization text,city text,website text,plan text,granted_at timestamptz,expires_at timestamptz,revoked boolean)
language plpgsql security definer set search_path='' as $$ begin if not exists(select 1 from public.studio_admins a where a.user_id=(select auth.uid())) then raise exception 'Admin access required' using errcode='42501'; end if; if status_filter not in ('all','active','expiring','expired','revoked','none') then raise exception 'Invalid status filter';end if;
return query select u.id,u.email::text,u.created_at,u.email_confirmed_at is not null,p.full_name,p.phone,p.whatsapp,p.organization,p.city,p.website,m.plan,m.granted_at,m.expires_at,m.revoked from auth.users u left join public.studio_profiles p on p.user_id=u.id left join public.studio_memberships m on m.user_id=u.id where (
 length(btrim(coalesce(search_term,'')))=0 or
 position(lower(left(btrim(coalesce(search_term,'')),120)) in lower(coalesce(u.email,'')||' '||coalesce(p.full_name,'')||' '||coalesce(p.organization,'')))>0 or
 (length(regexp_replace(coalesce(search_term,''),'[^0-9]','','g'))>=3 and
 (position(regexp_replace(search_term,'[^0-9]','','g') in regexp_replace(coalesce(p.phone,''),'[^0-9]','','g'))>0 or position(regexp_replace(search_term,'[^0-9]','','g') in regexp_replace(coalesce(p.whatsapp,''),'[^0-9]','','g'))>0))
) and (case status_filter when 'active' then m.user_id is not null and not m.revoked and m.expires_at>now() when 'expiring' then m.user_id is not null and not m.revoked and m.expires_at>now() and m.expires_at<=now()+interval '7 days' when 'expired' then m.user_id is not null and not m.revoked and m.expires_at<=now() when 'revoked' then coalesce(m.revoked,false) when 'none' then m.user_id is null else true end) order by u.created_at desc,u.id limit 50 offset greatest(0,coalesce(page_offset,0));end;$$;
create or replace function public.studio_admin_user_count_v2(search_term text default '',status_filter text default 'all') returns bigint language plpgsql security definer set search_path='' as $$begin if not exists(select 1 from public.studio_admins a where a.user_id=(select auth.uid())) then raise exception 'Admin access required' using errcode='42501'; end if; if status_filter not in ('all','active','expiring','expired','revoked','none') then raise exception 'Invalid status filter';end if; return (select count(*) from auth.users u left join public.studio_profiles p on p.user_id=u.id left join public.studio_memberships m on m.user_id=u.id where (
 length(btrim(coalesce(search_term,'')))=0 or
 position(lower(left(btrim(coalesce(search_term,'')),120)) in lower(coalesce(u.email,'')||' '||coalesce(p.full_name,'')||' '||coalesce(p.organization,'')))>0 or
 (length(regexp_replace(coalesce(search_term,''),'[^0-9]','','g'))>=3 and
 (position(regexp_replace(search_term,'[^0-9]','','g') in regexp_replace(coalesce(p.phone,''),'[^0-9]','','g'))>0 or position(regexp_replace(search_term,'[^0-9]','','g') in regexp_replace(coalesce(p.whatsapp,''),'[^0-9]','','g'))>0))
) and (case status_filter when 'active' then m.user_id is not null and not m.revoked and m.expires_at>now() when 'expiring' then m.user_id is not null and not m.revoked and m.expires_at>now() and m.expires_at<=now()+interval '7 days' when 'expired' then m.user_id is not null and not m.revoked and m.expires_at<=now() when 'revoked' then coalesce(m.revoked,false) when 'none' then m.user_id is null else true end));end;$$;
revoke all on function public.studio_admin_user_directory_v2(text,integer,text),public.studio_admin_user_count_v2(text,text) from public,anon;
grant execute on function public.studio_admin_user_directory_v2(text,integer,text),public.studio_admin_user_count_v2(text,text) to authenticated;