(async()=>{
  const api=window.APANAM_CATALOG,status=document.getElementById('adminStatus'),form=document.getElementById('adminSettings'),list=document.getElementById('adminTemplates');let data,limit=24,busy=false;
  const message=text=>{status.textContent=text};
  try{const saved=await api.draft();data=saved?api.catalog(saved):await api.load()}catch(error){try{data=await api.load()}catch(_){message('Catalog या browser storage नहीं खुला। App refresh करके कोशिश करें।');return}}
  const readyControls=document.createElement('div');readyControls.innerHTML='<label><input type="checkbox" name="externalPostersEnabled"> अनुमति वाले बाहरी तैयार posters की खोज चालू रखें</label><label>बाहरी posters छिपाएँ · स्रोत URL, हर लाइन एक<textarea name="externalPosterBlocklist" maxlength="12000" rows="4" placeholder="Gallery के स्रोत link का URL यहाँ डालें"></textarea></label>';form.append(readyControls);
  function settings(){for(const el of form.elements){if(!el.name)continue;if(el.type==='checkbox')el.checked=data.settings[el.name];else el.value=data.settings[el.name]??''}}
  async function save(next){const clean=api.catalog(next);await api.draft(clean);data=clean;updateStorage();return clean}
  async function updateStorage(){try{const estimate=await navigator.storage?.estimate?.();document.getElementById('adminStorage').textContent=`Catalog: ${(new Blob([JSON.stringify(data)]).size/1048576).toFixed(2)} MB · ${data.templates.length} templates${estimate?.quota?` · Browser उपयोग ${(estimate.usage/1048576).toFixed(1)} / ${(estimate.quota/1048576).toFixed(0)} MB`:''}`}catch(_){}}
  async function change(id,patch){try{const next=structuredClone(data),item=next.templates.find(t=>t.id===id);Object.assign(item,patch,{updatedAt:new Date().toISOString()});await save(next);message('Template draft सेव हुआ। सभी users तक पहुँचाने के लिए Publish करें।');render()}catch(error){message('बदलाव सेव नहीं हुआ। Catalog backup लें। '+error.message);render()}}
  function card(item){const box=document.createElement('article');box.className='studio-template-card';const frame=document.createElement('iframe');frame.sandbox='';frame.title=item.name+' preview';const p=item.project,scale=Math.min(210/p.width,120/p.height)*2;frame.srcdoc=`<style>body{margin:0;overflow:hidden}.stage{position:relative;transform-origin:top left;transform:scale(${scale});width:${p.width/2}px;height:${p.height/2}px;background:${p.bgColor}}.element{position:absolute;white-space:pre-wrap;box-sizing:border-box}.element img{width:100%;height:100%;object-fit:contain}</style><div class="stage">${api.safeHTML(p.html)}</div>`;
    const name=document.createElement('input');name.value=item.name;name.maxLength=120;name.setAttribute('aria-label','Template नाम');name.onchange=()=>change(item.id,{name:name.value.trim()||'मेरा Template'});
    const category=document.createElement('input');category.value=item.category;category.maxLength=80;category.setAttribute('aria-label','Template category');category.onchange=()=>change(item.id,{category:category.value.trim()||'General'});
    const schedule=document.createElement('div');
    const occasion=document.createElement('input');occasion.value=item.occasion||'';occasion.maxLength=100;occasion.placeholder='अवसर / विषय';occasion.setAttribute('aria-label','अवसर / विषय');occasion.onchange=()=>change(item.id,{occasion:occasion.value});
    const date=document.createElement('input');date.type='date';date.value=item.eventDate||'';date.setAttribute('aria-label','अवसर की तारीख');date.onchange=()=>change(item.id,{eventDate:date.value});
    const annual=document.createElement('label'),repeat=document.createElement('input');repeat.type='checkbox';repeat.checked=item.repeatYearly;repeat.setAttribute('aria-label','हर साल इसी तारीख');repeat.onchange=()=>change(item.id,{repeatYearly:repeat.checked});annual.append(repeat,document.createTextNode('हर साल इसी तारीख'));schedule.append(occasion,date,annual);
    const published=document.createElement('label');published.className='admin-published';const check=document.createElement('input');check.type='checkbox';check.checked=item.published;check.onchange=()=>change(item.id,{published:check.checked});published.append(check,document.createTextNode('User Library में दिखाएँ'));
    const actions=document.createElement('div');actions.className='studio-template-actions';for(const [label,run] of [['Editor में बदलें',async()=>{try{await save(data);location.href='index.html?admin-template='+encodeURIComponent(item.id)}catch(error){message('Editor draft सेव नहीं हुआ: '+error.message)}}],['JSON backup',()=>api.download(item.project,item.name.replace(/[^\p{L}\p{N}-]+/gu,'-')+'.json')],['Duplicate',async()=>{try{const next=structuredClone(data);next.templates.push({...structuredClone(item),id:crypto.randomUUID(),name:item.name+' Copy'});await save(next);render();message('Template की copy जुड़ी।')}catch(error){message('Copy सेव नहीं हुई: '+error.message)}}],['हटाएँ',async()=>{if(!confirm('यह template draft से हटाएँ? Live catalog Publish करने पर बदलेगा।'))return;try{const next=structuredClone(data);next.templates=next.templates.filter(t=>t.id!==item.id);await save(next);render();message('Draft से template हटाया।')}catch(error){message('Template नहीं हटाया गया: '+error.message)}}]]){const button=document.createElement('button');button.type='button';button.textContent=label;button.onclick=run;actions.append(button)}box.append(frame,name,category,schedule,published,actions);return box;
  }
  function render(){const term=document.getElementById('adminSearch').value.trim().toLocaleLowerCase(),items=data.templates.filter(t=>!term||(t.name+' '+t.category+' '+t.occasion).toLocaleLowerCase().includes(term));list.replaceChildren(...items.slice(0,limit).map(card));document.getElementById('adminMore').hidden=limit>=items.length;document.getElementById('adminCount').textContent=`कुल ${data.templates.length} · खोज में ${items.length} · ${data.templates.filter(t=>t.published).length} visible templates`;updateStorage()}
  form.onsubmit=async event=>{event.preventDefault();try{const next=structuredClone(data);for(const el of form.elements)if(el.name)next.settings[el.name]=el.type==='checkbox'?el.checked:el.value;await save(next);message('Settings draft सेव हुआ। Publish करने पर live app बदलेगा।')}catch(error){message('Settings सेव नहीं हुई: '+error.message)}};
  document.getElementById('adminSearch').oninput=()=>{limit=24;render()};document.getElementById('adminMore').onclick=()=>{limit+=24;render()};
  const files=document.getElementById('adminFiles');files.onchange=async()=>{if(busy)return;busy=true;files.disabled=true;let added=0;const failures=[];const next=structuredClone(data);for(const file of files.files){message(file.name+' जोड़ रहे हैं…');try{const value=file.name.toLowerCase().endsWith('.json')?JSON.parse(await file.text()):null;const items=value?.format==='apanam-studio-catalog'?api.catalog(value).templates:[{name:file.name.replace(/\.[^.]+$/,''),category:document.getElementById('uploadCategory').value.trim()||'General',project:value?api.project(value):await api.imageProject(file),published:true,occasion:document.getElementById('uploadOccasion').value,eventDate:document.getElementById('uploadEventDate').value,repeatYearly:document.getElementById('uploadRepeatYearly').checked}];for(const item of items){next.templates.push({...item,id:crypto.randomUUID(),updatedAt:new Date().toISOString()});added++}}catch(error){failures.push(file.name+': '+error.message)}}try{await save(next);render();message(`${added} templates draft में जुड़े। ${failures.join(' · ')} Publish के बाद users को मिलेंगे।`)}catch(error){message('Upload draft सेव नहीं हुआ। मूल files सुरक्षित रखें और catalog backup लें। '+error.message)}finally{busy=false;files.disabled=false;files.value=''}};
  document.getElementById('reloadPublished').onclick=async()=>{if(!confirm('Local draft को live catalog से बदलें? पहले backup ले लें।'))return;try{await save(await api.load());settings();render();message('Live catalog से नया draft खुला।')}catch(error){message('Live catalog नहीं खुला: '+error.message)}};
  document.getElementById('downloadCatalog').onclick=()=>{try{api.download(api.catalog(data),'studio-catalog.json');message('Catalog डाउनलोड हुआ। अब GitHub में upload और commit करें।')}catch(error){message(error.message)}};
  const importPicker=document.getElementById('importCatalog');importPicker.onchange=async()=>{const file=importPicker.files[0];if(!file)return;try{const incoming=api.catalog(JSON.parse(await file.text()));if(!confirm('मौजूदा draft को इस backup से बदलें?'))return;await save(incoming);settings();render();message('Admin backup वापस खुला।')}catch(error){message('Backup नहीं खुला; पुराना draft सुरक्षित है। '+error.message)}finally{importPicker.value=''}};
  const cloud=window.APANAM_CLOUD,cloudStatus=document.getElementById('studioCloudStatus'),login=document.getElementById('studioCloudLogin');let cloudBusy=false;
  async function cloudState(){try{const user=cloud?.user(),admin=user&&await cloud.isAdmin();for(const id of ['studioCloudLoad','studioCloudSave','studioCloudPublish'])document.getElementById(id).disabled=!admin||cloudBusy;document.getElementById('studioCloudLogout').hidden=!user;cloudStatus.textContent=admin?'Admin login तैयार है। Cloud draft Save या Publish करें।':user?'Login हुआ। इस account को अभी admin अधिकार नहीं मिला है।':'Cloud publishing के लिए login करें।';if(admin)await cloud.load('published');}catch(error){cloudStatus.textContent=error.message;}}
  login.onsubmit=async e=>{e.preventDefault();if(cloudBusy)return;cloudBusy=true;try{await cloud.signIn(login.elements.email.value.trim(),login.elements.password.value);login.elements.password.value='';}catch(error){cloudStatus.textContent='Login नहीं हुआ: '+error.message;cloudBusy=false;return;}cloudBusy=false;await cloudState();};
  document.getElementById('studioCloudSignup').onclick=async()=>{if(!login.reportValidity()||cloudBusy)return;cloudBusy=true;try{await cloud.signUp(login.elements.email.value.trim(),login.elements.password.value);login.elements.password.value='';cloudStatus.textContent='यदि account बनना उपलब्ध है तो confirmation email देखें। Verify करके Login करें। Admin अधिकार owner verification के बाद मिलेंगे।';}catch(error){cloudStatus.textContent='Account नहीं बना: '+error.message;}finally{cloudBusy=false;}};
  document.getElementById('studioCloudLogout').onclick=async()=>{try{await cloud.signOut();}catch(error){cloudStatus.textContent=error.message;}await cloudState();};
  document.getElementById('studioCloudLoad').onclick=async()=>{if(!confirm('Local draft को cloud draft से बदलें? पहले JSON backup लें।'))return;try{await save(await cloud.load('draft'));settings();render();message('Cloud draft इस device पर खुला।');}catch(error){cloudStatus.textContent=error.message;}};
  async function cloudWrite(publish){if(cloudBusy||busy)return;cloudBusy=true;for(const id of ['studioCloudSave','studioCloudPublish','studioCloudLoad'])document.getElementById(id).disabled=true;try{cloudStatus.textContent='Images और catalog cloud में सेव हो रहे हैं…';const next=await cloud.prepareAssets(data);await save(next);await cloud.save('draft',next);if(publish)await cloud.save('published',next);cloudStatus.textContent=publish?'Publish सफल। Users app refresh करके नए posters देख सकते हैं।':'Cloud draft सेव हुआ। Public library अभी नहीं बदली।';render();}catch(error){cloudStatus.textContent='Cloud publish/save पूरा नहीं हुआ: '+error.message+' Local draft/backup सुरक्षित रखें।';}finally{cloudBusy=false;const allowed=await cloud.isAdmin().catch(()=>false);for(const id of ['studioCloudLoad','studioCloudSave','studioCloudPublish'])document.getElementById(id).disabled=!allowed;}}
  document.getElementById('studioCloudSave').onclick=()=>cloudWrite(false);document.getElementById('studioCloudPublish').onclick=()=>{if(confirm('Visible posters और settings सभी users के लिए अभी प्रकाशित करें?'))cloudWrite(true);};
  const grantForm=document.getElementById('manualGrant'),grantButton=document.getElementById('manualGrantButton'),grantStatus=document.getElementById('manualGrantStatus');
  grantForm.elements.userId.addEventListener('input',()=>{document.getElementById('manualGrantSelected').textContent='User ID खुद बदली गई है; सही account की ID जाँचें।';});
  async function grantState(){const allowed=await cloud?.isAdmin().catch(()=>false);grantButton.disabled=!allowed;document.getElementById('manualMemberRefresh').disabled=!allowed;if(!allowed)document.getElementById('manualMemberList').replaceChildren();}
  document.addEventListener('apanam-cloud-session',grantState);grantState();
  grantForm.onsubmit=async e=>{e.preventDefault();grantButton.disabled=true;try{await cloud.grantManual(grantForm.elements.userId.value.trim(),grantForm.elements.days.value);document.dispatchEvent(new Event('apanam-membership-changed'));await members();grantStatus.textContent='मुफ्त manual membership सेव हुई। User अपना Membership page refresh करे।';}catch(error){grantStatus.textContent=error.message;}finally{await grantState();}};
  async function members(){const list=document.getElementById('manualMemberList');try{const rows=await cloud.listMemberships();list.replaceChildren();if(!rows.length){list.textContent='अभी कोई मुफ्त membership नहीं है।';return;}for(const row of rows){const box=document.createElement('article'),label=document.createElement('p');label.textContent=row.user_id+' · '+(row.revoked?'वापस लिया गया':Date.parse(row.expires_at)>Date.now()?'सक्रिय':'अवधि समाप्त')+' · '+new Date(row.expires_at).toLocaleDateString('hi-IN');const edit=document.createElement('button');edit.type='button';edit.textContent='अवधि बदलें / फिर चालू करें';edit.onclick=()=>{grantForm.elements.userId.value=row.user_id;document.getElementById('manualGrantSelected').textContent='चुना गया User ID: '+row.user_id;grantForm.elements.days.focus();};const revoke=document.createElement('button');revoke.type='button';revoke.textContent='मुफ्त Access वापस लें';revoke.disabled=row.revoked;revoke.onclick=async()=>{if(!confirm('इस user की मुफ्त manual membership वापस लें? फिर grant देकर चालू कर सकते हैं।'))return;revoke.disabled=true;try{await cloud.revokeManual(row.user_id);document.dispatchEvent(new Event('apanam-membership-changed'));await members();}catch(error){grantStatus.textContent=error.message;revoke.disabled=false;}};box.append(label,edit,revoke);list.append(box);}grantStatus.textContent='अधिकतम 100 memberships दिख रही हैं।';}catch(error){grantStatus.textContent=error.message;}}
  document.getElementById('manualMemberRefresh').onclick=members;
  if(cloud)cloudState();
  settings();render();message('Admin draft तैयार है। Cloud Publish के लिए अधिकृत admin login करें।');
})();

