(async()=>{
  const api=window.APANAM_CATALOG,status=document.getElementById('adminStatus'),form=document.getElementById('adminSettings'),list=document.getElementById('adminTemplates');let data,limit=24,busy=false;
  const message=text=>{status.textContent=text};
  try{const saved=await api.draft();data=saved?api.catalog(saved):await api.load()}catch(error){try{data=await api.load()}catch(_){message('Catalog या browser storage नहीं खुला। App refresh करके कोशिश करें।');return}}
  function settings(){for(const el of form.elements){if(!el.name)continue;if(el.type==='checkbox')el.checked=data.settings[el.name];else el.value=data.settings[el.name]??''}}
  async function save(next){const clean=api.catalog(next);await api.draft(clean);data=clean;updateStorage();return clean}
  async function updateStorage(){try{const estimate=await navigator.storage?.estimate?.();document.getElementById('adminStorage').textContent=`Catalog: ${(new Blob([JSON.stringify(data)]).size/1048576).toFixed(2)} MB · ${data.templates.length} templates${estimate?.quota?` · Browser उपयोग ${(estimate.usage/1048576).toFixed(1)} / ${(estimate.quota/1048576).toFixed(0)} MB`:''}`}catch(_){}}
  async function change(id,patch){try{const next=structuredClone(data),item=next.templates.find(t=>t.id===id);Object.assign(item,patch,{updatedAt:new Date().toISOString()});await save(next);message('Template draft सेव हुआ। सभी users तक पहुँचाने के लिए Publish करें।');render()}catch(error){message('बदलाव सेव नहीं हुआ। Catalog backup लें। '+error.message);render()}}
  function card(item){const box=document.createElement('article');box.className='studio-template-card';const frame=document.createElement('iframe');frame.sandbox='';frame.title=item.name+' preview';const p=item.project,scale=Math.min(210/p.width,120/p.height)*2;frame.srcdoc=`<style>body{margin:0;overflow:hidden}.stage{position:relative;transform-origin:top left;transform:scale(${scale});width:${p.width/2}px;height:${p.height/2}px;background:${p.bgColor}}.element{position:absolute;white-space:pre-wrap;box-sizing:border-box}.element img{width:100%;height:100%;object-fit:contain}</style><div class="stage">${api.safeHTML(p.html)}</div>`;
    const name=document.createElement('input');name.value=item.name;name.maxLength=120;name.setAttribute('aria-label','Template नाम');name.onchange=()=>change(item.id,{name:name.value.trim()||'मेरा Template'});
    const category=document.createElement('input');category.value=item.category;category.maxLength=80;category.setAttribute('aria-label','Template category');category.onchange=()=>change(item.id,{category:category.value.trim()||'General'});
    const schedule=document.createElement('div');
    const occasion=document.createElement('input');occasion.value=item.occasion||'';occasion.maxLength=100;occasion.placeholder='अवसर / विषय';occasion.setAttribute('aria-label','अवसर / विषय');occasion.onchange=()=>change(item.id,{occasion:occasion.value});
    const date=document.createElement('input');date.type='date';date.value=item.eventDate||'';date.setAttribute('aria-label','अवसर की तारीख');date.onchange=()=>change(item.id,{eventDate:date.value});
    const annual=document.createElement('label'),repeat=document.createElement('input');repeat.type='checkbox';repeat.checked=item.repeatYearly;repeat.setAttribute('aria-label','हर साल इसी तारीख');repeat.onchange=()=>change(item.id,{repeatYearly:repeat.checked});annual.append(repeat,document.createTextNode('हर साल इसी तारीख'));schedule.append(occasion,date,annual);
    const published=document.createElement('label');published.className='admin-published';const check=document.createElement('input');check.type='checkbox';check.checked=item.published;check.onchange=()=>change(item.id,{published:check.checked});published.append(check,document.createTextNode('User Library में दिखाएँ'));
    const actions=document.createElement('div');actions.className='studio-template-actions';for(const [label,run] of [['Editor में बदलें',async()=>{try{await save(data);location.href='index.html?admin-template='+encodeURIComponent(item.id)}catch(error){message('Editor draft सेव नहीं हुआ: '+error.message)}}],['JSON backup',()=>api.download(item.project,item.name.replace(/[^\p{L}\p{N}-]+/gu,'-')+'.json')],['Duplicate',async()=>{try{const next=structuredClone(data);next.templates.push({...structuredClone(item),id:crypto.randomUUID(),name:item.name+' Copy'});await save(next);render();message('Template की copy जुड़ी।')}catch(error){message('Copy सेव नहीं हुई: '+error.message)}}],['हटाएँ',async()=>{if(!confirm('यह template draft से हटाएँ? Live catalog Publish करने पर बदलेगा।'))return;try{const next=structuredClone(data);next.templates=next.templates.filter(t=>t.id!==item.id);await save(next);render();message('Draft से template हटाया।')}catch(error){message('Template नहीं हटाया गया: '+error.message)}}]]){const button=document.createElement('button');button.type='button';button.textContent=label;button.onclick=run;actions.append(button)}box.append(frame,name,category,schedule,published,actions);return box;
  }
  function render(){const term=document.getElementById('adminSearch').value.trim().toLocaleLowerCase(),items=data.templates.filter(t=>!term||(t.name+' '+t.category+' '+t.occasion).toLocaleLowerCase().includes(term));list.replaceChildren(...items.slice(0,limit).map(card));document.getElementById('adminMore').hidden=limit>=items.length;document.getElementById('adminCount').textContent=`कुल ${data.templates.length} · खोज में ${items.length} · ${data.templates.filter(t=>t.published).length} visible templates`;updateStorage()}
  form.onsubmit=async event=>{event.preventDefault();try{const next=structuredClone(data);for(const el of form.elements)if(el.name)next.settings[el.name]=el.type==='checkbox'?el.checked:el.value;await save(next);message('Settings draft सेव हुआ। Publish करने पर live app बदलेगा।')}catch(error){message('Settings सेव नहीं हुई: '+error.message)}};
  document.getElementById('adminSearch').oninput=()=>{limit=24;render()};document.getElementById('adminMore').onclick=()=>{limit+=24;render()};
  const files=document.getElementById('adminFiles');files.onchange=async()=>{if(busy)return;busy=true;files.disabled=true;let added=0;const failures=[];const next=structuredClone(data);for(const file of files.files){message(file.name+' जोड़ रहे हैं…');try{const value=file.name.toLowerCase().endsWith('.json')?JSON.parse(await file.text()):null;const items=value?.format==='apanam-studio-catalog'?api.catalog(value).templates:[{name:file.name.replace(/\.[^.]+$/,''),category:document.getElementById('uploadCategory').value.trim()||'General',project:value?api.project(value):await api.imageProject(file),published:true,occasion:document.getElementById('uploadOccasion').value,eventDate:document.getElementById('uploadEventDate').value,repeatYearly:document.getElementById('uploadRepeatYearly').checked}];for(const item of items){next.templates.push({...item,id:crypto.randomUUID(),updatedAt:new Date().toISOString()});added++}}catch(error){failures.push(file.name+': '+error.message)}}try{await save(next);render();message(`${added} templates draft में जुड़े। ${failures.join(' · ')} Publish के बाद users को मिलेंगे।`)}catch(error){message('Upload draft सेव नहीं हुआ। मूल files सुरक्षित रखें और catalog backup लें। '+error.message)}finally{busy=false;files.disabled=false;files.value=''}};
  document.getElementById('reloadPublished').onclick=async()=>{if(!confirm('Local draft को live catalog से बदलें? पहले backup ले लें।'))return;try{await save(await api.load());settings();render();message('Live catalog से नया draft खुला।')}catch(error){message('Live catalog नहीं खुला: '+error.message)}};
  document.getElementById('downloadCatalog').onclick=()=>{try{api.download(api.catalog(data),'studio-catalog.json');message('Catalog डाउनलोड हुआ। अब GitHub में upload और commit करें।')}catch(error){message(error.message)}};
  const importPicker=document.getElementById('importCatalog');importPicker.onchange=async()=>{const file=importPicker.files[0];if(!file)return;try{const incoming=api.catalog(JSON.parse(await file.text()));if(!confirm('मौजूदा draft को इस backup से बदलें?'))return;await save(incoming);settings();render();message('Admin backup वापस खुला।')}catch(error){message('Backup नहीं खुला; पुराना draft सुरक्षित है। '+error.message)}finally{importPicker.value=''}};
  settings();render();message('Admin draft तैयार है। Publication के लिए GitHub owner account इस्तेमाल करें।');
})();
