(async()=>{
  const api=window.APANAM_CATALOG,stage=document.getElementById('stage'),header=document.querySelector('body>header');if(!api||!header)return;
  let data;try{data=await api.load()}catch(error){console.warn(error);data=api.catalog({format:'apanam-studio-catalog',settings:{},templates:[]})}
  const settings=data.settings;document.title=settings.appName+(stage?' · Poster':' · Video');
  const colors=document.createElement('style');colors.textContent=`#export,.studio-library button{background:${settings.primaryColor};color:#fff}.studio-library-link{color:${settings.primaryColor}}`;document.head.append(colors);
  const footer=document.createElement('footer');footer.className='studio-catalog-footer';const admin=document.createElement('a');admin.href='admin.html';admin.textContent='Admin Workspace';footer.append(admin);if(settings.contact){const support=document.createElement('span');support.textContent=settings.contact;footer.append(support)}document.body.append(footer);
  if(settings.announcement){const notice=document.createElement('div');notice.className='studio-announcement';notice.textContent=settings.announcement;header.after(notice)}
  if(settings.maintenance||stage&&!settings.posterEnabled||!stage&&!settings.videoEnabled){const notice=document.createElement('section');notice.className='studio-maintenance';const h=document.createElement('h2');h.textContent=settings.maintenance?'अभी रखरखाव चल रहा है':'यह editor अभी उपलब्ध नहीं है';const p=document.createElement('p');p.textContent=settings.contact||'कृपया कुछ समय बाद दोबारा खोलें।';notice.append(h,p);document.querySelector('main')?.replaceWith(notice);return}
  if(!stage)return;
  const link=document.createElement('button');link.id='studioTemplateLibrary';link.type='button';link.textContent='Poster / Templates';(header.querySelector('.header-utility-actions')||header.querySelector('.actions')||header).prepend(link);
  const overlay=document.createElement('div');overlay.className='studio-library-overlay';overlay.hidden=true;overlay.innerHTML='<section class="studio-library" role="dialog" aria-modal="true" aria-labelledby="studioLibraryTitle"><header><h2 id="studioLibraryTitle">Poster / Template Library</h2><button type="button" class="studio-library-close" data-close>✕ बंद करें</button></header><p>Template खोलकर अपना text, photo, logo और रंग बदलें। JPG/PNG एक photo layer है; उसके पुराने text अलग-अलग edit नहीं होते। Editable JSON में सभी layers बदल सकते हैं।</p><label class="studio-upload">अपना poster या editable JSON जोड़ें <input id="studioUserUpload" type="file" multiple accept="image/png,image/jpeg,image/webp,image/gif,.json,application/json"></label><div class="studio-library-tools"><input type="search" id="studioTemplateSearch" placeholder="Template खोजें" aria-label="Template खोजें"><select id="studioTemplateCategory" aria-label="Category"><option value="">सभी categories</option></select></div><p role="status" aria-live="polite"></p><div class="studio-library-grid"></div><button type="button" id="studioMoreTemplates">और दिखाएँ</button><p class="studio-local-label">अपना upload इसी device का draft है। सभी users के catalog में केवल admin द्वारा प्रकाशित templates दिखेंगे।</p></section>';document.body.append(overlay);
  const status=overlay.querySelector('[role=status]'),grid=overlay.querySelector('.studio-library-grid'),search=overlay.querySelector('#studioTemplateSearch'),category=overlay.querySelector('#studioTemplateCategory');let local=[],limit=24;
  function openProject(project){try{if(stage.querySelector('.element')&&!confirm('खुला poster बदल जाएगा। पहले Save/backup कर लें। Template खोलें?'))return;if(!window.APANAM_PROJECT.restore(api.project(project)))throw Error('Template नहीं खुला।');window.APANAM_PROJECT.save();overlay.hidden=true;document.getElementById('zoomFit')?.click()}catch(error){status.textContent=error.message}}
  function card(item){const box=document.createElement('article');box.className='studio-template-card';const frame=document.createElement('iframe');frame.sandbox='';frame.title=item.name+' preview';const p=item.project,scale=Math.min(200/p.width,160/p.height)*2;frame.srcdoc=`<style>body{margin:0;overflow:hidden}.stage{position:relative;transform-origin:top left;transform:scale(${scale});width:${p.width/2}px;height:${p.height/2}px;background:${p.transparent?'transparent':p.bgColor}}.element{position:absolute;box-sizing:border-box;white-space:pre-wrap}.element img{width:100%;height:100%;object-fit:contain}.handle,.rotateHandle{display:none}</style><div class="stage">${api.safeHTML(p.html)}</div>`;const title=document.createElement('strong');title.textContent=item.name;const note=document.createElement('small');note.textContent=item.category+(item.local?' · अपना upload':'');const use=document.createElement('button');use.type='button';use.textContent='खोलें और edit करें';use.onclick=()=>openProject(p);box.append(frame,title,note,use);return box}
  function render(){const term=search.value.trim().toLocaleLowerCase(),all=[...local,...data.templates.filter(t=>t.published)],filtered=all.filter(t=>(!category.value||t.category===category.value)&&(!term||(t.name+' '+t.category).toLocaleLowerCase().includes(term)));grid.replaceChildren(...filtered.slice(0,limit).map(card));overlay.querySelector('#studioMoreTemplates').hidden=limit>=filtered.length;status.textContent=`${filtered.length} templates · ${Math.min(limit,filtered.length)} दिख रहे हैं`;}
  for(const name of new Set(data.templates.filter(t=>t.published).map(t=>t.category))){const option=new Option(name,name);category.add(option)}
  search.oninput=category.onchange=()=>{limit=24;render()};overlay.querySelector('#studioMoreTemplates').onclick=()=>{limit+=24;render()};link.onclick=()=>{overlay.hidden=false;render()};overlay.querySelector('[data-close]').onclick=()=>{overlay.hidden=true;link.focus()};document.addEventListener('keydown',e=>{if(e.key==='Escape')overlay.hidden=true});
  const picker=overlay.querySelector('#studioUserUpload');picker.disabled=!settings.uploadsEnabled;picker.onchange=async()=>{let added=0;const failed=[];for(const file of picker.files){try{if(file.name.toLowerCase().endsWith('.json')){const value=JSON.parse(await file.text());const items=value.format==='apanam-studio-catalog'?api.catalog(value).templates.map(t=>({...t,local:true})): [{id:crypto.randomUUID(),name:file.name,category:'अपना Upload',project:api.project(value),local:true}];local.push(...items);added+=items.length}else{local.push({id:crypto.randomUUID(),name:file.name,category:'अपना Upload',project:await api.imageProject(file),local:true});added++}}catch(error){failed.push(file.name+': '+error.message)}}picker.value='';render();status.textContent=`${added} poster/templates जुड़े। ${failed.join(' · ')}`};
  const editing=new URLSearchParams(location.search).get('admin-template');if(editing){try{const draft=api.catalog(await api.draft()),item=draft.templates.find(t=>t.id===editing);if(!item)throw Error('Admin template draft नहीं मिला।');window.APANAM_PROJECT.restore(item.project);const save=document.createElement('button');save.type='button';save.textContent='Template बदलाव admin में सेव करें';header.after(save);save.onclick=async()=>{try{const current=api.catalog(await api.draft()),template=current.templates.find(t=>t.id===editing);if(!template)throw Error('Template हट चुका है।');template.project=api.project(window.APANAM_PROJECT.snapshot());template.updatedAt=new Date().toISOString();await api.draft(current);location.href='admin.html'}catch(error){alert('Template सेव नहीं हुआ: '+error.message)}}}catch(error){alert(error.message)}}
})();
