(()=>{'use strict';if(document.getElementById('studioSupportOpen'))return;const header=document.querySelector('body>header')||document.querySelector('main');if(!header)return;
const open=document.createElement('button');open.id='studioSupportOpen';open.type='button';open.textContent='💬 AI Chat';open.title='AI से सवाल पूछें';(header.querySelector('.header-utility-actions')||header).append(open);
const dialog=document.createElement('dialog');dialog.className='studio-support-dialog';dialog.id='studioSupportDialog';dialog.innerHTML='<header><h2>APANAMai AI Chat</h2><button type="button" data-support-close aria-label="सहायता बंद करें">×</button></header><div class="support-body"><p>कहानी, पढ़ाई, अनुवाद, लेखन और सामान्य सवाल पूछें। App सहायता के shortcuts नीचे हैं। यह chat आपके account, bank payment या support ticket की निजी स्थिति नहीं देखता। Password, OTP, card और API key न लिखें।</p><div class="support-suggestions"><button type="button" data-topic="backup">Backup</button><button type="button" data-topic="voice">आवाज़</button><button type="button" data-topic="export">Export समस्या</button><button type="button" data-topic="autopay">AutoPay</button><button type="button" data-topic="text">Text Edit</button></div><div class="support-chat" role="log" aria-live="polite" aria-label="सहायता बातचीत"></div><form class="support-form"><label for="supportQuestion">अपना सवाल लिखें</label><textarea id="supportQuestion" maxlength="1000" rows="2" placeholder="जैसे: बच्चों के लिए हिंदी में छोटी कहानी लिखें" required></textarea><div id="supportAiOptions" hidden><label class="support-ai-controls"><input type="checkbox" id="supportAiConsent"> मैं अपना सवाल और हाल की बातचीत Sarvam AI को भेजने की अनुमति देता हूँ। निजी जानकारी न लिखें।</label></div><button type="submit" id="supportAsk">जवाब पाएँ</button></form><p id="supportStatus" role="status"></p><div class="support-footer"><a href="APP-USER-GUIDE.md">पूरा guide</a><a href="mailto:apanambusiness@gmail.com">Support email</a><button type="button" id="supportClear">बातचीत साफ करें</button></div></div>';document.body.append(dialog);
const chat=dialog.querySelector('.support-chat'),form=dialog.querySelector('form'),input=dialog.querySelector('textarea'),status=dialog.querySelector('#supportStatus'),ask=dialog.querySelector('#supportAsk'),api=window.APANAM_CLOUD;let history=[],knowledge=[],busy=false,epoch=0,aiEnabled=false,loaded=false;
const normalize=s=>s.toLowerCase().normalize('NFKC').replace(/[?।!.,]/g,' ').replace(/\s+/g,' ').trim();function add(text,kind='assistant',link){const p=document.createElement('p');p.className='support-message '+kind;p.textContent=text;chat.append(p);if(link){const a=document.createElement('a');a.href=link;a.textContent='संबंधित विकल्प खोलें →';chat.append(a);}while(chat.children.length>40)chat.firstElementChild.remove();chat.scrollTop=chat.scrollHeight;}
async function load(){const n=epoch,owner=api?.user()?.id;if(!loaded){const r=await fetch('studio-support-knowledge.json');if(!r.ok)throw Error('Guide नहीं खुला। Internet के साथ app refresh करें।');knowledge=await r.json();loaded=true;}aiEnabled=false;if(api?.user()&&api.supportRequest){try{const config=await api.supportRequest('status');if(n!==epoch||owner!==api.user()?.id)return;aiEnabled=!!config.enabled;status.textContent=aiEnabled?'AI Chat तैयार · प्रति account अधिकतम 10 सवाल/दिन · बचे '+config.remaining+'। Wallet से कटौती नहीं।':'AI Chat अभी उपलब्ध नहीं है। App सहायता shortcuts चलेंगे।';}catch{status.textContent='AI की उपलब्धता नहीं जाँची जा सकी। App सहायता shortcuts चलेंगे।';}}else status.textContent='AI Chat के लिए Membership में Login करें। App सहायता बिना login चलेगी।';if(n!==epoch)return;dialog.querySelector('#supportAiOptions').hidden=!aiEnabled;}
function best(question){const q=normalize(question);return knowledge.map(r=>({r,score:r.keywords.reduce((n,k)=>n+(q.includes(normalize(k))?Math.pow(normalize(k).split(' ').length,2):0),0)})).sort((a,b)=>b.score-a.score)[0];}
async function answer(question,topic){if(busy)return;busy=true;ask.disabled=true;const n=epoch,owner=api?.user()?.id;try{if(!loaded)await load();if(n!==epoch)return;
if(topic){add(question,'user');const r=knowledge.find(r=>r.id===topic);if(r)add(r.answer,'assistant',r.link);return;}
if(!aiEnabled){const result=best(question);add(question,'user');if(result?.score>0)add(result.r.answer,'assistant',result.r.link);else add('सामान्य सवाल का AI उत्तर अभी उपलब्ध नहीं है। Membership में Login करें और chat दोबारा खोलें। App सहायता के shortcuts इस्तेमाल कर सकते हैं।');input.value='';return;}
if(!dialog.querySelector('#supportAiConsent').checked){status.textContent='पहले सवाल और बातचीत Sarvam को भेजने की अनुमति चुनें।';return;}
let context=history.slice(-6);while(new TextEncoder().encode(JSON.stringify(context)).length>6000)context=context.slice(2);
add(question,'user');input.value='';status.textContent='AI जवाब तैयार कर रहा है…';const value=await api.supportRequest('ask',{question,history:context,consent:true,consent_version:'chat-context-sarvam-v2',request_id:crypto.randomUUID()});if(n!==epoch||owner!==api.user()?.id)return;add(value.answer);history.push({role:'user',content:question},{role:'assistant',content:value.answer});history=history.slice(-6);status.textContent=value.truncated?'उत्तर की लंबाई सीमा पूरी हुई। आगे के लिए छोटा अगला सवाल पूछें।':'AI उत्तर की जाँच करें। अगला सवाल इसी बातचीत में पूछ सकते हैं।';
}catch(e){if(n===epoch){add(e.message);status.textContent='उत्तर नहीं मिला। कोई automatic retry नहीं भेजी गई।';}}finally{busy=false;ask.disabled=false;}}
const menu=document.getElementById('studioAccountMenu');if(menu){const entry=document.createElement('button');entry.id='studioSupportMenuOpen';entry.type='button';entry.textContent='💬 AI Chat';entry.onclick=()=>open.click();menu.append(entry);}
open.onclick=async()=>{dialog.showModal();input.focus();try{await load();}catch(e){status.textContent=e.message;}};dialog.querySelector('[data-support-close]').onclick=()=>{dialog.close();open.focus();};dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});form.onsubmit=e=>{e.preventDefault();const q=input.value.trim();if(!q)return;if(/(sb_secret_|sk_[a-z0-9]|password\s*[:=]|otp\s*[:=]|\b\d{16}\b)/i.test(q)){status.textContent='निजी credentials हटाकर केवल सवाल लिखें।';return;}answer(q);};for(const b of dialog.querySelectorAll('[data-topic]'))b.onclick=()=>answer(b.textContent,b.dataset.topic);dialog.querySelector('#supportClear').onclick=()=>{epoch++;history=[];chat.replaceChildren();input.value='';dialog.querySelector('#supportAiConsent').checked=false;status.textContent='बातचीत साफ हुई। यह browser में स्थायी रूप से सेव नहीं की गई।';};document.addEventListener('apanam-cloud-session',()=>{epoch++;history=[];aiEnabled=false;chat.replaceChildren();input.value='';dialog.querySelector('#supportAiConsent').checked=false;dialog.querySelector('#supportAiOptions').hidden=true;status.textContent='Account बदला। बातचीत साफ कर दी गई।';});window.APANAM_SUPPORT={match:q=>best(q),open:()=>open.click()};
})();
