(async()=>{
  const api=window.APANAM_CATALOG,stage=document.getElementById('stage'),header=document.querySelector('body>header');if(!api||!header)return;
  let data;try{data=await api.load()}catch(error){console.warn(error);data=api.catalog({format:'apanam-studio-catalog',settings:{},templates:[]})}
  const settings=data.settings;document.title=settings.appName+(stage?' · Poster':' · Video');
  const colors=document.createElement('style');colors.textContent=`#export,.studio-library button{background:${settings.primaryColor};color:#fff}.studio-library-link{color:${settings.primaryColor}}`;document.head.append(colors);
  const footer=document.createElement('footer');footer.className='studio-catalog-footer';const admin=document.createElement('a');admin.href='admin.html';admin.textContent='Admin Workspace';footer.append(admin);if(settings.contact){const support=document.createElement('span');support.textContent=settings.contact;footer.append(support)}document.body.append(footer);
  if(settings.announcement){const notice=document.createElement('div');notice.className='studio-announcement';notice.textContent=settings.announcement;header.after(notice)}
  if(settings.maintenance||stage&&!settings.posterEnabled||!stage&&!settings.videoEnabled){const notice=document.createElement('section');notice.className='studio-maintenance';const h=document.createElement('h2');h.textContent=settings.maintenance?'अभी रखरखाव चल रहा है':'यह editor अभी उपलब्ध नहीं है';const p=document.createElement('p');p.textContent=settings.contact||'कृपया कुछ समय बाद दोबारा खोलें।';notice.append(h,p);document.querySelector('main')?.replaceWith(notice);return}
  if(!stage)return;
  const link=document.createElement('button');link.id='studioTemplateLibrary';link.type='button';link.textContent='Poster / Templates';(document.getElementById('studioMobilePrimaryActions')||header.querySelector('.actions')||header).prepend(link);window.APANAM_PLACE_ACCESS?.();const membership=document.createElement('a');membership.href='membership.html';membership.textContent='Membership';membership.className='studio-membership-link';(document.getElementById('studioMobilePrimaryActions')||header.querySelector('.actions')||header).append(membership);
  const overlay=document.createElement('div');overlay.className='studio-library-overlay';overlay.hidden=true;overlay.innerHTML='<section class="studio-library" role="dialog" aria-modal="true" aria-labelledby="studioLibraryTitle"><header><h2 id="studioLibraryTitle">Poster / Template Library</h2><button type="button" class="studio-library-close" data-close>✕ बंद करें</button></header><p>पहले design चुनें, फिर अपना text, photo और पहचान बदलें।</p><details class="studio-edit-guide"><summary>कैसे edit करें? · Mobile और Desktop</summary><ol><li><strong>Design चुनें:</strong> category या search से poster खोजें और “खोलें और edit करें” दबाएँ। “अपना नाम / Logo लगाएँ” से तय जगह पर अपनी पहचान भरें या अलग नामपट्टी जोड़ें।</li><li><strong>Text / Photo बदलें:</strong> Desktop पर दाईं ओर Layers में text लिखें या photo के लिए Choose File चुनें। Mobile पर नीचे “Layers” दबाएँ; उसी सूची में text और photo बदलें। Photo और logo अलग हैं—जिस layer को बदलना है, उसी का file विकल्प चुनें।</li><li><strong>जगह और आकार:</strong> “Canvas में चुनें” से layer चुनें, फिर canvas पर drag करें और किनारों से आकार बदलें। गलती हो तो Undo दबाएँ।</li><li><strong>काम सुरक्षित रखें:</strong> Save करें; Download से फ़ाइल निकालें और Share से भेजें। दूसरे device पर खोलने के लिए Login करके “मेरे Cloud Posters” में Save करें।</li></ol><p><strong>JPG / PNG:</strong> ये एक photo होती हैं; छपा text और वस्तुएँ अपने-आप अलग layers नहीं बनते। Photo चुनकर “छपा Text बदलें” या “फोटो का हिस्सा चुनें” इस्तेमाल करें। OCR और background repair का परिणाम photo की स्पष्टता पर निर्भर है। Editable templates में text और photo पहले से अलग हैं।</p></details><label class="studio-upload">अपना poster या editable JSON जोड़ें <input id="studioUserUpload" type="file" multiple accept="image/png,image/jpeg,image/webp,image/gif,.json,application/json"></label><div class="studio-library-tools"><input type="search" id="studioTemplateSearch" placeholder="Template खोजें" aria-label="Template खोजें"><select id="studioTemplateCategory" aria-label="Category"><option value="">सभी categories</option></select></div><div class="studio-library-tools"><select id="studioDateMode" aria-label="अवसर के posters"><option value="all">सभी posters</option><option value="day">तारीख के posters</option></select><input id="studioEventDate" type="date" aria-label="Poster तारीख"><button type="button" id="studioToday">आज के posters</button><button type="button" id="studioBusinessProfile">मेरा नाम / संस्था / Logo</button></div><p role="status" aria-live="polite"></p><div class="studio-library-grid"></div><button type="button" id="studioMoreTemplates">और दिखाएँ</button><p class="studio-local-label">अपना upload इसी device का draft है। सभी users के catalog में केवल admin द्वारा प्रकाशित templates दिखेंगे।</p></section>';document.body.append(overlay);
  const status=overlay.querySelector('[role=status]'),grid=overlay.querySelector('.studio-library-grid'),search=overlay.querySelector('#studioTemplateSearch'),category=overlay.querySelector('#studioTemplateCategory');let local=[],limit=24;
  function uploadedTemplates(write){return new Promise((resolve,reject)=>{const r=indexedDB.open('apanam-user-uploads',1);r.onupgradeneeded=()=>r.result.createObjectStore('templates',{keyPath:'id'});r.onerror=()=>reject(r.error);r.onsuccess=()=>{const db=r.result,t=db.transaction('templates',write?'readwrite':'readonly'),store=t.objectStore('templates');let result=[];if(write){for(const item of write)store.put(item);}else{const q=store.getAll();q.onsuccess=()=>{result=q.result;};}t.oncomplete=()=>{db.close();resolve(result);};t.onerror=t.onabort=()=>{db.close();reject(t.error||Error('Upload save नहीं हुआ'));};};});}
  function openProject(project,personalize=false){try{if(stage.querySelector('.element')&&!confirm('खुला poster बदल जाएगा। पहले Save/backup कर लें। Template खोलें?'))return;if(!window.APANAM_PROJECT.restore(api.project(project)))throw Error('Template नहीं खुला।');window.APANAM_PROJECT.save();overlay.hidden=true;document.getElementById('zoomFit')?.click();window.APANAM_TEMPLATE_CONTENT?.refresh();if(personalize)window.APANAM_DAILY_PROFILE?.open()}catch(error){status.textContent=error.message}}
  function card(item){const box=document.createElement('article');box.className='studio-template-card';const frame=document.createElement('iframe');frame.sandbox='';frame.title=item.name+' preview';const p=item.project,scale=Math.min(200/p.width,160/p.height)*2;frame.srcdoc=`<style>body{margin:0;overflow:hidden}.stage{position:relative;transform-origin:top left;transform:scale(${scale});width:${p.width/2}px;height:${p.height/2}px;background:${p.transparent?'transparent':p.bgColor}}.element{position:absolute;box-sizing:border-box;white-space:pre-wrap}.element img{width:100%;height:100%;object-fit:contain}.handle,.rotateHandle{display:none}</style><div class="stage">${api.safeHTML(p.html)}</div>`;const content=document.createElement('template');content.innerHTML=api.safeHTML(p.html);const textCount=content.content.querySelectorAll('[data-text],.element.text').length,photoCount=content.content.querySelectorAll('img').length,elementCount=content.content.querySelectorAll('.element').length;const capability=document.createElement('small');capability.className='studio-template-capability';capability.textContent=(textCount||photoCount>1||elementCount>1)?`अलग editable हिस्से · ${textCount} Text · ${photoCount} Photo`:photoCount===1?'एक image · अंदर के हिस्से Area edit से चुनें':'Canvas design · Layers में हिस्से चुनें';const title=document.createElement('strong');title.textContent=item.name;const note=document.createElement('small');note.textContent=item.category+(item.occasion?' · '+item.occasion:'')+(item.eventDate?' · '+item.eventDate:'')+(item.local?' · अपना upload':'');const use=document.createElement('button');use.type='button';use.textContent='खोलें और edit करें';use.onclick=()=>openProject(p);const personalize=document.createElement("button");personalize.type="button";personalize.textContent="अपना नाम / Logo लगाएँ";personalize.onclick=()=>openProject(p,true);box.append(frame,title,note,capability,use,personalize);return box}
  const dateMode=overlay.querySelector('#studioDateMode'),eventDate=overlay.querySelector('#studioEventDate');eventDate.value=api.today();dateMode.onchange=eventDate.oninput=eventDate.onchange=()=>{limit=24;render()};overlay.querySelector('#studioToday').onclick=()=>{eventDate.value=api.today();dateMode.value='day';limit=24;render()};overlay.querySelector('#studioBusinessProfile').onclick=()=>window.APANAM_DAILY_PROFILE?.open();
  function render(){const term=search.value.trim().toLocaleLowerCase(),all=[...local,...data.templates.filter(t=>t.published)],filtered=all.filter(t=>(dateMode.value!=='day'||api.onDate(t,eventDate.value))&&(!category.value||t.category===category.value)&&(!term||(t.name+' '+t.category+' '+(t.occasion||'')).toLocaleLowerCase().includes(term)));grid.replaceChildren(...filtered.slice(0,limit).map(card));overlay.querySelector('#studioMoreTemplates').hidden=limit>=filtered.length;status.textContent=`${filtered.length} templates · ${Math.min(limit,filtered.length)} दिख रहे हैं${!filtered.length&&dateMode.value==='day'?' · इस तारीख का poster अभी प्रकाशित नहीं है। सभी posters चुन सकते हैं।':''}`;}
  for(const name of new Set(data.templates.filter(t=>t.published).map(t=>t.category))){const option=new Option(name,name);category.add(option)}
  search.oninput=category.onchange=()=>{limit=24;render()};overlay.querySelector('#studioMoreTemplates').onclick=()=>{limit+=24;render()};link.onclick=()=>{window.APANAM_TEMPLATE_CONTENT?.refresh();overlay.hidden=false;render()};overlay.querySelector('[data-close]').onclick=()=>{overlay.hidden=true;link.focus()};document.dispatchEvent(new Event('apanam-library-ready'));document.addEventListener('keydown',e=>{if(e.key==='Escape')overlay.hidden=true});
  try{local=await uploadedTemplates();}catch(error){console.warn('Uploaded templates unavailable',error);}
  const picker=overlay.querySelector('#studioUserUpload');picker.disabled=!settings.uploadsEnabled;picker.onchange=async()=>{let added=0;const failed=[];for(const file of picker.files){try{if(file.name.toLowerCase().endsWith('.json')){const value=JSON.parse(await file.text());const items=value.format==='apanam-studio-catalog'?api.catalog(value).templates.map(t=>({...t,local:true})): [{id:crypto.randomUUID(),name:file.name,category:'अपना Upload',project:api.project(value),local:true}];local.push(...items);added+=items.length}else{local.push({id:crypto.randomUUID(),name:file.name,category:'अपना Upload',project:await api.imageProject(file),local:true});added++}}catch(error){failed.push(file.name+': '+error.message)}}try{await uploadedTemplates(local);}catch(error){failed.push('इस बार upload browser में सुरक्षित नहीं हुआ: '+error.message);}picker.value='';render();status.textContent=`${added} poster/templates जुड़े। ${failed.join(' · ')}`};
  const editing=new URLSearchParams(location.search).get('admin-template');if(editing){try{const draft=api.catalog(await api.draft()),item=draft.templates.find(t=>t.id===editing);if(!item)throw Error('Admin template draft नहीं मिला।');window.APANAM_PROJECT.restore(item.project);window.APANAM_TEMPLATE_CONTENT?.refresh();const save=document.createElement('button');save.type='button';save.textContent='Template बदलाव admin में सेव करें';header.after(save);save.onclick=async()=>{try{const current=api.catalog(await api.draft()),template=current.templates.find(t=>t.id===editing);if(!template)throw Error('Template हट चुका है।');template.project=api.project(window.APANAM_PROJECT.snapshot());template.updatedAt=new Date().toISOString();await api.draft(current);location.href='admin.html'}catch(error){alert('Template सेव नहीं हुआ: '+error.message)}}}catch(error){alert(error.message)}}
})();

