(()=>{'use strict';
const config=window.APANAM_CLOUD_CONFIG;if(!config?.url||!config?.key)return;
const KEY='apanam-studio-cloud-session-v1';let session=null,refreshing=null;const versions={};
try{session=JSON.parse(sessionStorage.getItem(KEY)||'null')}catch{}
function remember(value){session=value;try{if(value)sessionStorage.setItem(KEY,JSON.stringify(value));else sessionStorage.removeItem(KEY)}catch{}document.dispatchEvent(new Event('apanam-cloud-session'));}
async function request(path,options={},token){const headers={apikey:config.key,...options.headers};if(token)headers.Authorization='Bearer '+token;const response=await fetch(config.url+path,{...options,headers,signal:options.signal||AbortSignal.timeout(12000)});let data;try{data=await response.json()}catch{data=null}if(!response.ok)throw Error(data?.msg||data?.message||data?.error_description||data?.error||'Cloud request असफल ('+response.status+')');return data;}
async function access(){if(!session)throw Error('पहले login करें।');if(session.expires_at*1000>Date.now()+60000)return session.access_token;if(!refreshing)refreshing=request('/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})}).then(value=>{remember(value);return value.access_token}).catch(error=>{remember(null);throw error}).finally(()=>refreshing=null);return refreshing;}
async function signIn(email,password){const value=await request('/auth/v1/token?grant_type=password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});remember(value);return value.user;}
async function signUp(email,password){return request('/auth/v1/signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});}
async function signOut(){try{if(session)await request('/auth/v1/logout',{method:'POST'},await access())}finally{remember(null)}}
async function isAdmin(){if(!session)return false;const token=await access(),user=await request('/auth/v1/user',{},token);const rows=await request('/rest/v1/studio_admins?select=user_id&user_id=eq.'+encodeURIComponent(user.id),{},token);return rows?.length===1;}
async function load(id='published'){const rows=await request('/rest/v1/studio_catalogs?select=payload,version&id=eq.'+id,{signal:AbortSignal.timeout(id==='published'?3500:12000)},id==='draft'?await access():undefined);if(!rows?.[0])throw Error('Cloud catalog उपलब्ध नहीं है।');versions[id]=rows[0].version;return window.APANAM_CATALOG.catalog(rows[0].payload);}
async function save(id,catalog){if(!await isAdmin())throw Error('इस account को admin अधिकार नहीं मिला है।');if(!versions[id])await load(id);const payload=window.APANAM_CATALOG.catalog(catalog);if(id==='published')payload.templates=payload.templates.filter(t=>t.published);if(new Blob([JSON.stringify(payload)]).size>10*1024*1024)throw Error('Catalog 10 MB से बड़ा है। बड़े image को छोटा करें।');const token=await access();const rows=await request('/rest/v1/studio_catalogs?id=eq.'+id+'&version=eq.'+versions[id],{method:'PATCH',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({payload,version:versions[id]+1,updated_at:new Date().toISOString()})},token);if(!rows?.[0])throw Error('दूसरे admin ने catalog बदला है। Cloud से नया draft लें; आपका local backup सुरक्षित है।');versions[id]=rows[0].version;return payload;}
async function prepareAssets(catalog){
 const clean=window.APANAM_CATALOG.catalog(catalog),sources=new Map(),boxes=[];
 for(const item of clean.templates){const box=document.createElement('div');box.innerHTML=item.project.html;boxes.push([item,box]);for(const img of box.querySelectorAll('img'))if(img.src.startsWith('data:image/'))sources.set(img.src,null);if(item.project.bgImage.startsWith('data:image/'))sources.set(item.project.bgImage,null);}
 // Validate the complete batch before any upload consumes storage.
 for(const src of sources.keys()){const blob=await (await fetch(src)).blob();if(!['image/png','image/jpeg','image/webp','image/gif'].includes(blob.type))throw Error('PNG/JPG/WebP/GIF image चुनें।');if(blob.size>2*1024*1024)throw Error('हर poster/photo 2 MB से छोटा रखें।');sources.set(src,blob);}
 const urls=new Map();for(const [src,blob] of sources){const extension=blob.type==='image/jpeg'?'jpg':blob.type.split('/')[1],name=crypto.randomUUID()+'.'+extension;await request('/storage/v1/object/studio-posters/'+name,{method:'POST',headers:{'Content-Type':blob.type},body:blob},await access());urls.set(src,config.url+'/storage/v1/object/public/studio-posters/'+name);}
 for(const [item,box] of boxes){for(const img of box.querySelectorAll('img'))if(urls.has(img.src))img.src=urls.get(img.src);item.project.html=box.innerHTML;if(urls.has(item.project.bgImage))item.project.bgImage=urls.get(item.project.bgImage);}return clean;
}
async function membership(){const user=await request('/auth/v1/user',{},await access());const rows=await request('/rest/v1/studio_memberships?select=plan,expires_at&user_id=eq.'+encodeURIComponent(user.id),{},await access());return rows?.[0]||null;}
async function grantManual(userId,days){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(userId))throw Error('सही user ID चुनें।');days=Number(days);if(!Number.isInteger(days)||days<1||days>365)throw Error('1–365 दिन चुनें।');if(!await isAdmin())throw Error('Admin login जरूरी है।');return request('/rest/v1/studio_memberships?on_conflict=user_id',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({user_id:userId,plan:'manual_complimentary',expires_at:new Date(Date.now()+days*86400000).toISOString(),granted_by:session.user.id})},await access());}
window.APANAM_CLOUD={membership,grantManual,signIn,signUp,signOut,isAdmin,load,save,prepareAssets,user:()=>session?.user||null};
})();
