(()=>{'use strict';
function init(){const stage=document.getElementById('stage'),workspace=document.querySelector('.workspace'),aside=document.querySelector('main>aside:not(.right)'),bar=document.getElementById('templateCanvasActions'),list=document.getElementById('templateLayerFields'),nav=document.querySelector('.apanam-mobile-bar');if(!stage||!workspace||!aside||!nav||!bar||!list)return;
const pageNav=document.createElement('nav');pageNav.id='studioMobilePageNav';pageNav.setAttribute('aria-label','Studio के मुख्य काम');for(const [id,label,target] of [['studioMobileTemplates','Templates','studioTemplateLibrary'],['studioMobileCreate','Create','apanamCreatorHubButton']]){const button=document.createElement('button');button.id=id;button.type='button';button.textContent=label;button.onclick=()=>document.getElementById(target)?.click();pageNav.append(button);}const video=document.createElement('a');video.href='cartoon-video.html';video.textContent='Video / Cartoon';pageNav.append(video);document.querySelector('body>header').after(pageNav);
const media=matchMedia('(max-width:900px)'),home={barParent:bar.parentElement,barNext:bar.nextSibling,listParent:list.parentElement,listNext:list.nextSibling};
const sheet=document.createElement('dialog');sheet.id='studioMobileSheet';sheet.innerHTML='<div class="mobile-sheet-heading"><strong id="mobileSheetTitle">Edit</strong><button type="button" id="mobileSheetClose">✕ बंद</button></div><div id="mobileSheetBody"></div>';document.body.append(sheet);const content=sheet.querySelector('#mobileSheetBody');const format=document.querySelector('.studio-format-strip'),formatHome=format?.parentElement,formatNext=format?.nextSibling;sheet.querySelector('#mobileSheetClose').onclick=()=>sheet.close();
const shade=document.createElement('button');shade.id='studioMobileShade';shade.type='button';shade.setAttribute('aria-label','Tools बंद करें');document.body.append(shade);const toolsClose=document.createElement('button');toolsClose.id='studioMobileToolsClose';toolsClose.type='button';toolsClose.textContent='✕ Tools बंद';const organizer=aside.querySelector('.organizer')||aside;organizer.prepend(toolsClose);const addRow=document.createElement('div');addRow.id='studioMobileAddRow';for(const [label,action]of [['Text जोड़ें',()=>document.querySelector('[data-add="text"]')?.click()],['Photo जोड़ें',()=>document.getElementById('imageUpload')?.click()],['Templates',()=>document.getElementById('studioTemplateLibrary')?.click()]]){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=()=>{closeTools();action();};addRow.append(b);}toolsClose.after(addRow);
function closeTools(){document.body.classList.remove('studio-mobile-tools-open');}toolsClose.onclick=shade.onclick=closeTools;
const createMore=document.createElement('button');createMore.id='studioMobileCreateMore';createMore.type='button';createMore.textContent='＋ और';createMore.setAttribute('aria-label','और चीजें जोड़ें');createMore.onclick=()=>{if(sheet.open)sheet.close();document.body.classList.add('studio-mobile-tools-open');};document.querySelector('#apanamCompactTools .apanam-strip')?.append(createMore);
const typingButton=document.createElement('button');typingButton.id='studioMobileTyping';typingButton.type='button';typingButton.textContent='अ Typing';typingButton.setAttribute('aria-label','Phonetic typing खोलें');createMore.before(typingButton);typingButton.onclick=()=>{let target=choose();if(target?.querySelector('img')){guideHint.textContent='Phonetic typing के लिए Text layer चुनें या Text जोड़ें।';guideHint.classList.add('mobile-guide-attention');return;}if(target?.dataset.locked==='1'){guideHint.textContent='Typing से पहले Text layer को Unlock करें।';guideHint.classList.add('mobile-guide-attention');return;}if(!target)document.querySelector('[data-add="text"]')?.click();requestAnimationFrame(()=>{textStyle.onclick();const language=document.getElementById('apanamTypingLanguage');if(language?.value==='off'){language.value='hi';language.dispatchEvent(new Event('change',{bubbles:true}));}document.getElementById('apanamRomanInput')?.focus();});};
function choose(){let el=stage.querySelector('.element.selected');if(!el){const elements=stage.querySelectorAll('.element');if(elements.length===1){el=elements[0];el.click();}}return el;}
function edit(){closeTools();if(sheet.open)sheet.close();const el=choose();if(!el){guideHint.textContent=stage.querySelector('.element')?'जिस Text या Photo को बदलना है, पहले उस पर tap करें।':'पहले Design चुनें या Text / Image जोड़ें।';guideHint.classList.add('mobile-guide-attention');return;}if(!el.querySelector('img')){requestAnimationFrame(()=>window.APANAM_EDIT_TEXT?.(el));return;}sheet.querySelector('#mobileSheetTitle').textContent='Text / Photo Edit';bar.hidden=false;content.replaceChildren(bar);sheet.showModal();}
function layers(){closeTools();if(sheet.open)sheet.close();sheet.querySelector('#mobileSheetTitle').textContent='Layers · अलग हिस्से';content.replaceChildren(list);sheet.showModal();}
const allButton=document.createElement('button');allButton.id='studioMobileAllActions';allButton.type='button';allButton.textContent='☰';allButton.setAttribute('aria-label','सभी tools का menu');allButton.title='सभी tools';document.querySelector('body>header').append(allButton);
const allActions=document.createElement('div');allActions.id='studioMobileActionGrid';
for(const [id,label]of [['studioMediaOpen','Cloud Files'],['studioTemplateLibrary','Poster / Templates'],['apanamCreatorHubButton','Create'],['saveProject','Save'],['headerEditProject','Edit'],['objectHeaderEdit','Area edit'],['loadProject','Load'],['headerDeleteProject','Project Delete'],['undo','Undo'],['redo','Redo'],['download','Download'],['apanamSocialShare','Share'],['apanamInstallApp','Install App'],['apanamSafetyButton','Safety'],['apanamHelpButton','Help']]){const b=document.createElement('button');b.type='button';b.textContent=label;b.dataset.action=id;b.onclick=()=>{sheet.close();document.getElementById(id)?.click();};allActions.append(b);}
const adminLink=document.createElement('a');adminLink.href='admin.html';adminLink.textContent='Admin Workspace';allActions.append(adminLink);
allButton.onclick=()=>{for(const b of allActions.querySelectorAll('button')){const original=document.getElementById(b.dataset.action);b.disabled=!original||original.disabled;b.title=original?.title||b.textContent;}closeTools();if(sheet.open)sheet.close();sheet.querySelector('#mobileSheetTitle').textContent='सभी बटन';content.replaceChildren(allActions);sheet.showModal();};
const textStyle=document.createElement('button');textStyle.id='studioMobileTextStyle';textStyle.type='button';textStyle.textContent='Font / रंग';document.querySelector('.studio-selection-actions').prepend(textStyle);textStyle.onclick=()=>{if(!format)return;if(sheet.open)sheet.close();sheet.querySelector('#mobileSheetTitle').textContent='Text · Typing / Font / रंग';content.replaceChildren(format);const typingStatus=document.getElementById('apanamTypingStatus');if(typingStatus)content.append(typingStatus);format.scrollLeft=0;sheet.showModal();};
const guide=document.createElement('section');guide.id='studioMobileGuide';guide.innerHTML='<div class="mobile-guide-steps"><button type="button" data-step="design">① Design चुनें</button><button type="button" data-step="edit">② बदलें</button><button type="button" data-step="finish">③ Save / Share</button></div><p id="studioMobileGuideHint" role="status">पहले Template चुनें या ऊपर Text / Image जोड़ें।</p>';workspace.prepend(guide);const guideHint=guide.querySelector('p');guide.querySelector('[data-step=design]').onclick=()=>document.getElementById('studioTemplateLibrary')?.click();guide.querySelector('[data-step=edit]').onclick=edit;
function finish(){closeTools();if(sheet.open)sheet.close();const grid=document.createElement('div');grid.className='mobile-finish-grid';for(const [id,label]of [['saveProject','Save · काम सुरक्षित रखें'],['apanamSocialShare','Share · किसी को भेजें'],['download','Download · फ़ाइल निकालें']]){const b=document.createElement('button');b.type='button';b.textContent=label;b.dataset.action=id;b.disabled=!document.getElementById(id)||document.getElementById(id).disabled;b.onclick=()=>{sheet.close();document.getElementById(id)?.click();};grid.append(b);}sheet.querySelector('#mobileSheetTitle').textContent='काम तैयार है';content.replaceChildren(grid);sheet.showModal();}guide.querySelector('[data-step=finish]').onclick=finish;
const quickEdit=document.createElement('div');quickEdit.id='studioMobilePhotoActions';for(const [id,label]of [['studioTextAreaEdit','छपा Text बदलें'],['objectImageEdit','फोटो का हिस्सा चुनें']]){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=()=>{if(sheet.open)sheet.close();document.getElementById(id)?.click();};quickEdit.append(b);}document.getElementById('studioSelectionBar').after(quickEdit);
function guideSync(){const el=stage.querySelector('.element.selected'),image=!!el?.querySelector('img');quickEdit.hidden=!image;guideHint.classList.remove('mobile-guide-attention');guideHint.textContent=image?'पूरी photo हिलाने के लिए drag करें। अंदर का Text / हिस्सा बदलने के लिए नीचे चुनें।':el?'Text बदलने के लिए ② बदलें दबाएँ। जगह बदलने के लिए drag करें।':stage.querySelector('.element')?'बदलने के लिए poster के Text या Photo पर tap करें।':'पहले Design चुनें या ऊपर Text / Image जोड़ें।';}let guideFrame;new MutationObserver(()=>{cancelAnimationFrame(guideFrame);guideFrame=requestAnimationFrame(guideSync);}).observe(stage,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});guideSync();
const entries=[['▣','Templates',()=>document.getElementById('studioTemplateLibrary')?.click()],['✎','Edit',edit],['▤','Layers',layers],['＋','Tools',()=>{if(sheet.open)sheet.close();document.body.classList.add('studio-mobile-tools-open');}],['↓','Download',()=>document.getElementById('download')?.click()]];
nav.replaceChildren();for(const [icon,label,action]of entries){const b=document.createElement('button');b.type='button';b.setAttribute('aria-label',label);b.innerHTML='<span>'+icon+'</span><small>'+({Templates:'Design',Edit:'बदलें',Layers:'Layers',Tools:'जोड़ें',Download:'Download'}[label]||label)+'</small>';b.onclick=action;nav.append(b);}
function libraryReady(){const ready=!!document.getElementById('studioTemplateLibrary')?.onclick;guide.querySelector('[data-step=design]').disabled=!ready;nav.querySelector('[aria-label=Templates]').disabled=!ready;guide.querySelector('[data-step=design]').textContent=ready?'① Design चुनें':'① लोड हो रहा है…';}document.addEventListener('apanam-library-ready',libraryReady);libraryReady();
let lastTouch=null;for(const region of [nav,sheet,aside,guide,quickEdit])region.addEventListener('pointerup',e=>{const b=e.target.closest('button');if(!media.matches||e.pointerType!=='touch'||!b||b.disabled||e.target.closest('#stage'))return;e.preventDefault();lastTouch={x:e.clientX,y:e.clientY,t:performance.now()};b.click();});document.addEventListener('click',e=>{if(e.isTrusted&&lastTouch&&performance.now()-lastTouch.t<700&&Math.hypot(e.clientX-lastTouch.x,e.clientY-lastTouch.y)<24){e.preventDefault();e.stopImmediatePropagation();lastTouch=null;}},true);
// Pixel selection has its own full-screen editor. Close the menu before starting it.
sheet.addEventListener('click',e=>{if(e.target.closest('button')?.textContent.includes('Canvas में चुनें'))sheet.close();if(e.target.closest('#studioTextAreaEdit,#objectImageEdit,#templateCanvasTextEdit'))sheet.close();},true);
sheet.addEventListener('close',()=>{if(sheet.open)return;if(format&&content.contains(format))restore(format,formatHome,formatNext);const typingStatus=document.getElementById('apanamTypingStatus');if(typingStatus&&content.contains(typingStatus))document.getElementById('apanamPhoneticBox')?.append(typingStatus);});
function restore(node,parent,next){if(parent?.isConnected)parent.insertBefore(node,next?.parentElement===parent?next:null);}
function fit(){if(!media.matches||document.querySelector('dialog:modal'))return;const wrap=document.getElementById('stageWrap'),area=workspace.getBoundingClientRect(),controls=[guide,quickEdit,document.getElementById('studioSelectionBar'),workspace.querySelector('.zoomBar')].reduce((n,e)=>n+(e?.getBoundingClientRect().height||0)+8,0),scale=Math.min(1,(workspace.clientWidth-24)/(stage.offsetWidth+16),Math.max(140,area.height-controls-24)/(stage.offsetHeight+16));window.APANAM_WORKFLOW?.setZoom(scale);workspace.scrollTop=workspace.scrollLeft=0;}
function layout(){closeTools();if(sheet.open)sheet.close();if(media.matches){document.body.classList.add('studio-mobile-layout');content.append(bar,list);if(format)restore(format,formatHome,formatNext);requestAnimationFrame(fit);}else{document.body.classList.remove('studio-mobile-layout');if(format)restore(format,formatHome,formatNext);const desktop=innerWidth>=1100;restore(bar,desktop?document.getElementById('studioLayerInspector'):home.barParent,desktop?null:home.barNext);restore(list,desktop?document.querySelector('.studio-layers-pane'):home.listParent,desktop?null:home.listNext);}}
let layoutWidth=innerWidth;window.addEventListener('resize',()=>{if(innerWidth!==layoutWidth){layoutWidth=innerWidth;layout();}else fit();});media.addEventListener('change',layout);new MutationObserver(()=>{if(media.matches)requestAnimationFrame(fit);}).observe(stage,{attributes:true,attributeFilter:['style']});document.getElementById('zoomFit')?.addEventListener('click',()=>requestAnimationFrame(fit));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeTools();});layout();setTimeout(fit,250);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();


