import { auth } from "@/auth";
import { redirect } from "next/navigation";
import AdminControls from "@/components/admin-controls";
import { getFeatures } from "@/lib/features";
import { neon } from "@neondatabase/serverless";
import { AdminRequestStatus } from "@/components/request-status";
import AdminSummary from "@/components/admin-summary";
const adminEmail = "apanambusiness@gmail.com";
export default async function Admin(){const session=await auth();if(session?.user?.email!==adminEmail)redirect("/studio");const features=await getFeatures(); const sql = process.env.DATABASE_URL ? neon(process.env.DATABASE_URL) : null; const statsRows = sql ? await sql`select count(*) filter (where type = 'Manual custom design') as total, count(*) filter (where type = 'Manual custom design' and status = 'requested') as requested, count(*) filter (where type = 'Manual custom design' and status = 'in_progress') as in_progress, count(*) filter (where type = 'Manual custom design' and status = 'ready') as ready, count(*) filter (where type = 'Manual custom design' and status = 'delivered') as delivered, (select count(*) from creator_profiles) as creators from creations` : []; const stat = statsRows[0]; const stats = { creators: Number(stat?.creators ?? 0), total: Number(stat?.total ?? 0), requested: Number(stat?.requested ?? 0), inProgress: Number(stat?.in_progress ?? 0), ready: Number(stat?.ready ?? 0), delivered: Number(stat?.delivered ?? 0) }; const requests=sql ? await sql`select id, status, language, prompt, output_url, created_at from creations where type = 'Manual custom design' order by created_at desc limit 20` : []; return <main><header><a href="/studio" className="brand"><span>T</span>ToonSutra <i>AI</i></a><a href="/studio" className="text-button">Creator studio</a></header><section className="admin"><p className="eyebrow">TOONSUTRA ADMIN</p><h1>Control center</h1><p>Free aur paid tools ko yahan se manage kijiye.</p><AdminSummary stats={stats}/><AdminControls initial={features}/><AdminRequestStatus initial={requests.map((item) => ({ id: String(item.id), status: String(item.status), language: String(item.language), prompt: String(item.prompt), createdAt: String(item.created_at), outputUrl: item.output_url ? String(item.output_url) : undefined }))}/></section></main>}
