-- Everything, including synthetic accounts and quota changes, is rolled back.
begin;
create temporary table qa_people(role_name text primary key,id uuid default gen_random_uuid());
insert into qa_people(role_name) values('member'),('other'),('admin');
grant select on qa_people to authenticated,anon,service_role;
insert into auth.users(id,email,email_confirmed_at,is_anonymous) select id,id::text||'@example.invalid',now(),false from qa_people;
insert into public.studio_admins(user_id) select id from qa_people where role_name='admin';
create temporary table qa_values(name text primary key,value text);
grant select,insert on qa_values to authenticated,service_role;
create function pg_temp.assert_true(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label; end if; end $$;
create function pg_temp.expect_error(command text,pattern text) returns void language plpgsql as $$declare failed boolean:=false; begin begin execute command; exception when others then if position(pattern in sqlerrm)>0 then failed:=true; else raise; end if; end; if not failed then raise exception 'Expected rejection: %',command; end if; end $$;
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',(select id from qa_people where role_name='member'),'role','authenticated')::text,true);
select pg_temp.assert_true((public.studio_business_overview()->>'manual_open')::boolean,'pre-launch manual remains open');
insert into qa_values(name,value) select 'trial',public.studio_start_trial()->>'started_at';
select pg_temp.assert_true(public.studio_start_trial()->>'started_at'=(select value from qa_values where name='trial'),'trial repeat does not extend expiry');
select pg_temp.assert_true((public.studio_start_trial()->>'expires_at')::timestamptz-(select value::timestamptz from qa_values where name='trial')=interval '15 days','trial exactly fifteen days');
insert into public.studio_notification_preferences(user_id,email_reminders) select id,true from qa_people where role_name='member';
select pg_temp.expect_error('select public.studio_admin_business(''rates'',''{"kind":"poster","cost":100,"margin":30}''::jsonb)','Admin required');
select pg_temp.expect_error('select public.studio_media_reserve(gen_random_uuid(),''bad'',1,''image/png'')','permission denied');
select pg_temp.expect_error('update public.studio_business_settings set payments_enabled=true','permission denied');
select pg_temp.expect_error('select public.studio_ai_quote(''poster'',0)','Units must be');
select pg_temp.assert_true(not (public.studio_ai_quote('poster',1)->>'generation_enabled')::boolean,'no paid generation before provider/payment setup');
select set_config('request.jwt.claims',jsonb_build_object('sub',(select id from qa_people where role_name='other'),'role','authenticated')::text,true);
select pg_temp.assert_true((select count(*) from public.studio_trials)=0,'other user cannot see trial');
select pg_temp.assert_true((select count(*) from public.studio_notification_preferences)=0,'other user cannot see consent');
select pg_temp.expect_error('insert into public.studio_notification_preferences(user_id,email_reminders) select id,true from qa_people where role_name=''member''','row-level security');
select set_config('request.jwt.claims',jsonb_build_object('sub',(select id from qa_people where role_name='admin'),'role','authenticated')::text,true);
select public.studio_admin_business('rates','{"kind":"poster","provider":"QA only","cost":100,"margin":30}');
select pg_temp.assert_true((public.studio_ai_quote('poster',2)->>'sale_paise')::integer=286,'sale rounds upward and keeps margin');
select pg_temp.expect_error('select public.studio_admin_business(''rates'',''{"kind":"poster","cost":100,"margin":10}''::jsonb)','check constraint');
reset role;
update public.studio_trials set started_at=now()-interval '14 days',expires_at=now()+interval '1 day' where user_id=(select id from qa_people where role_name='member');
insert into public.studio_memberships(user_id,plan,expires_at,granted_by,revoked,granted_at) select a.id,'manual_complimentary',now()+interval '1 day',b.id,false,now() from qa_people a cross join qa_people b where a.role_name='member' and b.role_name='admin';
select studio_private.prepare_reminders();
insert into qa_values(name,value) select 'queue',count(*)::text from studio_private.reminder_queue where user_id=(select id from qa_people where role_name='member');
select studio_private.prepare_reminders();
select pg_temp.assert_true((select count(*)::text from studio_private.reminder_queue where user_id=(select id from qa_people where role_name='member'))=(select value from qa_values where name='queue'),'duplicate reminders are suppressed');
select pg_temp.assert_true((select value::int from qa_values where name='queue')=1,'consenting expiring user gets one queue item');
set local role service_role;
select pg_temp.assert_true(public.studio_claim_reminders()='[]'::jsonb,'reminder sending disabled by default');
insert into qa_values(name,value) select 'file',(public.studio_media_reserve((select id from qa_people where role_name='member'),'QA file',10485760,'image/png')).id::text;
select public.studio_media_state((select id from qa_people where role_name='member'),(select value::uuid from qa_values where name='file'),'ready');
select pg_temp.expect_error('select public.studio_media_download((select id from qa_people where role_name=''other''),(select value::uuid from qa_values where name=''file''))','not yours');
select public.studio_media_reserve((select id from qa_people where role_name='member'),'QA second',10485760,'image/png');
select public.studio_media_reserve((select id from qa_people where role_name='member'),'QA third',10485760,'image/png');
select pg_temp.expect_error('select public.studio_media_reserve((select id from qa_people where role_name=''member''),''over quota'',1,''image/png'')','30 MB');
reset role;
select pg_temp.assert_true((select used_bytes from studio_private.media_budget where id)=31457280,'quota reserve is exact and failed operation is atomic');
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',(select id from qa_people where role_name='other'),'role','authenticated')::text,true);
select pg_temp.assert_true((select count(*) from public.studio_media_files)=0,'cross-user media invisible');
select set_config('request.jwt.claims',jsonb_build_object('sub',(select id from qa_people where role_name='member'),'role','authenticated')::text,true);
select pg_temp.assert_true((select count(*) from public.studio_media_files)=3,'owner sees own media');
select pg_temp.expect_error('update public.studio_media_files set bytes=1','permission denied');
set local role anon;
select pg_temp.expect_error('select * from public.studio_media_files','permission denied');
select pg_temp.expect_error('select public.studio_start_trial()','permission denied');
reset role;
update public.studio_notification_preferences set email_reminders=false where user_id=(select id from qa_people where role_name='member');
select studio_private.prepare_reminders();
select pg_temp.assert_true(not exists(select 1 from studio_private.reminder_queue where user_id=(select id from qa_people where role_name='member') and status='pending'),'opting out cancels pending reminders');
set local role service_role;
select pg_temp.assert_true((public.studio_media_reserve((select id from qa_people where role_name='other'),'Recorded WebM',12,'audio/webm')).mime='audio/webm','WebM narration accepted');
select pg_temp.assert_true((public.studio_media_reserve((select id from qa_people where role_name='other'),'Recorded M4A',12,'audio/mp4')).mime='audio/mp4','M4A narration accepted');
select pg_temp.expect_error('select public.studio_media_reserve((select id from qa_people where role_name=''member''),''recorded over quota'',12,''audio/webm'')','30 MB');
reset role;
select pg_temp.assert_true((select not public and file_size_limit=10485760 and allowed_mime_types @> array['audio/webm','audio/mp4'] from storage.buckets where id='studio-private-media'),'recorded audio bucket stays private and size limited');
select 'PASS: trial, margin, consent, queue deduplication, media quotas, ownership and blocked payments' as result;
rollback;

