'use client';
import {useRef,useState} from 'react';
import {Image,Video,Sparkles,FolderOpen,Crown,Download,Plus,Type,Upload,Undo2,Redo2,Phone,Globe,MapPin,Instagram,MessageCircle,Layers3,Trash2,Copy} from 'lucide-react';
const starter=[
{id:'logo',kind:'text',text:'YOUR LOGO',x:35,y:28,w:130,h:44,size:15,color:'#ffffff'},
{id:'title',kind:'text',text:'BIG SALE',x:55,y:125,w:310,h:75,size:54,color:'#ffffff'},
{id:'offer',kind:'text',text:'UP TO 50% OFF',x:58,y:215,w:280,h:50,size:27,color:'#fde047'},
{id:'phone',kind:'text',text:'+91 98765 43210',x:55,y:390,w:220,h:34,size:18,color:'#ffffff'},
{id:'web',kind:'text',text:'www.apanam.online',x:55,y:430,w:230,h:34,size:16,color:'#ffffff'}];
export default function Home(){const [items,setItems]=useState(starter),[selected,setSelected]=useState('title'),[bg,setBg]=useState('#5b21b6'),[drag,setDrag]=useState(null);const file=useRef();const sel=items.find(x=>x.id===selected);const patch=(id,p)=>setItems(a=>a.map(x=>x.id===id?{...x,...p}:x));
const addText=(text='New text')=>{const id='e'+Date.now();setItems(a=>[...a,{id,kind:'text',text,x:130,y:280,w:240,h:48,size:25,color:'#ffffff'}]);setSelected(id)};
const upload=e=>{const f=e.target.files?.[0];if(!f)return;const id='img'+Date.now();setItems(a=>[...a,{id,kind:'image',src:URL.createObjectURL(f),x:310,y:290,w:180,h:180}]);setSelected(id)};
const move=e=>{if(!drag)return;const r=e.currentTarget.getBoundingClientRect();patch(drag.id,{x:Math.max(0,Math.min(540-drag.w,e.clientX-r.left-drag.dx)),y:Math.max(0,Math.min(540-drag.h,e.clientY-r.top-drag.dy))})};
return <main className="shell"><aside><div className="brand"><div className="mark">A</div><div><b>APANAM</b><small>AI Creative Studio</small></div></div><nav><button className="active"><Image size={19}/>Poster Maker</button><button><Video size={19}/>Video Studio <span className="soon">Soon</span></button><button><Sparkles size={19}/>AI Creator <span className="soon">Soon</span></button><button><FolderOpen size={19}/>My Designs</button></nav><div className="upgrade"><Crown/><b>FREE-FIRST</b><p>Manual tools first. Paid AI remains off.</p></div></aside><section className="workspace"><header><div><h1>Manual Poster Maker</h1><p>Drag every text, image, logo and contact detail anywhere.</p></div><div className="headBtns"><button><FolderOpen size={18}/> Projects</button><button className="primary"><Plus size={18}/> New Design</button></div></header><div className="proEditor">
<section className="toolrail"><button onClick={()=>addText()}><Type/>Text</button><button onClick={()=>file.current.click()}><Upload/>Photo</button><button onClick={()=>addText('YOUR LOGO')}><Image/>Logo</button><button onClick={()=>addText('+91 98765 43210')}><Phone/>Mobile</button><button onClick={()=>addText('WhatsApp: 98765 43210')}><MessageCircle/>WhatsApp</button><button onClick={()=>addText('@yourbusiness')}><Instagram/>Social</button><button onClick={()=>addText('www.yourwebsite.com')}><Globe/>Website</button><button onClick={()=>addText('Your business address')}><MapPin/>Address</button><button><Layers3/>Layers</button><input ref={file} hidden type="file" accept="image/*" onChange={upload}/></section>
<section className="canvasArea"><div className="toolbar"><button><Undo2 size={17}/></button><button><Redo2 size={17}/></button><b>Instagram 1080 × 1080</b><span className="spacer"/><button onClick={()=>addText()}><Type size={17}/> Text</button><button onClick={()=>file.current.click()}><Upload size={17}/> Upload</button></div><div className="stage"><div className="poster designCanvas" style={{background:`linear-gradient(145deg,${bg},#111827)`}} onMouseMove={move} onMouseUp={()=>setDrag(null)} onMouseLeave={()=>setDrag(null)}>{items.map(i=><div key={i.id} className={'designItem '+(selected===i.id?'selected':'')} style={{left:i.x,top:i.y,width:i.w,height:i.h,fontSize:i.size,color:i.color}} onMouseDown={e=>{e.stopPropagation();setSelected(i.id);setDrag({id:i.id,dx:e.nativeEvent.offsetX,dy:e.nativeEvent.offsetY,w:i.w,h:i.h})}}>{i.kind==='image'?<img src={i.src} draggable="false"/>:<span>{i.text}</span>}{selected===i.id&&<><i className="handle br"/><i className="handle mr"/><i className="handle mb"/></>}</div>)}</div></div><div className="canvasBottom"><span>Drag items • Exact size controls →</span><button className="primary"><Download size={17}/> Download</button></div></section>
<section className="properties"><h3>Element Properties</h3>{sel?<><label>{sel.kind==='image'?'Image':'Text'}{sel.kind==='text'&&<input value={sel.text} onChange={e=>patch(sel.id,{text:e.target.value})}/>}</label><div className="grid2"><label>X<input type="number" value={Math.round(sel.x)} onChange={e=>patch(sel.id,{x:+e.target.value})}/></label><label>Y<input type="number" value={Math.round(sel.y)} onChange={e=>patch(sel.id,{y:+e.target.value})}/></label><label>Width<input type="number" value={sel.w} onChange={e=>patch(sel.id,{w:+e.target.value})}/></label><label>Height<input type="number" value={sel.h} onChange={e=>patch(sel.id,{h:+e.target.value})}/></label></div>{sel.kind==='text'&&<><label>Font size<input type="range" min="10" max="100" value={sel.size} onChange={e=>patch(sel.id,{size:+e.target.value})}/></label><label>Color<input type="color" value={sel.color} onChange={e=>patch(sel.id,{color:e.target.value})}/></label></>}<div className="actionrow"><button onClick={()=>setItems(a=>[...a,{...sel,id:'copy'+Date.now(),x:sel.x+18,y:sel.y+18}])}><Copy/>Copy</button><button onClick={()=>{setItems(a=>a.filter(x=>x.id!==sel.id));setSelected(null)}}><Trash2/>Delete</button></div></>:<p>Click any poster element.</p>}<h3>Background</h3><div className="colors">{['#5b21b6','#be123c','#0369a1','#047857','#111827','#ea580c'].map(c=><button key={c} onClick={()=>setBg(c)} style={{background:c}}/>)}</div><p className="hint">X/Y changes position. Width/Height gives independent horizontal and vertical sizing.</p></section></div></section></main>}
