"use client";
import { useState } from "react";

type Product={id:string;icon:string;name:string;price:string;note:string};
const products:Product[]=[{id:"poster",icon:"✦",name:"Poster",price:"₹15 se",note:"Social, film aur shop poster"},{id:"festival",icon:"✺",name:"Festival poster",price:"₹25 se",note:"Festival, birthday aur wishes"},{id:"manual",icon:"✎",name:"Custom design",price:"₹99+",note:"Designer-assisted special work"},{id:"video",icon:"🎬",name:"Cartoon video",price:"Coming soon",note:"Short animated story"}];
const themes=["Traditional Indian","Festival","Cartoon","Movie poster","Instagram post","Minimal","Luxury gold","Kids fun","Shop offer","Wedding","Devotional","Modern neon"];
const languages=["Hindi","English","Hinglish","Bengali","Marathi","Tamil","Telugu","Kannada","Malayalam","Gujarati","Punjabi","Urdu","Odia"];
const templates=[
 {name:"Ganesh Chaturthi",idea:"Ganesh Chaturthi ki hardik shubhkamnayein, traditional decoration aur festive mood",theme:"Traditional Indian",language:"Hindi"},
 {name:"Diwali offer",idea:"Diwali special shop offer, diyas, rangoli aur family festival mood",theme:"Festival",language:"Hindi"},
 {name:"Birthday",idea:"Happy Birthday celebration, cake, balloons aur joyful friends",theme:"Kids fun",language:"English"},
 {name:"Shop opening",idea:"Nayi dukaan ka grand opening, local business welcome message aur festive decoration",theme:"Shop offer",language:"Hindi"},
 {name:"Movie idea",idea:"Ek chhote shehar ke hero ki inspiring cinematic journey",theme:"Movie poster",language:"Hindi"},
 {name:"Wedding",idea:"Shaadi ki hardik badhai, elegant flowers aur family celebration",theme:"Wedding",language:"Hindi"},
];
type Props={profile:{plan:string;credits:number;trialStartedAt:string|null;history:Array<{type:string;language:string;prompt:string;createdAt:string}>}};
export default function Creator({profile}:Props){
 const [product,setProduct]=useState(products[0]);const [idea,setIdea]=useState("");const [theme,setTheme]=useState(themes[0]);const [language,setLanguage]=useState("Hindi");const [brief,setBrief]=useState("");const [status,setStatus]=useState("Step 1: template ya service choose kijiye.");const [loading,setLoading]=useState(false);
 const apply=(item:typeof templates[number])=>{setIdea(item.idea);setTheme(item.theme);setLanguage(item.language);setBrief("");setStatus(`${item.name} ready hai. Neeche apna text badal sakte hain.`)};
 async function makeBrief(){if(!idea.trim()){setStatus("Pehle poster ya story ka idea likhiye.");return}setLoading(true);try{const response=await fetch("/api/creative-assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idea:`${idea}\nTheme: ${theme}`,language,type:product.name})});const data=await response.json();if(!response.ok)throw new Error(data.error);setBrief(data.text);setStatus("Creative brief ready hai. Aap ise copy karke designer ko bhej sakte hain.")}catch(error){setStatus(error instanceof Error?error.message:"Creative brief abhi available nahi hai.")}finally{setLoading(false)}}
 return <>
 <section className="quick-create"><div><p className="eyebrow">EASY CREATOR</p><h2>3 step mein apna design plan banaiye.</h2><p>Template choose karein, text edit karein, phir free creative brief banaiye.</p></div><ol><li><b>1</b> Choose</li><li><b>2</b> Edit</li><li><b>3</b> Create</li></ol></section>
 <section className="template-section"><div className="picker-heading"><div><p className="eyebrow">QUICK START</p><h2>Ready templates</h2></div><p>Apne kaam ke according template select kijiye.</p></div><div className="template-grid">{templates.map(item=><button type="button" key={item.name} onClick={()=>apply(item)}><b>{item.name}</b><span>{item.theme} · {item.language}</span><small>Choose →</small></button>)}</div></section>
 <section className="easy-editor"><div className="editor-side"><p className="eyebrow">STEP 1 · WHAT DO YOU WANT TO MAKE?</p><div className="service-tabs">{products.map(item=><button type="button" className={product.id===item.id?"active":""} onClick={()=>{setProduct(item);setStatus(`${item.name} select hua. Ab theme aur text edit kijiye.`)}} key={item.id}><span>{item.icon}</span><b>{item.name}</b><small>{item.price}</small></button>)}</div><p className="eyebrow">STEP 2 · CHOOSE A DESIGN THEME</p><div className="theme-grid">{themes.map(item=><button key={item} type="button" className={theme===item?"active":""} onClick={()=>setTheme(item)}>{item}</button>)}</div><label htmlFor="idea">STEP 3 · EDIT YOUR TEXT</label><textarea id="idea" value={idea} onChange={e=>setIdea(e.target.value)} placeholder="Example: Ganesh Chaturthi ki hardik shubhkamnayein · Shop name · Mobile number · Offer"/><div className="editor-options"><select value={language} onChange={e=>setLanguage(e.target.value)} aria-label="Language">{languages.map(item=><option key={item}>{item}</option>)}</select><div><span>Selected theme</span><b>{theme}</b></div></div><button type="button" className="button make-button" disabled={loading} onClick={makeBrief}>{loading?"Ban raha hai…":"Create free design brief →"}</button><small>{status}</small></div>
 <aside className="preview-card"><p className="eyebrow">YOUR DESIGN PREVIEW</p><div className={`theme-preview ${theme.toLowerCase().replaceAll(" ","-")}`}><span>{product.icon}</span><b>{theme}</b><small>{language}</small></div><h3>{product.name}</h3><p>{idea || "Template choose karke apna text edit kijiye."}</p><div className="preview-meta"><span>Theme <b>{theme}</b></span><span>Starting price <b>{product.price}</b></span></div>{brief&&<pre className="brief">{brief}</pre>}<button type="button" className="outline" onClick={async()=>{try{await navigator.clipboard.writeText(brief||idea);setStatus("Text copy ho gaya.")}catch{setStatus("Copy permission nahi mili. Text select karke copy kijiye.")}}}>Copy text</button></aside></section>
 <section className="trial-banner"><b>3 din free</b><span>{profile.credits} trial credits · Image/video aur online payment abhi paused hain.</span></section>
 </>}
