const origin='https://apanambusiness-ship-it.github.io';
function mapped(name:string,old:string){try{return JSON.parse(Deno.env.get(name)||'{}').default||Deno.env.get(old)||'';}catch{return Deno.env.get(old)||'';}}
const base=Deno.env.get('SUPABASE_URL')||'',secret=mapped('SUPABASE_SECRET_KEYS','SUPABASE_SERVICE_ROLE_KEY'),anon=mapped('SUPABASE_PUBLISHABLE_KEYS','SUPABASE_ANON_KEY');
const headers={'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Headers':'authorization,apikey,content-type','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json','Cache-Control':'no-store'};
const json=(v:unknown,status=200)=>new Response(JSON.stringify(v),{status,headers});
async function db(path:string,options:RequestInit={},token=secret){const r=await fetch(base+path,{...options,headers:{apikey:token===secret?secret:anon,...(token!==secret||secret.split('.').length===3?{Authorization:'Bearer '+token}:{}),...options.headers},signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('Support database unavailable');const text=await r.text();return text?JSON.parse(text):null;}
const rpc=(name:string,args:Record<string,unknown>)=>db('/rest/v1/rpc/'+name,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(args)});
async function body(req:Request){const reader=req.body?.getReader();if(!reader)return {};const decoder=new TextDecoder();let raw='',size=0;for(;;){const v=await reader.read();if(v.done)break;size+=v.value.length;if(size>12000){await reader.cancel();throw Error('Request too large');}raw+=decoder.decode(v.value,{stream:true});}return JSON.parse(raw+decoder.decode()||'{}');}
// Operator arms a single fixed, non-user probe in private SQL. Public requests cannot re-arm it.
Deno.serve(async(req:Request)=>{if(req.headers.get('origin')&&req.headers.get('origin')!==origin)return json({error:'Origin denied'},403);if(req.method==='OPTIONS')return new Response(null,{status:204,headers});if(req.method!=='POST')return json({error:'POST required'},405);let owner='';try{
 const action=new URL(req.url).searchParams.get('action')||'status';
 if(action==='probe'){
  if(await rpc('studio_chat_probe_claim',{})!==true)return json({error:'No operator-armed probe'},409);
  let code='unknown';try{const response=await provider([{role:'user',content:'What is 2 + 2? Reply with only the number.'}],32);code=response.ok?'ok':errorCode(response.status);if(response.ok){const result=await response.json();if(String(result?.choices?.[0]?.message?.content||'').trim()!=='4')code='invalid_response';}}catch{}
  await rpc('studio_chat_probe_finish',{result_code:code});return json({ok:code==='ok',code},code==='ok'?200:502);
 }
 const token=(req.headers.get('authorization')||'').replace(/^Bearer /i,'');if(!token)return json({error:'Login required'},401);let user:any;try{user=await db('/auth/v1/user',{},token);}catch{return json({error:'Session invalid'},401);}if(!user?.id||user.is_anonymous||!user.email_confirmed_at)return json({error:'Verified account required'},403);owner=user.id;
 const config=await rpc('studio_chat_status',{owner_id:owner}),enabled=config?.enabled===true&&!!Deno.env.get('SARVAM_API_KEY');
 if(action==='status')return json({...config,enabled,mode:enabled?'general-ai':'local-guide'});if(action!=='ask')return json({error:'Unknown action'},400);if(!enabled)return json({error:'AI Chat अभी उपलब्ध नहीं है। App सहायता के shortcuts इस्तेमाल करें।'},403);
 let value:any;try{value=await body(req);}catch{return json({error:'सवाल और बातचीत का आकार बहुत बड़ा या गलत है।'},400);}const question=String(value.question||'').trim();
 if(value.consent!==true||value.consent_version!=='chat-context-sarvam-v2')return json({error:'सवाल और हाल की बातचीत Sarvam को भेजने की अनुमति जरूरी है।'},400);
 const privateText=/(sb_secret_|sk_[a-z0-9]|password\s*[:=]|otp\s*[:=]|\b\d{16}\b)/i;
 if(!question||[...question].length>1000||privateText.test(question))return json({error:'1000 अक्षरों तक सवाल लिखें; password, OTP, card या API key न दें।'},400);
 const history=value.history??[];if(!Array.isArray(history)||history.length>6||history.some((m:any)=>!m||!['user','assistant'].includes(m.role)||typeof m.content!=='string'||m.content.length>2400||privateText.test(m.content)))return json({error:'बातचीत का संदर्भ अमान्य है। बातचीत साफ करके फिर पूछें।'},400);
 if(new TextEncoder().encode(JSON.stringify(history)).length>6000)return json({error:'पुराना संदर्भ बहुत बड़ा है। बातचीत साफ करके फिर पूछें।'},400);
 if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(String(value.request_id||'')))return json({error:'Valid request ID required'},400);
 const claim=await rpc('studio_support_ai_claim',{owner_id:owner,request_id:value.request_id}).catch(()=>null);if(claim!==true)return json({error:'दैनिक सीमा, 10 सेकंड का अंतर या duplicate request है। थोड़ी देर बाद पूछें; automatic retry नहीं हुई।'},429);
 const system='You are APANAMai AI Chat, a helpful general-purpose assistant. Answer knowledge, learning, writing, stories, translation, business ideas and coding questions in the user language; support Indian languages. Follow the conversation. Be concise, useful and honest. You have no live web search, account, bank, payment, ticket or device access and cannot perform actions. Do not invent current facts or claim to have checked anything. Ask for essential clarification. Give general health/legal/financial information with appropriate uncertainty rather than definitive personal professional advice. Refuse harmful requests appropriately. Never request or reveal passwords, OTPs, card details or API keys. App-specific facts: registration Rs10, first trial15 days, membership Rs100 every30 days with explicit mandate consent; real AutoPay activation remains unconfirmed. AI chat currently has a limited included quota and never debits a user wallet. Do not claim provider image/video/audio generation is enabled.';
 const response=await provider([{role:'system',content:system},...history.map((m:any)=>({role:m.role,content:m.content})),{role:'user',content:question}],600);
 if(!response.ok){await rpc('studio_health_report',{owner_id:owner,service_name:'support',error_code:errorCode(response.status)}).catch(()=>{});return json({error:response.status===429?'AI provider की सीमा पूरी है। बाद में पूछें।':'AI provider उत्तर नहीं दे पाया। App सहायता लें; automatic retry नहीं हुई।'},502);}const result=await response.json();const text=String(result?.choices?.[0]?.message?.content||'').trim();if(!text){await rpc('studio_health_report',{owner_id:owner,service_name:'support',error_code:'unknown'}).catch(()=>{});return json({error:'AI से खाली उत्तर आया।'},502);}return json({answer:text.slice(0,2400),source:'sarvam-ai',account_access:false,truncated:result?.choices?.[0]?.finish_reason==='length'||text.length>2400});
 }catch{if(owner)await rpc('studio_health_report',{owner_id:owner,service_name:'support',error_code:'unknown'}).catch(()=>{});return json({error:'AI Chat पूरी नहीं हुई। App सहायता लें; automatic retry नहीं हुई।'},503);}});
function errorCode(status:number){return status===401?'http401':status===403?'http403':status===429?'http429':'http500';}
function provider(messages:any[],max_tokens:number){return fetch('https://api.sarvam.ai/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','api-subscription-key':Deno.env.get('SARVAM_API_KEY')||''},body:JSON.stringify({model:'sarvam-105b-conversations',reasoning_effort:null,temperature:0.4,max_tokens,stream:false,messages}),signal:AbortSignal.timeout(25000)});}
