const origin='https://apanambusiness-ship-it.github.io';
function mapped(name:string,old:string){try{return JSON.parse(Deno.env.get(name)||'{}').default||Deno.env.get(old)||'';}catch{return Deno.env.get(old)||'';}}
const base=Deno.env.get('SUPABASE_URL')||'',secret=mapped('SUPABASE_SECRET_KEYS','SUPABASE_SERVICE_ROLE_KEY'),anon=mapped('SUPABASE_PUBLISHABLE_KEYS','SUPABASE_ANON_KEY');
const headers={'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Headers':'authorization,apikey,content-type','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json','Cache-Control':'no-store'};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers});
async function db(path:string,options:RequestInit={},token=secret){const r=await fetch(base+path,{...options,headers:{apikey:token===secret?secret:anon,...(token!==secret||secret.split('.').length===3?{Authorization:'Bearer '+token}:{}),...options.headers},signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('Database HTTP '+r.status);return r.json();}
const rpc=(name:string,args:Record<string,unknown>)=>db('/rest/v1/rpc/'+name,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(args)});
async function bounded(req:Request){const reader=req.body?.getReader();if(!reader)return {};let raw='',size=0;const decoder=new TextDecoder();for(;;){const v=await reader.read();if(v.done)break;size+=v.value.length;if(size>2048){await reader.cancel();throw Error('Request too large');}raw+=decoder.decode(v.value,{stream:true});}return JSON.parse(raw+decoder.decode()||'{}');}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers});if(req.method!=='POST')return json({error:'POST required'},405);try{
 const token=(req.headers.get('authorization')||'').replace(/^Bearer /i,'');if(!token)return json({error:'Login required'},401);let user:any;try{user=await db('/auth/v1/user',{},token);}catch{return json({error:'Session invalid'},401);}if(!user?.id||user.is_anonymous||!user.email_confirmed_at)return json({error:'Verified account required'},403);
 const action=new URL(req.url).searchParams.get('action')||'status';
 if(action==='report'){const body=await bounded(req);return json({accepted:await rpc('studio_health_report',{owner_id:user.id,service_name:body.service,error_code:body.code})});}
 if(action!=='status')return json({error:'Unknown action'},400);
 const admins=await db('/rest/v1/studio_admins?select=user_id&user_id=eq.'+encodeURIComponent(user.id),{},token);if(!Array.isArray(admins)||admins.length!==1)return json({error:'Admin required'},403);
 const mode=Deno.env.get('STUDIO_PAYMENT_MODE')||'sandbox',prefix=mode==='production'?'CASHFREE_LIVE_':'CASHFREE_TEST_',cashConfigured=!!Deno.env.get(prefix+'APP_ID')&&!!Deno.env.get(prefix+'SECRET_KEY');let business:any=null,events:any=[];const failures:string[]=[];
 const reads=await Promise.allSettled([db('/rest/v1/studio_business_settings?id=eq.true&select=payments_enabled,ai_enabled'),rpc('studio_health_summary',{})]);if(reads[0].status==='fulfilled')business=reads[0].value?.[0];else failures.push('business_settings');if(reads[1].status==='fulfilled')events=reads[1].value;else failures.push('diagnostic_records');
 const row=(id:string,name:string,configured:boolean,enabled:boolean,missing:string[],note:string)=>({id,name,configured,enabled,missing,note,verification:'configuration-only'});
 const services=[{id:'database',name:'Supabase database',configured:!!base&&!!secret&&!!anon,enabled:failures.length===0,missing:failures,note:failures.length?'Database/schema की read जाँच असफल।':'Database और diagnostic records की live read सफल।',verification:'live-read'},
 row('payments','Cashfree '+mode,cashConfigured,Deno.env.get('STUDIO_PAYMENTS_ENABLED')==='true'&&cashConfigured&&(mode==='sandbox'||business?.payments_enabled===true),[...(!Deno.env.get(prefix+'APP_ID')?[prefix+'APP_ID']:[]),...(!Deno.env.get(prefix+'SECRET_KEY')?[prefix+'SECRET_KEY']:[])],'Keys की मौजूदगी जाँची है; उनकी वैधता और merchant activation इस जाँच से सिद्ध नहीं होती।'),
 row('subscriptions','Cashfree AutoPay',cashConfigured,Deno.env.get('STUDIO_SUBSCRIPTIONS_ENABLED')==='true'&&cashConfigured&&(mode==='sandbox'||business?.payments_enabled===true),[], 'STUDIO_SUBSCRIPTIONS_ENABLED और live payment gate दोनों जरूरी हैं। बैंक mandate/payment test अलग है।'),
 row('voice','Sarvam आवाज़',!!Deno.env.get('SARVAM_API_KEY'),!!Deno.env.get('SARVAM_API_KEY')&&Deno.env.get('STUDIO_PAID_VOICE_ENABLED')==='true'&&business?.ai_enabled===true,!Deno.env.get('SARVAM_API_KEY')?['SARVAM_API_KEY']:[],'Key मौजूद होने से provider balance, quota या model access की पुष्टि नहीं होती। कोई paid generation नहीं चलाई गई।'),
 row('email','Expiry / payment email',!!Deno.env.get('BREVO_API_KEY')&&!!Deno.env.get('STUDIO_REMINDER_FROM'),false,[...(!Deno.env.get('BREVO_API_KEY')?['BREVO_API_KEY']:[]),...(!Deno.env.get('STUDIO_REMINDER_FROM')?['STUDIO_REMINDER_FROM']:[])],'Sender verification, scheduler और delivery logs अलग जाँचें; test email नहीं भेजा गया।'),
 row('support','Supporting AI chat',!!Deno.env.get('SARVAM_API_KEY'),Deno.env.get('STUDIO_SUPPORT_AI_ENABLED')==='true'&&!!Deno.env.get('SARVAM_API_KEY'),!Deno.env.get('SARVAM_API_KEY')?['SARVAM_API_KEY']:[],'सामान्य help स्थानीय guide से चलती है। उन्नत AI के लिए STUDIO_SUPPORT_AI_ENABLED और provider लागत की मंजूरी जरूरी है।')];
 return json({checked_at:new Date().toISOString(),environment:mode,services,events,scope:'Recorded app errors from signed-in users; not complete provider logs. No secret values, prompts or payment details are returned.'});
 }catch{return json({error:'Diagnostic जाँच असफल। Database/function configuration और deployment logs देखें।'},503);}});
